[CmdletBinding()]
param(
    [string]$VaultRoot = (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),
    [string]$OutputPath = '12_Brain/09_Ops/Health.md'
)

$ErrorActionPreference = 'Stop'
$resolvedVault = (Resolve-Path -LiteralPath $VaultRoot).Path
$testScript = Join-Path $PSScriptRoot 'Test-SecondBrain.ps1'
$knowledgeCoverageScript = Join-Path $PSScriptRoot 'Update-KnowledgeCoverage.ps1'
$clientCoverageScript = Join-Path $PSScriptRoot 'Update-ClientIntelligenceCoverage.ps1'

$knowledgeCoverage = & $knowledgeCoverageScript -VaultRoot $resolvedVault
$clientCoverage = & $clientCoverageScript -VaultRoot $resolvedVault

$testOutput = & $testScript -VaultRoot $resolvedVault -Json
$testExitCode = $LASTEXITCODE
$health = $testOutput | ConvertFrom-Json

$markdownFiles = @(
    Get-ChildItem -LiteralPath $resolvedVault -Recurse -Filter '*.md' -File |
        Where-Object {
            $_.FullName -notmatch '\\.git\\' -and
            $_.FullName -notmatch '\\node_modules\\'
        }
)

$brainFiles = @($markdownFiles | Where-Object FullName -like '*\12_Brain\*')
$captureFiles = @($markdownFiles | Where-Object FullName -like '*\12_Brain\01_Captures\*' | Where-Object Name -ne 'README.md')
$projectFiles = @($markdownFiles | Where-Object FullName -like '*\12_Brain\05_Projects\*' | Where-Object Name -ne 'README.md')
$decisionFiles = @($markdownFiles | Where-Object FullName -like '*\12_Brain\04_Decisions\*' | Where-Object Name -ne 'README.md')
$memoryFiles = @($markdownFiles | Where-Object FullName -like '*\12_Brain\08_Memory\*' | Where-Object Name -ne 'README.md')

$openTasks = 0
foreach ($file in $markdownFiles) {
    [string]$text = Get-Content -LiteralPath $file.FullName -Raw
    if ([string]::IsNullOrEmpty($text)) {
        continue
    }
    $openTasks += [regex]::Matches($text, '(?m)^\s*-\s+\[ \]\s+').Count
}

$severityLabel = if ($health.summary.errorCount -gt 0 -or $clientCoverage.status -eq 'blocked') {
    'blocked'
}
elseif ($health.summary.warningCount -gt 0 -or $clientCoverage.status -eq 'needs-review') {
    'needs-review'
}
else {
    'healthy'
}

$issueLines = New-Object System.Collections.Generic.List[string]
foreach ($issue in @($health.issues | Sort-Object severity, code, path)) {
    $issueLines.Add("- **$($issue.severity)** ``$($issue.code)`` in ``$($issue.path)``: $($issue.detail)")
}
if ($clientCoverage.status -ne 'healthy') {
    $issueLines.Add("- **warning** ``client_intelligence_reconciliation`` in ``12_Brain/09_Ops/Client Intelligence Coverage.md``: $($clientCoverage.missing) missing, $($clientCoverage.duplicates) duplicate, $($clientCoverage.extra) extra, and $($clientCoverage.unmappedActiveOverviews) unmapped active overview routes.")
}
if ($issueLines.Count -eq 0) {
    $issueLines.Add('- None.')
}

$nowLocal = Get-Date
$lines = @(
    '---'
    'note_type: health'
    "status: $severityLabel"
    "updated: $($nowLocal.ToString('yyyy-MM-dd'))"
    "checked_at: $($nowLocal.ToString('s'))"
    'tags:'
    '  - brain'
    '  - health'
    '  - generated'
    '---'
    ''
    '# Brain Health'
    ''
    "Generated by `System/scripts/Update-SecondBrainHealth.ps1`."
    ''
    '## Snapshot'
    ''
    "| Metric | Count |"
    "|---|---:|"
    "| Markdown notes | $($markdownFiles.Count) |"
    "| Brain notes | $($brainFiles.Count) |"
    "| Captures | $($captureFiles.Count) |"
    "| Active project files | $($projectFiles.Count) |"
    "| Decision files | $($decisionFiles.Count) |"
    "| Memory files | $($memoryFiles.Count) |"
    "| Operational knowledge domains | $($knowledgeCoverage.operationalDomains) / $($knowledgeCoverage.domains) |"
    "| Canonical active relationship routes | $($clientCoverage.activeRegistryClients) |"
    "| Client intelligence overlays | $($clientCoverage.overlays) |"
    "| Missing client overlays | $($clientCoverage.missing) |"
    "| Unmapped active vault overviews | $($clientCoverage.unmappedActiveOverviews) |"
    "| Base files | $($health.summary.baseFiles) |"
    "| Graph nodes | $($health.summary.graphNodes) |"
    "| Graph edges | $($health.summary.graphEdges) |"
    "| Connected components | $($health.summary.graphComponents) |"
    "| Largest component coverage | $($health.summary.graphLargestComponentCoverage)% |"
    "| Orphan notes | $($health.summary.graphOrphans) |"
    "| Open checkbox tasks | $openTasks |"
    "| Errors | $($health.summary.errorCount) |"
    "| Warnings | $($health.summary.warningCount) |"
    ''
    '## Findings'
    ''
)
$lines += $issueLines
$lines += @(
    ''
    '## Operating interpretation'
    ''
    'A passing structural check means the brain layer is wired correctly. It does'
    'not prove that client facts, research, or metrics are current; those require'
    'their own live source verification.'
)

$absoluteOutput = Join-Path $resolvedVault ($OutputPath.Replace('/', '\'))
$outputDirectory = Split-Path $absoluteOutput -Parent
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

[IO.File]::WriteAllText($absoluteOutput, (($lines -join [Environment]::NewLine) + [Environment]::NewLine), (New-Object Text.UTF8Encoding($false)))

[pscustomobject]@{
    outputPath = $absoluteOutput
    status = $severityLabel
    testExitCode = $testExitCode
    errors = [int]$health.summary.errorCount
    warnings = [int]$health.summary.warningCount
    knowledgeCoveragePercent = [double]$knowledgeCoverage.coveragePercent
    clientCoverageStatus = [string]$clientCoverage.status
    clientOverlays = [int]$clientCoverage.overlays
    clientOverlaysMissing = [int]$clientCoverage.missing
    unmappedActiveOverviews = [int]$clientCoverage.unmappedActiveOverviews
}
