'use strict';

/** Aug 17 radar demo pack. Facts only. Casselle is structurally blocked. */

const STYLE =
  'Editorial two-colour engraved illustration, copperplate engraving mixed with technical woodcut, printed on warm cream paper. Fine hatch, stipple, and cross-contour lines. Wide landscape 16:9. Faint CAD corner registration brackets in the margins. Strictly two ink colors only. Absolutely no text, no letters, no numbers, no logo, no watermark, no human faces, no people, no photographic realism, no glossy 3D render, no identifiable real building facade or storefront, no real business premises.';

function prompt(brand, accent, subject) {
  return `${STYLE} Ink colors only: ${brand} and ${accent}. Subject: ${subject}`;
}

module.exports = [
  {
    slug: 'east-penn-roofing',
    name: 'East Penn Roofing',
    website: 'https://www.eastpennroofing.com/emmaus',
    vertical: 'roofer',
    schema: 'RoofingContractor',
    city: 'Emmaus',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18049',
    brand: '#1a1a1a',
    accent: '#df3131',
    buzz: 'slate roofs',
    ticker: ['Emmaus', 'Easton', 'Quakertown', 'Fleetwood', 'Bethlehem', 'Macungie', 'Pennsburg', 'Allentown'],
    h1: 'A roof has one job',
    lede: 'East Penn Roofing is based in Emmaus. The published work is residential and commercial roofing across the Lehigh Valley: repair, replacement, inspection, storm restoration, and seamless gutters.',
    sections: [
      { title: 'Slate, and who can do it', body: 'Their own service list names slate roofing and slate roof repair alongside asphalt, metal, and shingles. That is the uncommon line. Most valley shops stop at asphalt. If a page is going to earn a call, it should say the hard material first and keep the rest as a list, not a speech.' },
      { title: 'Flat roofs, plainly', body: 'Commercial and flat roofing are on the same menu as the house work. Emmaus is listed as home base. Easton, Quakertown, Fleetwood, Bethlehem, Macungie, Pennsburg, and Allentown are on the published coverage list. No hours were copied onto this demo because they were not captured as a stable string on the pages we read.' },
      { title: 'What this page will not invent', body: 'No crew size, no founding year, no license number, no “family owned since.” The live Emmaus page talks about replacements, repairs, and gutters built to last. That is enough. The pictures here are engraved stand-ins, not photographs of their jobs.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of slate courses and copper flashing, not a real job site', subject: 'Close study of hand-split slate courses, copper flashing folds, and a ridge cap, viewed as a measured elevation drawing of materials only' },
      { alt: 'Engraved two-colour study of a flat commercial roof assembly', subject: 'A flat commercial roof assembly in section: tapered insulation, membrane seams, and a box scupper, drawn as a shop elevation with hatch for each layer' },
      { alt: 'Engraved two-colour Lehigh Valley ridge map without real addresses', subject: 'An abstract Lehigh Valley ridge and river map as engraved contour lines and a small grid of unnamed blocks, no street names, no real roofs' },
    ],
  },
  {
    slug: 'pennmark-financial',
    name: 'Pennmark Financial',
    website: 'https://pennmarkfinancial.com/',
    vertical: 'payment-service',
    schema: 'ProfessionalService',
    city: 'Exton',
    area: 'Chester County',
    region: 'PA',
    postcode: '19341',
    brand: '#223645',
    accent: '#065f46',
    buzz: 'get paid',
    h1: 'POS. Then the swipe.',
    lede: 'Pennmark Financial is not a wealth manager. Their own homepage sells Quantic POS as a service and card processing for small and mid-size businesses, with a low or zero upfront hardware pitch.',
    sections: [
      { title: 'What they actually sell', body: 'The live title is “Trusted Partner of Quantic POS.” The offer is cloud POS plus payments: hardware, software, and processing in one program. Credit-card processing is advertised at rates as low as 0% per swipe or dip under their published promotion. This page does not repeat that rate as a promise. It only records that the claim is on their site today.' },
      { title: 'Who it is for', body: 'They speak to restaurants and other counter businesses that need a terminal and a processor, not a portfolio. Exton is the radar city. No branch hours were published in the text we captured, so none appear here.' },
      { title: 'Schema, corrected', body: 'Radar first filed them as a financial advisor. That is the wrong trade. The demo uses a professional-service schema and the line PAY / get paid. If this pack is ever mailed, the pitch is a payments site, not a planning site.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a counter terminal and receipt rail, not a real store', subject: 'A compact point-of-sale terminal, card rail, and paper-tape roll on a blank counter, drawn as a parts plate, no brand marks' },
      { alt: 'Engraved two-colour study of payment rails as a wiring diagram', subject: 'An abstract wiring diagram of a card swipe becoming a settlement batch: chevrons, a small ledger block, and a cloud node, no logos' },
      { alt: 'Engraved two-colour Exton-area grid without real premises', subject: 'A Chester County road-and-ridge engraving with an unnamed crossroads grid, no storefronts, no office parks' },
    ],
  },
  {
    slug: 'peter-zimmerman-architects',
    name: 'Peter Zimmerman Architects',
    website: 'https://www.pzarchitects.com/',
    vertical: 'architect',
    schema: 'Architect',
    city: 'Berwyn',
    area: 'Chester County',
    region: 'PA',
    postcode: '19312',
    brand: '#2b2620',
    accent: '#b08a4a',
    buzz: 'timeless living',
    flag: 'Live site returned 403 during the Aug 17 grade. Do not treat that score as a design verdict.',
    h1: 'Houses drawn to last',
    lede: 'Peter Zimmerman Architects is filed in Berwyn. The live site blocked the Aug 17 crawl (403), so this demo does not quote rooms, awards, or a project list we could not read.',
    sections: [
      { title: 'What we can say', body: 'The registry has them as an architect in Chester County. That is the whole verified sentence. “Timeless living” is the two-word mark for this card because the earlier harvest tied it to their own residential language. If that heading is gone when you reopen the site, drop the mark.' },
      { title: 'What we will not say', body: 'No staff names, no “2018,” no invented slate-and-stucco portfolio. The earlier copy pass refused facts that lived only in a research report. Same rule here.' },
      { title: 'Why the page still exists', body: 'A 403 is a rebuild case only after a human confirms the URL is still theirs. The pictures are engraved house-and-landscape studies, not their jobs.' },
    ],
    slots: [
      { alt: 'Engraved two-colour elevation of a stone house massing, not a real commission', subject: 'A measured front elevation of a stone country house: hipped roof, chimney masses, and mullioned voids, no address, no cars' },
      { alt: 'Engraved two-colour study of a stair and landing as a section', subject: 'An architectural section through a stair hall: treads, a newel, and a landing window as linework only' },
      { alt: 'Engraved two-colour Chester County ridge without a real estate', subject: 'Chester County ridgelines and a unnamed tree line, engraved, with a tiny unlabelled floor-plan ghost in the corner' },
    ],
  },
  {
    slug: 'frees-insurance',
    name: 'Frees Insurance',
    website: 'https://freesinsurance.com/',
    vertical: 'insurance',
    schema: 'InsuranceAgency',
    city: 'Phoenixville',
    area: 'Chester County',
    region: 'PA',
    postcode: '19460',
    phone: '610-933-4950',
    email: 'info@freesinsurance.com',
    street: '120 Gay St',
    brand: '#1c2a44',
    accent: '#c4a35a',
    buzz: 'since 1933',
    flag: 'Their own contact page still lists 120 Gay St. Recheck the street before any mail drop. The Aug 17 grade hit a 403 on a different fetch path.',
    ticker: ['Phoenixville'],
    h1: 'Insurance is what you buy',
    lede: 'Frees Insurance is an independent agency in Phoenixville. Their site says they have specialized in personal insurance since 1933. Published lines: auto, home, renters, umbrella, life, and business.',
    sections: [
      { title: 'The line they already wrote', body: '“Insurance is not what you pay; it’s what you buy.” That is theirs. This page keeps it and does not add a slogan on top. Phone (610) 933-4950 and info@freesinsurance.com are on the contact page we read on 17 August 2026.' },
      { title: 'Address, as published today', body: '120 Gay St, PO Box 289, Phoenixville, PA 19460 is what their contact page prints. Some directories still repeat that block. If a move is coming, it is not on the page we fetched. Recheck the same day you print a card.' },
      { title: 'What the pictures are', body: 'Engraved Phoenixville-canal and policy-jacket studies. Not their office. Not their staff.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a policy jacket and fountain pen, no people', subject: 'An open insurance jacket, a blotter, and a fountain pen on a desk, engraved, no names on the papers' },
      { alt: 'Engraved two-colour study of a house and car as coverage icons, not real property', subject: 'A small house mass and a simple automobile in elevation, drawn as coverage glyphs on a ledger grid, no plates, no address' },
      { alt: 'Engraved two-colour Phoenixville canal without real storefronts', subject: 'A Schuylkill canal lock and stone wall in Phoenixville as an engraved landscape, no readable signs, no office facade' },
    ],
  },
  {
    slug: 'bm-construction-hvac',
    name: 'B & M Construction & HVAC',
    website: 'https://bmconstructionhvac.com/',
    vertical: 'hvac',
    schema: 'HVACBusiness',
    city: 'Whitehall',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18052',
    brand: '#1e2430',
    accent: '#d97706',
    buzz: 'heat cool',
    flag: 'Domain did not resolve on Aug 17. No license claim on this page. PA HIC PA141518 was reported expired March 2026 by one pass and “active” by another — this demo states neither.',
    h1: 'Construction and air',
    lede: 'B & M Construction & HVAC is filed in Whitehall. The published URL did not resolve on 17 August 2026, so this demo does not invent a service menu, hours, or a license line.',
    sections: [
      { title: 'What the name already says', body: 'Construction and HVAC. That is the whole offer until a live page or a phone book listing is re-read. Whitehall, Lehigh County, PA 18052 is the radar row.' },
      { title: 'License, left blank', body: 'A PA home-improvement registration was discussed in the harvest notes. One reader called it active, one called it lapsed past March 2026. Today is 17 August 2026. This page makes no licensing claim either way.' },
      { title: 'Pictures', body: 'Engraved duct and framing studies. Not their trucks. Not their jobs.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of ductwork and a furnace cabinet, no brand', subject: 'A residential furnace cabinet, filter slot, and rectangular duct takeoffs as a parts elevation' },
      { alt: 'Engraved two-colour study of framing and a window rough-in', subject: 'A wall section: studs, sheathing, and a window rough opening with flashing tape drawn as hatch' },
      { alt: 'Engraved two-colour Whitehall-area grid without real houses', subject: 'An abstract Lehigh County block grid and a ridge line, no street names, no job sites' },
    ],
  },
  {
    slug: 'four-four-architecture',
    name: '4/4 Architecture',
    website: 'http://www.bsaia.net/',
    vertical: 'architect',
    schema: 'Architect',
    city: 'Bethlehem',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18018',
    brand: '#1f2933',
    accent: '#4b7c8a',
    buzz: 'plan check',
    flag: 'Wrong domain join: bsaia.net did not resolve. Do not pitch this URL as theirs until a human confirms the live site.',
    h1: 'A name, not a site',
    lede: 'Radar filed 4/4 Architecture in Bethlehem against bsaia.net. That host did not resolve on 17 August 2026. This page is a holding demo, not a portrait of a practice we could read.',
    sections: [
      { title: 'Do not mail this URL', body: 'ENOTFOUND is not a design problem. It is a data problem. Confirm the current domain before anyone spends a stamp.' },
      { title: 'What we still drew', body: 'Generic Bethlehem-steel and drafting studies so the slot is not a hatched void. They are not this firm’s buildings.' },
      { title: 'Next check', body: 'Search the Pennsylvania architect roster for the legal name before the next harvest. Until then, the card stays flagged.' },
    ],
    slots: [
      { alt: 'Engraved two-colour drafting table with triangles and a scale, no people', subject: 'A drafting table, two triangles, and an architect’s scale as a still-life plate' },
      { alt: 'Engraved two-colour steel-mill silhouette without a real mill', subject: 'An abstract Bethlehem blast-furnace silhouette as a distant engraved mass, no corporate marks' },
      { alt: 'Engraved two-colour city grid without real addresses', subject: 'A Bethlehem-like street grid and river bend, unnamed, engraved' },
    ],
  },
  {
    slug: 'pegasus-technologies',
    name: 'Pegasus Technologies',
    website: 'https://pegasustechnologies.com/',
    vertical: 'it',
    schema: 'ProfessionalService',
    city: 'Kennett Township',
    area: 'Chester County',
    region: 'PA',
    postcode: '19348',
    brand: '#0b1f33',
    accent: '#2aa4c8',
    buzz: 'right fit',
    flag: 'One Aug 17 fetch path returned 403. A later fetch of the homepage loaded. Prefer the live menu over the grade.',
    h1: 'IT that stays on',
    lede: 'Pegasus Technologies publishes managed IT, 24/7 support, backup and disaster recovery, cloud and Microsoft 365 migration, cabling, wireless, VoIP, and a SNAP-Defense security stack (MDR, SOC, EDR).',
    sections: [
      { title: 'The menu, not the pitch', body: 'Their nav is the brief: Match-IT, managed services for IT departments, Mac support, automation and AI, private and hybrid cloud, virtualization, redundant internet. This page lists those nouns. It does not invent a headcount or a founding year.' },
      { title: 'Where', body: 'Radar city is Kennett Township. The site also talks about locations they serve. We did not copy a town list we could not finish reading, so the ticker stays off.' },
      { title: 'Pictures', body: 'Engraved rack and packet studies. Not their NOC. Not their staff.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a server rack and patch field, no logos', subject: 'A half-height server rack, patch panel, and neatly dressed copper bundles as a shop elevation' },
      { alt: 'Engraved two-colour study of a backup vault as a diagram', subject: 'An abstract backup diagram: a local disk array, an offsite vault block, and a restore arrow, no vendor marks' },
      { alt: 'Engraved two-colour Kennett-area orchard grid without real offices', subject: 'Chester County orchard rows and a small unnamed hamlet grid, engraved, no office park' },
    ],
  },
  {
    slug: 'kvcw-oxford',
    name: 'KVCW Insurance — Oxford',
    website: 'https://kviscoe.com/',
    vertical: 'insurance',
    schema: 'InsuranceAgency',
    city: 'Oxford',
    area: 'Chester County',
    region: 'PA',
    postcode: '19363',
    phone: '610-459-4444',
    brand: '#1a2744',
    accent: '#8b1e2d',
    buzz: 'three offices',
    flag: 'Radar still says Coe Insurance. The live brand is Kimberley Vassal Coe & Weimer. Brian Coe is listed in harvest notes as CFO — not repeated here as a bio we did not re-read.',
    ticker: ['Oxford', 'Chadds Ford', 'Perkasie'],
    h1: 'Coe is a door, not the name',
    lede: 'kviscoe.com and kvcwins.com both resolve to Kimberley Vassal Coe & Weimer Insurance Services. Published offices: Chadds Ford, Oxford, and Perkasie. Phone 610-459-4444. Hours on the site we read: Mon–Thu 9–5, Fri 9–1, weekend closed.',
    sections: [
      { title: 'What they sell', body: 'Auto, homeowners, business, personal, life, health quotes, and Medicare supplemental plans. The site also has a policy service center: claims, auto ID cards, certificates, billing, and change requests.' },
      { title: 'Why the radar name is wrong', body: 'The row is still “Coe Insurance.” The page title is KVCW. If this pack is used for outreach, use the live name. The old Coe mark is a redirect, not a second agency.' },
      { title: 'Pictures', body: 'Engraved Oxford-brick and policy studies. Not their lobby.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a policy binder and keys, no people', subject: 'A leather policy binder, house keys, and a car key on a blotter, engraved, no names' },
      { alt: 'Engraved two-colour study of three office-town glyphs', subject: 'Three small unnamed town glyphs on a single engraved map plate, standing for a three-office agency, no labels' },
      { alt: 'Engraved two-colour Oxford-area brick street without real storefronts', subject: 'A Chester County brick street and shade trees as an engraved view, signs left blank' },
    ],
  },
  {
    slug: 'jobologi',
    name: 'Jobologi',
    website: 'https://www.internu.com/',
    vertical: 'employment-agency',
    schema: 'EmploymentAgency',
    city: '',
    area: 'Chester County',
    region: 'PA',
    brand: '#12263a',
    accent: '#e07a2f',
    buzz: 'job done',
    flag: 'internU has evolved. The live brand is Jobologi. internu.com is a stub that says so. Do not mail the internU name as current.',
    h1: 'internU grew up',
    lede: 'internu.com now says “internU has Evolved.” The live company is Jobologi: technology managed solutions, healthcare managed solutions, talent management, and data analytics.',
    sections: [
      { title: 'What Jobologi publishes', body: '“Getting the job done.” Decades in technology, healthcare, and talent management. Careers are split entry-level and professional. That is the public menu. This page does not invent a 1991 founding date or a 2024 close date as facts we did not re-read on their history page.' },
      { title: 'Radar still says internU', body: 'The Aug 17 row is an employment agency in Chester County graded off a three-word stub. The rebuild case is real. The name on the envelope should be Jobologi.' },
      { title: 'Pictures', body: 'Engraved badge and circuit studies. Not their office. Not their staff.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a badge reel and a laptop hinge, no faces', subject: 'A blank badge reel, a laptop hinge, and a cable coil as a still-life plate' },
      { alt: 'Engraved two-colour study of healthcare and circuit glyphs', subject: 'A caduceus-like abstract staff (not a trademark) beside a small circuit lattice, engraved, no text' },
      { alt: 'Engraved two-colour Chester County campus grid without real buildings', subject: 'An unnamed campus quad and tree grid, engraved, no internU or Jobologi marks' },
    ],
  },
  {
    slug: 'andesa-services',
    name: 'Andesa Services',
    website: 'https://andesaservices.com/',
    vertical: 'consulting',
    schema: 'ProfessionalService',
    city: 'Allentown',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18106',
    brand: '#0f2c4c',
    accent: '#3d8b7a',
    buzz: 'policy ops',
    flag: 'Homepage fetch hit Cloudflare from this environment. Copy stays thin until a signed-in read.',
    h1: 'A slow page is still a page',
    lede: 'Andesa Services is filed in Allentown as consulting. The Aug 17 grade called the live site dated: a 7.6s full load and a hard-coded 2560px width. This demo does not invent their product list.',
    sections: [
      { title: 'What the grade actually measured', body: 'HTTPS, a real host, and a layout that still thinks in 2560px. That is a rebuild conversation about craft, not about a missing business.' },
      { title: 'What we did not read', body: 'Cloudflare blocked a later fetch from this agent. No invented platforms, no invented carrier names, no invented headcount.' },
      { title: 'Pictures', body: 'Engraved ledger and Allentown-ridge studies. Not their floor.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a policy ledger and ruler, no names', subject: 'An open ledger, a brass ruler, and a stack of unbound signatures as a still-life' },
      { alt: 'Engraved two-colour study of a process swimlane without logos', subject: 'A three-lane process plate: intake, exception, release, drawn as engraved boxes and arrows, no vendor names' },
      { alt: 'Engraved two-colour Allentown ridge without real offices', subject: 'Lehigh Valley ridges and an unnamed river bend, engraved' },
    ],
  },
  {
    slug: 'builders-management-plus',
    name: 'Builders & Management Plus',
    website: 'https://buildersmanagementplus.com/',
    vertical: 'roofer',
    schema: 'RoofingContractor',
    city: 'Allentown',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18109',
    phone: '610-440-4082',
    brand: '#2e2d33',
    accent: '#fc6b0d',
    buzz: 'exteriors first',
    flag: 'Live site graded 72/100 strong. This is a craft demo, not a rebuild pitch.',
    h1: 'The outside of the house',
    lede: 'Builders & Management Plus publishes residential and commercial roofing, siding, storm damage, gutters, window replacement, and water-damage restoration. Phone on the site we read: 610-440-4082.',
    sections: [
      { title: 'Their own headline', body: '“Changing Roofs, Changing Lives” is on the live page. This demo does not compete with it. The useful sentence under it is that they sell the whole exterior, not only shingles.' },
      { title: 'Why radar still filed a row', body: 'A 72 is “do not pitch a rebuild.” If this card is shown, it is as a taste sample, not a replacement offer.' },
      { title: 'Pictures', body: 'Engraved shingle and gutter studies. Not their completed jobs.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of architectural shingles and a drip edge', subject: 'Architectural shingles, a metal drip edge, and a starter course as a materials elevation' },
      { alt: 'Engraved two-colour study of a gutter and downspout mitre', subject: 'A seamless gutter run, hidden hanger, and downspout mitre as a shop drawing' },
      { alt: 'Engraved two-colour Allentown neighborhood grid without real houses', subject: 'An unnamed Allentown block grid and tree line, engraved, no addresses' },
    ],
  },
  {
    slug: 'crosson-richetti',
    name: 'Crosson & Richetti',
    website: 'https://crossonrichetti.com/',
    vertical: 'lawyer',
    schema: 'LegalService',
    city: 'Allentown',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18101',
    brand: '#1b2030',
    accent: '#7a1f2b',
    buzz: 'case file',
    flag: 'Homepage fetch hit Cloudflare from this environment. Live grade was 73/100 strong — do not pitch a rebuild from this demo.',
    h1: 'A firm with a working site',
    lede: 'Crosson & Richetti LLC is a law firm in Allentown. The Aug 17 grade called the live site strong. This demo does not invent practice areas we could not re-read behind Cloudflare.',
    sections: [
      { title: 'Why this card is quiet', body: 'A 73 with a fast first response is not a rebuild lead. The page exists so the batch has a slot, not so anyone mails a “your site is broken” letter.' },
      { title: 'Pictures', body: 'Engraved Allentown-courthouse-massing studies. Not their office. Not their clients.' },
      { title: 'Next read', body: 'Open the live site from a normal browser before writing a single practice-area sentence.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a case file and seal stamp, no names', subject: 'A tied case file, a blank wax seal, and a steel rule on a desk' },
      { alt: 'Engraved two-colour study of a courthouse massing, not a real court', subject: 'A generic classical courthouse massing as an elevation, no flags, no inscriptions' },
      { alt: 'Engraved two-colour Allentown center grid without real firms', subject: 'An unnamed downtown grid and river, engraved' },
    ],
  },
  {
    slug: 'digital-marketing-service-pro',
    name: 'Digital Marketing Service Pro',
    website: 'https://digitalmarketingservpro.com/Service-Area/digital-marketing-west-chester',
    vertical: 'advertising-agency',
    schema: 'ProfessionalService',
    city: 'West Chester',
    area: 'Chester County',
    region: 'PA',
    postcode: '19380',
    brand: '#111827',
    accent: '#2563eb',
    buzz: 'service area',
    flag: 'Harvest notes place the operating firm in Fort Lauderdale. The West Chester URL is a service-area page, not proof of a Chester County shop.',
    h1: 'A URL is not a town',
    lede: 'Radar filed a West Chester service-area URL for Digital Marketing Service Pro. The grade called that page strong. The operating geography in the harvest notes is Fort Lauderdale, not Pennsylvania.',
    sections: [
      { title: 'Do not mail this as a local shop', body: 'A /Service-Area/digital-marketing-west-chester path is how national SEO shops plant towns. Confirm a real desk in Chester County before anyone treats this as a neighbor.' },
      { title: 'What we drew', body: 'Engraved map-pin and billboard studies. Not their office. Not a West Chester storefront they may not have.' },
      { title: 'Batch rule', body: 'Keep the defect flag on the hub. This is a data-quality card.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a map pin field, no city names', subject: 'A field of blank map pins on an unlabelled county plate, engraved' },
      { alt: 'Engraved two-colour study of a browser frame without readable UI chrome text', subject: 'An abstract browser window as a rectangle with a blank tab bar and a wireframe hero, no letters' },
      { alt: 'Engraved two-colour West Chester green without real shops', subject: 'A courthouse-green tree canopy and brick edge, signs left blank' },
    ],
  },
  {
    slug: 'gc-electric',
    name: 'GC Electric',
    website: 'https://gcelectric.com/',
    vertical: 'electrician',
    schema: 'Electrician',
    city: 'Allentown',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18103',
    phone: '610-797-3500',
    email: 'info@gcelectric.com',
    brand: '#1a1a1a',
    accent: '#c0392b',
    buzz: 'keep running',
    ticker: ['Lehigh Valley'],
    flag: 'Live site graded 72/100 strong. Demo only.',
    h1: 'Power, then backup',
    lede: 'GC Electric publishes residential, commercial, and industrial electrical work in the Lehigh Valley, plus renewable energy and ESS, generators, and energy management. The site we read lists 24/7 emergency service at 610-797-3500.',
    sections: [
      { title: 'The menu', body: 'Home electrical, commercial/industrial keep-the-plant-up work, wind and storage language, standby generators, and energy management. That is their nav, not our invention.' },
      { title: 'Why it is in the pack', body: 'A 72 is not a rebuild lead. The card is here because it was in today’s 23. If you show it, show it as a craft sample.' },
      { title: 'Pictures', body: 'Engraved panel and generator studies. Not their vans. Not their jobs.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a load center and homeruns, no brand', subject: 'An open load center, neatly dressed homeruns, and a grounding bar as a shop elevation' },
      { alt: 'Engraved two-colour study of a standby generator and transfer switch', subject: 'A standby generator pad and a transfer-switch cabinet in elevation, no manufacturer marks' },
      { alt: 'Engraved two-colour Lehigh Valley night grid without real plants', subject: 'A valley night grid of unnamed blocks and a river, engraved, no plant logos' },
    ],
  },
  {
    slug: 'heather-j-mattes',
    name: 'Law Offices of Heather J. Mattes',
    website: 'https://www.hjmattes.com/',
    vertical: 'lawyer',
    schema: 'LegalService',
    city: '',
    area: 'Chester County',
    region: 'PA',
    brand: '#1c1917',
    accent: '#9a3412',
    buzz: 'case work',
    flag: 'Live site graded 79/100 strong. Cloudflare blocked a later fetch. Do not pitch a rebuild.',
    h1: 'A strong site already',
    lede: 'Heather J. Mattes is filed as a Chester County law practice. The Aug 17 grade was 79/100 with two schema blocks. This demo does not invent a docket we could not re-read.',
    sections: [
      { title: 'Offer, if any', body: 'Radar’s own next action on a 79 is ads and SEO, not a rebuild. If this card is in the hub, it is for completeness.' },
      { title: 'Pictures', body: 'Engraved brief and Chester County studies. Not her office. Not her clients.' },
      { title: 'Next read', body: 'Open hjmattes.com from a normal browser before writing practice areas.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a legal brief and ribbon, no names', subject: 'A folded brief, a cloth ribbon, and a steel paperweight on oak, engraved' },
      { alt: 'Engraved two-colour study of a gavel rest, no people', subject: 'A gavel rest and a blank minute book, engraved still-life' },
      { alt: 'Engraved two-colour Chester County ridge without a real office', subject: 'Chester County stone walls and a ridge, engraved, no signage' },
    ],
  },
  {
    slug: 'main-line-benefits',
    name: 'Main Line Benefits',
    website: 'https://www.mlbenefitsco.com/',
    vertical: 'insurance',
    schema: 'InsuranceAgency',
    city: '',
    area: 'Chester County',
    region: 'PA',
    brand: '#1e3a4c',
    accent: '#2ea3f2',
    buzz: 'plan help',
    h1: 'Coverage, then the form',
    lede: 'Main Line Benefits publishes help for individuals, families, the self-employed, small businesses, and Medicare beneficiaries. They say there is no extra fee for their service. They also recruit agents.',
    sections: [
      { title: 'Medicare is on the homepage', body: 'If you are Medicare-eligible or about to be, they say they will search plans against needs and budget. That is their sentence. This page does not add a carrier list we did not capture.' },
      { title: 'What the grade saw', body: '61/100 dated: no meta description, no schema. A real site with a craft problem, not a missing business.' },
      { title: 'Pictures', body: 'Engraved card and mailbox studies. Not their staff.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a benefits card and envelope, no names', subject: 'A blank benefits card, a window envelope, and a fountain pen, engraved' },
      { alt: 'Engraved two-colour study of a Medicare-like booklet without marks', subject: 'A small stapled booklet and a pair of reading glasses, engraved, no program logos' },
      { alt: 'Engraved two-colour Main Line tree street without real offices', subject: 'A tree-lined Main Line street as an engraved view, signs blank' },
    ],
  },
  {
    slug: 'orpi-claire-canac',
    name: 'Orpi Claire Canac',
    website: 'https://www.orpi.com/clairecanac',
    vertical: 'estate-agent',
    schema: 'RealEstateAgent',
    city: 'Castres',
    area: 'Tarn',
    region: 'France',
    brand: '#c8102e',
    accent: '#1d1d1b',
    buzz: 'wrong market',
    flag: 'Castres, France. Not Lehigh County. Radar geo-join is wrong. Do not mail.',
    h1: 'This is not Pennsylvania',
    lede: 'orpi.com/clairecanac is a French Orpi agency page. Radar dropped it into Lehigh County. That is a bad join. The demo exists so the defect stays visible.',
    sections: [
      { title: 'Do not pitch', body: 'No PA rebuild letter. No English “we redesigned your site” email. The row is a geocoder miss.' },
      { title: 'What we drew', body: 'Engraved Tarn-tile and map studies. Not a Castres storefront photograph.' },
      { title: 'Fix the registry', body: 'Next radar pass should drop orpi.com from PA discovery or pin it to FR.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a French tile roof and chimney, not a real listing', subject: 'A terracotta tile roof and chimney pot as a materials elevation, no address' },
      { alt: 'Engraved two-colour study of a blank agency window, no letters', subject: 'A blank shop window and a hanging lantern, engraved, no Orpi wordmark' },
      { alt: 'Engraved two-colour Tarn hill town without real streets named', subject: 'A hill town of unnamed tile roofs, engraved, no street names' },
    ],
  },
  {
    slug: 'pa-title-tag-emmaus',
    name: 'PA Title & Tag of Emmaus',
    website: 'https://patitleandtag.com/',
    vertical: 'notary',
    schema: 'ProfessionalService',
    city: 'Emmaus',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18049',
    brand: '#1c2d4a',
    accent: '#b91c1c',
    buzz: 'title work',
    ticker: ['Emmaus', 'Red Hill', 'Boyertown', 'Harleysville'],
    h1: 'Title, tag, notary',
    lede: 'PA Title & Tag Service Inc publishes four offices: Upper Perk Valley (Red Hill), Boyertown, Emmaus, and Harleysville. The work is vehicle title and registration, license paperwork, driver services, and notary.',
    sections: [
      { title: 'Four desks, one standard', body: 'That is their homepage sentence. This demo does not invent hours per office. The live location cards hold those. The Aug 17 grade dinged a missing homepage phone and missing schema — craft notes, not a missing company.' },
      { title: 'Emmaus is one door', body: 'Radar filed the Emmaus row. The brand is larger than one town. If you show this card, keep the other three names on the ticker.' },
      { title: 'Pictures', body: 'Engraved plate and stamp studies. Not their counters. Not their staff.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a title jacket and notary embosser, no names', subject: 'A title jacket, a handheld notary embosser, and a ribbon, engraved, no seals with readable text' },
      { alt: 'Engraved two-colour study of a license plate blank, no numbers', subject: 'A blank Pennsylvania-shaped plate with no numbers or motto, engraved as a metal rectangle' },
      { alt: 'Engraved two-colour four-town grid without real offices', subject: 'Four unnamed town glyphs on one engraved county plate' },
    ],
  },
  {
    slug: 'prologistix-allentown',
    name: 'ProLogistix Allentown',
    website: 'https://www.prologistix.com/locations/allentown-pennsylvania/',
    vertical: 'employment-agency',
    schema: 'EmploymentAgency',
    city: 'Allentown',
    area: 'Lehigh County',
    region: 'PA',
    postcode: '18109',
    brand: '#0f2744',
    accent: '#f59e0b',
    buzz: 'warehouse work',
    flag: 'National chain branch. Harvest notes said branch 81010 and an Employbridge move. Hours were not published in the text we could read — none invented. Cloudflare blocked a later fetch.',
    h1: 'A branch, not a shop',
    lede: 'ProLogistix is a national staffing brand. The radar row is the Allentown location page. The Aug 17 grade called that page dated: overflow on phone and tablet, no meta description.',
    sections: [
      { title: 'What this page will not do', body: 'No invented lobby hours. No invented pay rates. No invented “family owned.” If Employbridge is the parent move, say it only after a human re-reads a primary page.' },
      { title: 'Why it is still in the pack', body: 'A national branch can still have a bad local URL. That is a different letter than a rebuild for a one-location shop.' },
      { title: 'Pictures', body: 'Engraved dock and pallet studies. Not their Allentown suite.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a loading dock and pallet jack, no people', subject: 'A loading-dock plate, a pallet jack, and stacked pallets as a shop elevation' },
      { alt: 'Engraved two-colour study of a time-clock and locker row, no faces', subject: 'A blank time clock and a row of closed lockers, engraved' },
      { alt: 'Engraved two-colour Allentown industrial grid without a real branch', subject: 'An industrial park grid and rail spur, engraved, no tenant names' },
    ],
  },
  {
    slug: 'samuel-stretton',
    name: 'Samuel C. Stretton',
    website: 'http://www.samstrettonlaw.com/',
    vertical: 'lawyer',
    schema: 'LegalService',
    city: '',
    area: 'Chester County',
    region: 'PA',
    brand: '#1c1917',
    accent: '#44403c',
    buzz: 'dead domain',
    flag: 'Harvest notes: domain repurposed by a California firm. Do not treat samstrettonlaw.com as the Chester County lawyer. Do not mail.',
    h1: 'The name is not the host',
    lede: 'Radar still files Samuel C. Stretton against samstrettonlaw.com. The Aug 17 grade called that host strong. The harvest notes say the name was reused. This demo is a warning card.',
    sections: [
      { title: 'Do not pitch the URL', body: 'A rebuilt page on a hijacked or resold domain is how you advertise the wrong person. Confirm the lawyer’s current host before any outreach.' },
      { title: 'What we drew', body: 'Engraved empty-counsel-table studies. Not a California SEO shop. Not a West Chester office we could not confirm.' },
      { title: 'Registry', body: 'Mark the domain contested on the next radar pass.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of an empty counsel table', subject: 'An empty counsel table, two closed books, and a water carafe, engraved' },
      { alt: 'Engraved two-colour study of a broken domain as a snapped seal', subject: 'A wax seal cracked in half on a blotter, engraved, no letters' },
      { alt: 'Engraved two-colour unnamed county ridge', subject: 'An unnamed Pennsylvania ridge and stone wall, engraved' },
    ],
  },
  {
    slug: 'west-chester-outdoor',
    name: 'West Chester Outdoor Advertising',
    website: 'https://wcadvertising.com/',
    vertical: 'advertising-agency',
    schema: 'ProfessionalService',
    city: 'West Chester',
    area: 'Chester County',
    region: 'PA',
    postcode: '19380',
    phone: '484-202-0715',
    email: 'info@wcadvertising.com',
    brand: '#0f172a',
    accent: '#2ea3f2',
    buzz: 'digital boards',
    h1: 'A board, not a feed',
    lede: 'West Chester Outdoor Advertising sells digital billboard inventory. The site we read lists 484-202-0715 and info@wcadvertising.com, and claims about 16,846 visual impressions per day per side on their digital board.',
    sections: [
      { title: 'Their number, their claim', body: 'They write “over 3.7 million cars per year” and “less than one” as a cost tease. This page records that the claim is on their homepage. It does not certify traffic counts.' },
      { title: 'The grade', body: '61/100 dated: slow full load, no meta description. A real local board company with a heavy page.' },
      { title: 'Pictures', body: 'Engraved billboard and road studies. Not their actual face. No readable ads.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of a digital billboard structure, blank face', subject: 'A monopole digital billboard with a blank face and catwalk, engraved, no copy on the board' },
      { alt: 'Engraved two-colour study of a night arterial without real brands', subject: 'A night arterial and a blank board in the distance, engraved, no store logos' },
      { alt: 'Engraved two-colour West Chester green without real boards sited', subject: 'West Chester green and a courthouse massing as an engraved view, no advertisements' },
    ],
  },
  {
    slug: 'zommick-mcmahon',
    name: 'Zommick McMahon',
    website: 'https://zmcre.com/',
    vertical: 'estate-agent',
    schema: 'RealEstateAgent',
    city: 'West Chester',
    area: 'Chester County',
    region: 'PA',
    postcode: '19382',
    phone: '610-359-1100',
    brand: '#111111',
    accent: '#edf000',
    buzz: 'knowledge integrity',
    ticker: ['Pennsylvania', 'New Jersey', 'Delaware'],
    flag: 'Copyright on the live site still said 2018 in the Aug 17 grade. Craft note, not a closed firm.',
    h1: 'Office, industrial, retail',
    lede: 'Zommick McMahon Commercial Real Estate publishes brokerage across PA, NJ, and DE: investments, office, retail, industrial, plus multi-family, hospitality, land, health care, special-purpose, and mixed-use. Phone on the site we read: 610-359-1100.',
    sections: [
      { title: 'Their three words', body: '“Knowledge. Integrity. Results.” is on the homepage. This demo does not add a fourth. Landlord and tenant representation are both listed.' },
      { title: 'The stale year', body: 'A footer stuck on 2018 is why the grade called the page dated. That is a one-line fix on their side, and a reason a rebuild pitch would bounce.' },
      { title: 'Pictures', body: 'Engraved industrial and office-massing studies. Not their listings. Not their faces.' },
    ],
    slots: [
      { alt: 'Engraved two-colour study of an industrial bay and dock, no tenants', subject: 'An industrial bay, a dock high door, and a clear-span truss as an elevation' },
      { alt: 'Engraved two-colour study of an office floor plate, no tenants', subject: 'A simple office floor plate with a core and a window wall, engraved, no logos' },
      { alt: 'Engraved two-colour tri-state ridge without real listings', subject: 'An abstract PA–NJ–DE ridge and river plate, engraved, no addresses' },
    ],
  },
].map((site) => {
  site.slots = site.slots.map((slot, i) => ({
    n: i + 1,
    alt: slot.alt,
    prompt: prompt(site.brand, site.accent, slot.subject),
  }));
  return site;
});
