// Copy depth pass.
// The first cut of data.js landed each page around 220 to 280 words of body
// copy; the house standard in ../../philly-sites/DESIGN-SYSTEM.md is 350 to 500.
// This layer deepens the three fields every archetype renders (service
// descriptions, story, feature) without touching the harvested facts. Names,
// phones, addresses, service lists, years and claims still come from data.js.

module.exports = {
  'academy-chiropractic-center': {
    services: [
      ['Chiropractic adjustment', 'Hands-on spinal care built around what your body is actually doing, not a template applied to every patient who walks through the door.'],
      ['Soft tissue therapy', 'Massage and manual work on the muscle that keeps pulling the joint back out of place, so the adjustment has something to hold onto.'],
      ['Posture and movement', 'Stretching and corrective work you can do at home, so the relief you leave with is still there by your next visit.'],
      ['Injury recovery', 'A plan for getting back to normal with a beginning and an end, rather than an open ended schedule that never quite finishes.'],
      ['Wellness care', 'Ongoing maintenance for people who spend the working day at a desk in Center City and feel it by Thursday afternoon.'],
      ['New patient exam', 'A full history and examination before anyone touches your spine, because the complaint you came in with is rarely the whole story.'],
    ],
    story: 'Located in the heart of Center City, Academy Chiropractic Center is unlike most other medical or chiropractic offices. We strive to replicate the personalized experience of a family practice, where the person treating you knows your history without reading it off a screen. From our inception we have endeavored not only to alleviate pain but to teach patients what caused it, because a patient who understands the cause is the one who stops coming back with the same problem.',
    feature: 'No overbooked rooms and no rotating hands. You see the same person on every visit and they remember what your last week looked like, which matters when the pain is tied to how you sit, sleep and work. That continuity is the whole reason this practice has stayed small since 1999.',
  },
  'acupuncture-medical-practice': {
    services: [
      ['Acupuncture', 'Thin needle treatment placed by a practitioner who explains every point before it goes in, so nothing about the session is a surprise.'],
      ['Chinese herbal medicine', 'Formulas prescribed alongside treatment rather than instead of it, adjusted as your response to the needles changes over a course of care.'],
      ['Interstitial cystitis program', 'A dedicated treatment program for a condition most clinics will not take on, built out over years of treating it specifically.'],
      ['Pain management', 'Chronic pain worked from the source rather than masked, with a course of treatment you can measure progress against.'],
      ['Fertility support', 'Cycle aware care coordinated with whatever your physician already has you doing, not offered as a replacement for it.'],
      ['Stress and sleep', 'Treatment for the things that keep you up at night and keep your shoulders somewhere around your ears all day.'],
    ],
    story: 'We are a holistic healthcare center combining acupuncture, Chinese herbal medicine, and advanced alternative medical techniques to treat our patients. Care starts with a full intake rather than a quick complaint form, because the thing you came in for is rarely the only thing going on. Treatment then moves at the pace your body sets, and the plan is revised as your response changes rather than run to a fixed number of sessions booked in advance.',
    feature: 'Recognition from the city we practice in, and it came the way that recognition should: from patients who kept coming back and kept sending people. The award sits on the wall, but the referral list is the part that matters to us, and it is the reason we have stayed on Chestnut Street.',
  },
  'bridesburg-spine-and-injury-clinic': {
    services: [
      ['Back pain treatment', 'The complaint most people walk in with, worked down to what is actually causing it rather than treated at the spot that hurts.'],
      ['Neck pain treatment', 'Range of motion restored on a plan with an endpoint, not a standing appointment that quietly becomes permanent.'],
      ['Headache treatment', 'Headaches and whiplash traced back to the neck they usually come from, which is why the painkillers were never fixing them.'],
      ['Auto injury care', 'Early intervention after a collision, documented properly from day one so the record exists when somebody later asks for it.'],
      ['Shoulder and jaw (TMJ) pain', 'The joints people ignore until they cannot chew a meal or reach the top shelf without planning the movement first.'],
      ['Radicular pain and vertigo', 'Nerve pain, dizziness, vertigo and thoracic outlet syndrome, treated by someone who sees these presentations every week.'],
    ],
    story: 'Auto injuries, whiplash, headaches, neck pain, back pain, shoulder pain, jaw pain, radicular pain, dizziness and vertigo. The list is long because the delay between the injury and the first visit is what turns a short problem into a long one. Soft tissue that heals in a shortened position stays shortened, and by the time most people book, the body has already built its compensation. Getting seen in the first week changes what the treatment is even trying to undo.',
    feature: 'One doctor, one clinic, one set of hands, which means nobody has to be caught up on your case at the start of every appointment. Curricula vitae and patient testimonials are on the record for anyone who wants to read them before booking, and most people do.',
  },
  'bustleton-services': {
    services: [
      ['Tree service', 'Removal, trimming and clearing on active commercial sites, sequenced around the trades that still need to get their work done.'],
      ['Fence installation', 'Perimeter and security fencing scoped to the site in front of us rather than pulled off a catalogue page.'],
      ['Landscaping', 'Commercial grounds built to survive the foot traffic they actually get, not the traffic the drawing assumed.'],
      ['Site clearing', 'Getting the lot ready before anyone else can start, which is the task that quietly sets every other schedule on the job.'],
      ['Grounds maintenance', 'Ongoing contracts for properties that cannot afford to look neglected, on a visit schedule you can hold us to.'],
      ['Storm response', 'The calls that come in after the weather rather than during business hours, answered by people who have the equipment staged.'],
    ],
    story: 'Since 1988, Bustleton Services has been a leading provider of commercial contracting services in the Philadelphia area. With over 30 years of experience, our team is dedicated to quality craftsmanship, safety, and professional service on every project. Three decades on commercial sites teaches you that the work itself is rarely the hard part. The hard part is showing up when you said, working around the other trades, and leaving the site in a condition the next crew can actually use.',
    feature: 'Our three pillars guide every project, and the one clients bring up first is communication. On a commercial site the surprise costs more than the work, so we would rather make the awkward phone call on Tuesday than hand over an invoice with a story attached on Friday.',
  },
  'dependable-concrete': {
    services: [
      ['Concrete steps', 'Front steps poured and finished to hold up to a Philadelphia winter, where the freeze and thaw cycle is what actually breaks concrete.'],
      ['Concrete driveways', 'Driveways, walkways and curb work laid on a base built to carry the load, which is why they are not cracking in year two.'],
      ['Concrete patios', 'Backyard patios and slabs formed and poured in a single pass, so there is no cold joint waiting to open up later.'],
      ['Basement floors and walls', 'Below grade work done by a crew that does it every week rather than as an occasional favour between other jobs.'],
      ['Basement waterproofing', 'Waterproofing across Philadelphia and the surrounding areas, addressing where the water is getting in instead of where it is showing up.'],
      ['Concrete resurfacing', 'Bringing back the surface that is already there when the slab underneath is sound, which is a great deal cheaper than replacing it.'],
    ],
    story: 'Thank you for visiting Dependable Concrete Contractor LLC. We are experienced concrete contractors with 35 years of service in Philadelphia. Steps, walkways, driveways, patios, backyards, resurfacing, curbs, basement floors, basement walls and waterproofing. Thirty five years in the same city means we have gone back to look at our own work a decade later, and that is the standard the pours get held to now: not how it looks the week it cures, but how it looks after ten winters.',
    feature: 'Reliable work, quoted before it starts, with the number you were given at the start being the number on the invoice at the end. Recommendations, testimonials and a full project gallery are all on the record, because in this trade the only reference that means anything is a slab somebody can go and stand on.',
  },
  'e-and-e-cleaning': {
    services: [
      ['House cleaning', 'Regular cleans for homes that need one less thing on the list, done by the same small team rather than whoever was free.'],
      ['Apartment cleaning', 'Apartments and condos priced by the actual place after we have seen it, not estimated by bedroom count over the phone.'],
      ['Move in and move out', 'The deep clean that decides whether the deposit comes back, done to the standard a landlord inspection is actually applied at.'],
      ['Commercial cleaning', 'Offices and small commercial spaces on a schedule built around your hours rather than ours.'],
      ['Deep cleaning', 'The one that gets behind the appliances and inside the cabinets, booked when the regular clean is no longer enough on its own.'],
      ['Recurring service', 'Weekly, biweekly or monthly with the same team each visit, so nobody has to be told twice how you like things done.'],
    ],
    story: 'We are a local cleaning company, family owned and operated. We provide residential and commercial cleaning to all of Philadelphia and the surrounding areas. Thank you so much for your patience while we build a better and easier way to book with us. Being family run is the reason the same faces keep turning up at the same houses, and it is why the standard does not slip on the fifth visit or the fiftieth.',
    feature: 'Online booking through the site is currently unavailable while we rebuild it. Email eandecleaning@mail.com or call and text (267) 593-0603 for an instant quote, which in practice is faster anyway, because we can ask the two or three questions that actually determine the price.',
  },
  'farrells-roofing': {
    services: [
      ['Roofing', 'Full replacements and repairs on flat and pitched roofs, quoted after somebody has actually been up there to look at it.'],
      ['Siding', 'Siding replaced by the same crew that handles the roof line, so the two meet properly instead of being somebody else problem.'],
      ['Gutters', 'Gutters and downspouts sized for the roof they are draining, which is why they keep up in a real Philadelphia downpour.'],
      ['Shingles', 'Shingle work matched to what is already on the block, so the house does not end up announcing that it had work done.'],
      ['Capping', 'Capping on trim and windows so the wood underneath stops rotting and the paint stops lifting every second season.'],
      ['Silver coat', 'Silver coating that reflects the heat and buys a sound flat roof several more years before it needs replacing.'],
    ],
    story: "Farrell's Roofing is a family owned and operated roofing company serving Philadelphia and the surrounding areas since 1997. Our services include roofing, siding, gutters, shingles, capping and silver coat. Twenty five years working the same row homes, twins and flat roofs means we already know how the houses on your block were built and where they tend to fail, which is usually the difference between fixing the leak and chasing it.",
    feature: 'Licensed and insured, family run, and twenty five years in the same market with the same phone number. The crew that quotes the job is the crew that does the job, so nothing gets promised at the kitchen table that the people on the roof have not agreed to.',
  },
  'greater-philadelphia-chiropractic-center': {
    services: [
      ['Chiropractic techniques', 'Adjustment methods and the tools that go with them, explained before they are used rather than after you ask what that was.'],
      ['Sports injuries', 'Injuries from the field and the gym treated with return to play in mind, not just the pain gone by Friday.'],
      ['Coping with pain', 'Self care you can actually do between appointments, which is what determines whether progress holds or resets each week.'],
      ['Types of therapies', 'A range of therapies matched to the condition in front of us rather than to whatever the schedule makes easiest.'],
      ['Exercise and prevention', 'General prevention guidance and exercise programming aimed at the injury you have not had yet.'],
      ['Anatomy education', 'Key body structures and terms laid out plainly, so you can follow your own case instead of nodding along to it.'],
    ],
    story: 'Anatomy, exercise, health tips, general prevention, key body structures and terms, treatments, chiropractic techniques and tools, coping with pain, and types of therapies. Patients who understand what is happening get better outcomes, and that is not a slogan. Someone who knows why their neck is doing this will change the thing at work that is causing it. Someone who does not will be back in six weeks with the same complaint and the same setup waiting at home.',
    feature: 'An ongoing newsletter for patients who want to keep learning between visits, alongside a full library covering new patients, office information and services. Nobody has to phone the front desk to find out what happens at a first appointment, because it is all written down.',
  },
  'hal-rosenthaler-dmd': {
    services: [
      ['Dental implants', 'Placed and restored in one practice, so nobody gets handed between offices halfway through a treatment that takes months.'],
      ['Porcelain veneers', 'Cosmetic work shaped to your face and your other teeth, rather than to a shade guide held up under surgery lighting.'],
      ['Crowns and bridges', 'Restorations built to last for years rather than to get through this one, which is the cheaper answer over any real timeframe.'],
      ['Periodontal care', 'Gum health handled early, before it becomes the expensive problem that takes the teeth around it down with it.'],
      ['Root canal', 'Endodontic treatment done gently and in house, by someone you have already met rather than a specialist across town.'],
      ['Teeth whitening and bonding', 'Whitening, bonding, dentures and fillings, all with the same unhurried approach the rest of the practice runs on.'],
    ],
    story: 'Dr. Rosenthaler provides dentistry that looks good, feels good, lasts a long time, and fits within your means. Specializing in prosthetic, restorative, cosmetic and implant dentistry, his gentle techniques combine with the caring nature of our team. That last constraint is deliberate and it is stated up front: the best plan is the one you will actually complete, so treatment gets sequenced around what is realistic rather than presented as a single number to accept or decline.',
    feature: 'Follow along on Instagram with Dr. Rosenthaler on his travels with his family and learn about the many beautiful places he photographs between appointments. It is an unusual thing for a dental practice to lead with, and it tells you something accurate about the person who will be treating you.',
  },
  'lawrence-kassan-podiatry': {
    services: [
      ['Bunions', 'Conservative care first, with surgery only when it has earned its place rather than offered as the opening move.'],
      ['Heel pain', 'The complaint that gets people out of bed badly, treated properly instead of managed with another insert and a shrug.'],
      ['Sports injuries', 'Foot and ankle injuries with a return to activity plan attached, because rest alone is not a rehabilitation programme.'],
      ['Ingrown toenails and fungus', 'Toenail fungus and ingrown nails handled in office, usually in a single visit and usually far sooner than people book it.'],
      ['Diabetic foot care', 'Diabetic foot conditions monitored on a schedule, catching the small thing before it becomes the thing nobody can reverse.'],
      ['Stress fractures and hallux rigidus', 'Corns, calluses, stress fractures and hallux rigidus, diagnosed properly rather than assumed from the symptom.'],
    ],
    story: 'As a Philadelphia podiatrist, Dr. Kassan specializes in medical and surgical care of the foot and ankle. With two office locations and convenient hours, we are able to see patients quickly and give them a means to understand their own condition. Feet get ignored longer than any other part of the body, mostly because people assume the pain is normal for their age or their job. It usually is not, and most of what comes through the door is straightforward once somebody looks at it.',
    feature: 'The practice built this site to give patients a means of understanding what is happening to their feet before they ever sit in the chair. Board certified in foot and ankle, two locations, and hours arranged so that seeing somebody does not mean taking a day off work.',
  },
  'marthas-sophisticated-shine': {
    services: [
      ['Home cleaning', 'Recurring residential cleaning for houses across the city, on a rhythm that fits the way the household actually runs.'],
      ['Airbnb turnovers', 'Fast turnarounds between guests, done to the standard that reviews reward rather than the standard that merely passes.'],
      ['Condo and apartment cleaning', 'Buildings, units and everything the lease quietly lists as your responsibility rather than the management company.'],
      ['Deep cleaning', 'The reset clean before a season, a move or a visit, when the regular schedule is no longer enough on its own.'],
      ['Personalized cleaning', 'Cleaning the way you like it, written down on the first visit and still being followed on the fiftieth.'],
      ['Move in and move out', 'The clean that settles the deposit conversation before it turns into a disagreement over email.'],
    ],
    story: 'We provide exceptional home cleaning services for residential homes, Airbnb, condos and apartment units. Because our clients know how well we care for and maintain their home, they keep us on the calendar year after year. That is the whole business model, stated plainly. There is no marketing budget behind this company, only a client list that has grown by word of mouth in a city where people are quick to tell a neighbour who they trust with a key.',
    feature: 'Martha L., founder: cleaning the way you like it, with a touch of sophistication. The preferences you give us on day one are the ones we work from on visit fifty, which sounds like a small thing until you have had a cleaner who kept moving everything back to where they thought it belonged.',
  },
  'mayfair-family-chiropractic': {
    services: [
      ['Acute and chronic injuries', 'The new injury and the one you have had for years, which are usually more connected than anybody has told you.'],
      ['Back and neck pain', 'Back, neck, head and joint pain worked as one system, because treating them as four separate complaints is why they keep returning.'],
      ['Total whole body health', 'Care that does not stop at the vertebra it started on, and does not pretend the rest of your week is irrelevant.'],
      ['Nutritional counseling', 'What you eat addressed alongside what you feel, without being turned into a supplement plan you did not ask for.'],
      ['Lifestyle management', 'The habits that keep undoing the adjustment, identified and worked on rather than quietly tolerated.'],
      ['Family care', 'Patients and their families guided at every step, which matters when the whole household has the same desk and the same couch.'],
    ],
    story: 'Mayfair Family Chiropractic Center is the leading chiropractic clinic in Philadelphia, and now in Wilmington, DE. We have been managing our patients health since 1995. We offer proactive, whole body care from back, neck, head and joint pain to nutritional counseling and lifestyle management. Thirty years in Northeast Philadelphia means we are treating the second generation of some families now, and that history is genuinely useful when a complaint turns out to run in one.',
    feature: 'Our professional team guides patients and their families throughout their health journeys. Schedule an appointment today to make sure you are on the right track. Complete care without the premium price is a claim the practice has made for years, and it holds because the model was built around volume of care rather than margin per visit.',
  },
  'mayfair-fence': {
    services: [
      ['Chain link fence', 'The workhorse fence, installed straight and tensioned properly, which is the entire difference between a good one and a sagging one.'],
      ['Wood fence', 'Privacy and picket in wood, with posts set deep enough to survive the freeze cycle that lifts every shortcut out of the ground.'],
      ['Iron fence', 'Ornamental iron for properties where the fence is part of the look rather than just the boundary.'],
      ['Custom iron works', 'Custom welding and iron work built in our own shop, for the gates and railings nobody stocks in a standard size.'],
      ['Commercial fencing', 'Building your commercial fencing solution to the spec the site needs, including the parts the drawing left vague.'],
      ['Privacy and picket', 'The two everybody asks for, done without the shortcuts that only become visible in the second year.'],
    ],
    story: 'Warranty, free estimates, increased security. Chain link, wood, iron fencing, installation, privacy and picket. Take a look at our recent projects and our full gallery of fences and gates. A fence is one of the few things a homeowner buys that is judged entirely from the street, so it either looks right or it does not, and there is nowhere to hide a line that wanders or a gate that catches.',
    feature: 'Custom welding and iron work, done by the same shop that installs the fence. Gates, railings and the pieces nobody stocks get made here rather than ordered in and made to fit, which is why the custom work matches the run it is attached to.',
  },
  'metro-physical-medicine': {
    services: [
      ['Medical doctor', 'Our on site medical doctor builds an individualized plan for your injury, working from the same file as everyone else treating you.'],
      ['Chiropractic care', 'Adjustment and manual care coordinated with the medical side, rather than two practices sending notes back and forth.'],
      ['Workers compensation', 'Work injury cases handled with the documentation the claim actually requires, prepared as we go rather than reconstructed later.'],
      ['Sports injuries', 'Injuries treated with return to activity as the goal, because pain relief alone tends to produce the same injury again.'],
      ['Physical therapy', 'Rehabilitation in a brand new, state of the art facility, on programming that progresses instead of repeating.'],
      ['Transportation', 'No ride to your appointment? No problem, we can help, and that offer is the reason some patients finish their course of care.'],
    ],
    story: 'We develop unique treatment plans for each patient. We offer chiropractic care, workers comp and sports injury treatment. Our on site medical doctor helps create an individualized plan to help you recover from an injury. Having the physician and the chiropractor in the same building changes the pace of everything: imaging gets ordered the same day it is indicated, and the plan gets adjusted in a conversation rather than across a two week referral gap.',
    feature: 'No problem. We can arrange transportation to your appointment at Metro Physical Medicine, because missing care over a ride is the wrong reason to stay hurt. It is the least glamorous thing this practice offers and it is quietly one of the most useful, particularly for patients recovering from a collision who no longer have a car.',
  },
  'moss-contracting': {
    services: [
      ['Residential wiring', 'Whole home wiring and rewiring done to code the first time, so the inspection is a formality rather than an event.'],
      ['New construction', 'Electrical for new builds scheduled around the other trades, because rough in at the wrong moment holds up everybody.'],
      ['Commercial electrical', 'Wiring installation for commercial clients working to real deadlines, with the dates agreed before the work starts.'],
      ['Panel and service work', 'Service upgrades for houses now asking a great deal more from a panel than it was ever specified to give.'],
      ['Lighting installation', 'Interior and exterior lighting planned before it is installed, rather than positioned wherever the existing runs made it easy.'],
      ['Investor friendly work', 'Real estate investor friendly scheduling and pricing, quoted for the unit rather than for the conversation.'],
    ],
    story: 'With over 20 years of experience working in the electrical and construction field, we established Moss Contracting to help homeowners and companies get work done right. We are a family owned and operated company specializing in new construction and residential wiring. Electrical is the trade where corners cut are hardest to see and most expensive to find later, which is why the work here gets done the same way whether or not anybody is coming to inspect it.',
    feature: 'Investors get the thing they actually need, which is not the lowest number on the quote. It is a crew that turns up on the day it said, prices the job honestly, and gets the unit ready to turn, because on a rental the week lost is worth more than the discount negotiated.',
  },
  'northeast-family-foot-care': {
    services: [
      ['Family foot care', 'Quality foot and ankle care for every age in the house, from the child growing out of shoes to the grandparent who needs watching.'],
      ['Heel and arch pain', 'The pain that announces itself on the first step of the morning, which is a specific pattern with a specific cause.'],
      ['Diabetic foot care', 'Regular monitoring for feet that cannot afford a missed problem, on a schedule rather than when something is already wrong.'],
      ['Nail and skin conditions', 'Ingrown nails, fungus, corns and calluses, treated in office and usually far more easily than people expect.'],
      ['Sports and activity injuries', 'Injuries treated with getting you back out there as the point, not simply waiting for the pain to fade.'],
      ['Pediatric podiatry', "Children's feet checked by people who see them all day and know which things are worth watching and which resolve on their own."],
    ],
    story: 'At Northeast Family Foot Care we believe that a visit to the doctor does not have to be a chore. We want you to feel relaxed and at home. In fact, in our office, you are not just a patient, you are part of the practice. Podiatry sees a lot of people who put the visit off for a year, and the tone of the office is a deliberate response to that, because the appointment somebody dreads is the appointment they postpone until it is harder to fix.',
    feature: 'New patients should arrive 15 minutes prior to the scheduled time to allow for collection of information. Please bring your insurance card and a list of any medications. Getting that out of the way at the front means the appointment itself is spent on your feet rather than on paperwork.',
  },
  'oxford-rehabilitation-center': {
    services: [
      ['Chiropractic therapy', 'The core of the practice, with chiropractic FAQs answered up front so nobody arrives unsure what is about to happen.'],
      ['Physical therapy', 'Rehabilitation programming that progresses week to week instead of repeating the same sheet until the sessions run out.'],
      ['Aquatic therapy', 'Water based rehabilitation for bodies that cannot load yet, which is often the only way to start moving at all.'],
      ['Hands-on techniques', 'Manual therapy from clinicians who reach for their hands before they reach for a machine.'],
      ['Motor vehicle accidents', 'Accident cases documented and treated properly from the first visit, while the record is still worth something.'],
      ['Work related injuries', 'Work injuries and the professional services that go with them, handled by people who deal with the paperwork weekly.'],
    ],
    story: 'Top rated chiropractic rehab center in Philadelphia, serving the community for over 30 years. Rehab services include chiropractic therapy, physical therapy, hands-on techniques and aquatic therapy. Motor vehicle accidents and work related injuries are a large part of what we handle. Having all four disciplines in one building is what lets a patient move between them as they recover, starting in the water and finishing on the floor without ever being referred out and starting over.',
    feature: 'Water carries the load your joints cannot. For patients early in recovery it is often the only way to start moving without setting progress back, and it lets rehabilitation begin weeks earlier than it otherwise could. That head start compounds across the whole course of treatment.',
  },
  'patriot-fence-and-ironworks': {
    services: [
      ['Vinyl fence and railings', 'Vinyl fence and railing systems that still look new several seasons in, with none of the annual upkeep wood demands.'],
      ['Chain link fence', 'Installed in one day as promised, slats included, tensioned properly so the line stays true along its whole run.'],
      ['Wood fence', 'Wood fencing built by a crew that measures twice and sets posts for the ground they are actually going into.'],
      ['Aluminum fence', 'Aluminum for properties that want the look of ornamental iron without committing to the maintenance that comes with it.'],
      ['Iron work', 'Custom iron work from the ironworks half of the business, which is why the gate matches the fence it hangs on.'],
      ['Financing', 'Financing available so the fence does not have to wait on the budget, quoted plainly alongside the price of the work.'],
    ],
    story: 'Vinyl fence, chain link fence, wood fence, aluminum fence, iron work and financing. Customers describe prompt initial meetings, on time estimates, and a true perfectionist leading the install. Those three things are the whole job in this trade, because a fence is quoted from a conversation and judged from the sidewalk, and the gap between the two is where most companies in this business lose their customers.',
    feature: 'Great communication and excellent workmanship is the review this business gets most often, and it is the one worth putting on the front page. It is also the harder pair to deliver together, since the crews that do beautiful work are frequently the ones nobody can reach on the phone.',
  },
  'philly-medical-and-rehab-associates': {
    services: [
      ['Automotive accident', 'Collision injuries assessed and documented from the first visit, while the connection between the crash and the pain is still clear.'],
      ['Workers compensation', 'Work injuries handled with the paperwork the claim requires, prepared properly rather than assembled after somebody asks.'],
      ['Personal injury', 'Slip and fall trauma to bones, joints, muscles and ligaments, which can happen almost anywhere on the body.'],
      ['Chronic pain management', 'Severe injuries that have become a chronic source of pain, treated as the long problem they have turned into.'],
      ['Rehabilitation', 'Getting daily life back once the limitations have set in, which is a different goal from simply reducing the pain score.'],
      ['Diagnostic assessment', 'Finding what is actually injured before treating around it, because the loudest symptom is not always the real problem.'],
    ],
    story: 'People who suffer slip and fall injuries can experience trauma to bones, joints, muscles and ligaments on nearly any place of the body. When these injuries are severe and a chronic source of pain you may encounter limitations in your daily life. Those limitations are usually what finally brings someone in, long after the injury itself, and by then the task is not only treating the damage but undoing everything the body has learned to do around it.',
    feature: 'Monday 9am to 2pm. Tuesday through Thursday 10am to 7pm. Friday through Sunday 9am to 2pm. Injuries do not respect business hours and neither does the schedule, which matters most for accident patients who cannot take time off work in the same week they are trying to start treatment.',
  },
  'pt-in-philly': {
    services: [
      ['1-on-1 physical therapy', 'A premium hour with an experienced Doctor of Physical Therapy who is treating you and nobody else for its full length.'],
      ['Personal training', 'Certified professionals delivering structured exercise programs, written for you rather than pulled from a template.'],
      ['Injury rehabilitation', 'Rehabilitation that gets the whole hour it needs, which is usually the reason it works when previous attempts did not.'],
      ['Movement assessment', 'Finding the cause instead of chasing the symptom, which frequently means looking somewhere other than where it hurts.'],
      ['Return to sport', 'Programming built to return you to the thing you were actually doing, at the intensity you were doing it.'],
      ['Strength programming', 'Proven programs that get results, progressed on evidence rather than on how long you have been coming in.'],
    ],
    story: 'PTinPhilly is a cash based physical therapy and personal training practice founded by professionals with knowledge and experience in the fitness and wellness industry. We never book multiple patients in one hour, which allows you to have the full attention of a licensed Doctor of Physical Therapy. Anyone who has done therapy at a busy clinic knows the alternative: fifteen minutes of hands on work and forty five minutes on a table with a heat pack while the clinician runs three other rooms.',
    feature: 'Private pay lets the clinician spend the hour on you instead of on a billing code, which is the actual reason so much of the profession is moving this way. Every one of our trainers is an experienced certified professional delivering programs proven to get results.',
  },
  'rhi-construction': {
    services: [
      ['Residential roofing', 'Roof replacement and repair for homeowners across Philadelphia and South Jersey, quoted after a real inspection.'],
      ['Commercial roofing', 'Flat roof systems for business owners who cannot close for a week while the work happens above them.'],
      ['Roof leak repair', 'Finding the leak rather than coating over the general area and hoping, which is why ours tend to stay fixed.'],
      ['Roof replacement', 'Full tear off and replacement backed by a 10 to 50 year warranty, with the old roof gone rather than built over.'],
      ['Certified installation', 'Certified crews, so the manufacturer warranty on your materials actually holds when you eventually need to call on it.'],
      ['Free consultation', 'Down to earth, we meet, review your requirements and are 100% up front with terms and how we can help.'],
    ],
    story: 'Communication, honesty and integrity are the core values we achieve with each and every job. Confidently choose RHI Construction for your residential and commercial roofing needs in Philadelphia and South Jersey. We deliver reliable service and professional craftsmanship. Roofing has a reputation problem it largely earned, so this company competes on the unglamorous things: turning up when we said, explaining what we found, and putting the warranty in writing before any money changes hands.',
    feature: 'We meet, review your requirements, and are completely up front with terms and how we can help you with your roofing needs. Certified, licensed and insured before the first shingle moves, and the warranty explained in plain terms rather than left in the paperwork for you to discover later.',
  },
  'rittenhouse-square-chiropractic': {
    services: [
      ['Chiropractic care', 'Corrective chiropractic care for neck, mid back and low back, aimed at changing the pattern rather than managing it indefinitely.'],
      ['Functional rehabilitation', 'Rehabilitation that rebuilds the movement rather than only the joint, so the correction has something holding it in place.'],
      ['Functional nutrition', 'Nutrition addressed as part of the treatment plan, where it is relevant to what brought you in and not as an add on.'],
      ['TMJD treatment', 'Jaw pain treated by doctors who see it regularly, which is far from true of every practice you could take it to.'],
      ['Auto accidents and whiplash', 'Personal injury doctors handling collision cases, with the documentation that those cases invariably end up needing.'],
      ['Headaches and migraines', 'Chiropractic care aimed at the headache pattern itself, which for many people originates in the neck.'],
    ],
    story: 'Dr. Jason Nutche, DC. Dr. Steven Realdine, DC. Dr. Michael Narvid, DC. Chiropractic care, TMJD, auto accidents, whiplash, corrective chiropractic care, personal injury, headaches and migraines, and care for neck, mid back and low back. Three doctors in one practice means a case can be discussed rather than simply carried, and it means that if one set of hands is not getting a result, another opinion is in the next room instead of another referral away.',
    feature: 'Center City location on the sixth floor at 1608 Walnut, three licensed chiropractors, and a practice built around functional rehabilitation rather than a permanent adjustment schedule. The aim stated plainly is to get people to the point where they no longer need to come in every week.',
  },
  'rufus-chiropractic-and-wellness': {
    services: [
      ['Chiropractic care', 'Adjustment and ongoing care built around the health goals you came in with, rather than a fixed programme sold up front.'],
      ['Neck pain and sciatica', 'The two complaints that bring most people through the door, and the two that most reward finding the actual cause.'],
      ['Corrective exercises', 'Exercises that hold the correction between appointments, which is where most of the progress is really made or lost.'],
      ['Massage therapy', 'Soft tissue work alongside the adjustment, addressing the muscle that keeps returning the joint to where it started.'],
      ['Cupping and physiotherapy', 'Cupping, physiotherapy and ultrasound used where they genuinely help rather than added to fill out a treatment plan.'],
      ['Red light therapy', 'Red light therapy offered as part of the plan when it fits the case, and left out when it does not.'],
    ],
    story: 'We provide excellent chiropractic care to help our patients reach and exceed their health goals. We assess the patient as a whole. We want to know what is happening in the rest of your life, because it is usually connected to what brought you in. The intake here takes longer than most people expect for that reason, and it is regularly the part of the visit that turns up the thing nobody had connected to the pain.',
    feature: 'New patients, your first visit, what to expect, online forms, payment options and appointments are all documented before you arrive, so nothing about the first appointment is a surprise. For anyone who has been putting off seeing somebody, that tends to be the part that finally makes the call easy.',
  },
  'scrc-accident-and-injury-center': {
    services: [
      ['Motor vehicle accidents', 'Advanced and personal care for collision injuries, assessed properly rather than assumed from the accident report.'],
      ['Work related injuries', 'Work injuries diagnosed and documented for the claim, with the record built as treatment happens instead of afterwards.'],
      ['Slip and fall', 'Fall injuries assessed across bones, joints and soft tissue, since these rarely turn out to involve only one of the three.'],
      ['Chiropractic care', 'Chiropractic care and physical therapy delivered as one coordinated plan rather than two schedules running in parallel.'],
      ['Physical therapy', 'Therapy built from an analysis of how your body actually moves now, which after an injury is rarely how it moved before.'],
      ['Diagnostic evaluation', 'Physicians who diagnose before they treat, because treating the obvious symptom is how the real injury gets missed.'],
    ],
    story: 'Our team of experienced physicians and support staff put your specific needs first. With years of experience, our team of physicians is capable of analyzing your body and creating a plan built for the injury you actually have. Accident cases are rarely simple, since the collision that injured a neck usually injured a shoulder and a low back at the same time, and a plan that treats only the loudest of the three leaves two behind.',
    feature: 'Advanced and personal care for treatment of motor vehicle accidents, work related injuries, and slip and falls, coordinated across both chiropractic and physical therapy. Running them together rather than in sequence is what keeps the recovery moving when one discipline alone would have stalled.',
  },
  'zbc-general-contracting': {
    services: [
      ['Kitchens', 'Full kitchen remodels from demolition through final trim, run by one crew so nobody disappears between the trades.'],
      ['Bathrooms', 'Bathroom renovations handled start to finish, including the parts behind the wall that decide how long the rest lasts.'],
      ['Flooring and basements', 'Flooring, basements and the spaces most people leave unfinished because the quote for them never quite arrives.'],
      ['Decks, porches and sunrooms', 'Decks, porches, sunrooms, pools and ponds, built for the weather Philadelphia actually gets rather than the catalogue photo.'],
      ['Masonry and hardscaping', 'Masonry, hardscaping, fences, sheds and garages, so the outside of the property gets the same crew as the inside.'],
      ['Repairs and prep for sale', 'Repairs, preventive maintenance and prep for sale, scoped around what a buyer or inspector will actually notice.'],
    ],
    story: 'To provide our customers with the highest quality work at a fair price. ZBC General Contracting specializes in top quality interior and exterior remodeling and renovations throughout the Greater Philadelphia Area. Whether you have a small repair or a full renovation, we handle it the same way. That last part is the one worth testing a contractor on, because plenty of companies do excellent work on the large job and treat the small one as an interruption to be squeezed in whenever.',
    feature: 'That is the standard the owner holds the crew to, and it is the reason the referral list looks the way it does. For all your home repair, remodeling and renovation needs, from the repair that takes an afternoon to the renovation that takes a season.',
  },
};
