// Content layer for the Philly Batch 2 rebuild.
// Every field here is harvested from the live business site (see ../<slug>/original.html).
// Nothing invented: names, phones, addresses, services and claims are theirs.

const TONE = require('./logotone.json');
const EXPANDED = require('./copy-expand');

const IMAGES = ['image-1.webp', 'image-2.webp', 'image-3.webp', 'image-4.webp', 'image-5.webp', 'image-9.webp'];

const sites = [
  {
    slug: 'academy-chiropractic-center',
    archetype: 'aurora-drift',
    name: 'Academy Chiropractic Center',
    short: 'Academy Chiropractic',
    schema: 'MedicalBusiness',
    url: 'https://www.academychiropracticcenter.com/',
    tel: '215-546-4860',
    address: '1420 Locust St. R5, Philadelphia, PA 19102',
    city: 'Center City Philadelphia',
    eyebrow: 'Center City since 1999',
    headline: 'Chiropractic care that treats you like a person, not a chart',
    sub: 'Since 1999, Academy Chiropractic Center has provided high quality chiropractic health care in Center City Philadelphia.',
    ctaPrimary: 'Call 215-546-4860',
    ctaSecondary: 'Get directions',
    proof: [['1999', 'Serving Center City'], ['R5', '1420 Locust Street'], ['Personal', 'One patient at a time'], ['Insurance', 'Most plans accepted']],
    services: [
      ['Chiropractic adjustment', 'Hands-on spinal care built around what your body is actually doing.'],
      ['Soft tissue therapy', 'Massage and manual work on the muscle that keeps pulling the joint back out.'],
      ['Posture and movement', 'Stretching and corrective work so the relief holds between visits.'],
      ['Injury recovery', 'A plan for getting back to normal, not an open ended schedule.'],
      ['Wellness care', 'Ongoing maintenance for people who sit at a desk all day.'],
      ['New patient exam', 'A full look before anyone touches your spine.'],
    ],
    story: {
      title: 'Unlike most other chiropractic offices',
      body: 'Located in the heart of Center City, Academy Chiropractic Center is unlike most other medical or chiropractic offices. We strive to replicate the personalized experience of a family practice. From our inception we have endeavored not only to alleviate pain but to teach patients what caused it.',
    },
    feature: { title: 'One patient at a time', body: 'No overbooked rooms, no rotating hands. You see the same person on every visit and they remember what your last week looked like.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 7:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['Our services', '#services'], ['Insurance', '#visit'], ['Contact', '#visit'], ['Home', '#top']],
    closing: 'Call us today at 215-546-4860 to get started.',
    tokens: { paper: '#EAEEF0', ink: '#0D3F58', accent: '#003449', accent2: '#116DFF', panel: '#D2DDE2', deep: '#062736' },
    alts: ['Hands massaging a back', 'Adjustment room at Academy Chiropractic Center', 'A woman stretching', 'A woman stretching from a distance', 'Treatment table in the Center City office', 'Academy Chiropractic Center in Philadelphia'],
  },
  {
    slug: 'acupuncture-medical-practice',
    archetype: 'zen-strata',
    name: 'Acupuncture Medical Practice',
    short: 'Acupuncture Medical',
    schema: 'MedicalBusiness',
    url: 'https://acupuncturephilly.com/',
    tel: '215.751.9833',
    address: '1737 Chestnut Street, Ste. 200, Philadelphia, PA 19103',
    city: 'Philadelphia',
    eyebrow: 'Awarded Best of Philadelphia',
    headline: 'Your wellness journey starts here',
    sub: 'A holistic healthcare center combining acupuncture, Chinese herbal medicine, and advanced alternative medical techniques to treat our patients.',
    ctaPrimary: 'Call 215.751.9833',
    ctaSecondary: 'See all services',
    proof: [['Best of', 'Philadelphia award'], ['Ste. 200', '1737 Chestnut Street'], ['Whole person', 'Not just the symptom'], ['Herbs', 'Chinese herbal medicine']],
    services: [
      ['Acupuncture', 'Thin needle treatment placed by a practitioner who explains every point.'],
      ['Chinese herbal medicine', 'Formulas prescribed alongside treatment, not instead of it.'],
      ['Interstitial cystitis program', 'A dedicated treatment program for a condition most clinics will not touch.'],
      ['Pain management', 'Chronic pain worked from the source rather than masked.'],
      ['Fertility support', 'Cycle-aware care coordinated with what your doctor is already doing.'],
      ['Stress and sleep', 'Treatment for the things that keep you up and keep you tight.'],
    ],
    story: {
      title: 'Treating the whole person',
      body: 'We are a holistic healthcare center combining acupuncture, Chinese herbal medicine, and advanced alternative medical techniques. Care starts with a full intake, because the thing you came in for is rarely the only thing going on.',
    },
    feature: { title: 'Awarded Best of Philadelphia', body: 'Recognition from the city we practice in. It came from patients who kept coming back and kept sending people.' },
    quote: null,
    hours: [['Mon', '9:00am - 6:00pm'], ['Tue', '9:00am - 6:00pm'], ['Wed', '9:00am - 6:00pm'], ['Thu', '9:00am - 6:00pm'], ['Fri', '9:00am - 4:00pm'], ['Sat', 'By appointment']],
    links: [['How acupuncture works', '#story'], ['All services', '#services'], ['Interstitial cystitis program', '#feature'], ["Dr. Shi's blog", '#visit']],
    closing: 'Book a first visit and we will start with the whole picture.',
    tokens: { paper: '#EFEDE8', ink: '#2B2C31', accent: '#C0674F', accent2: '#117579', panel: '#DCD8D0', deep: '#25262A' },
    alts: ['Treatment room at Acupuncture Medical Practice', 'Acupuncture needles laid out before a session', 'Chinese herbal medicine cabinet', 'Practitioner reviewing an intake chart', 'Quiet treatment space on Chestnut Street', 'Acupuncture Medical Practice in Philadelphia'],
  },
  {
    slug: 'bridesburg-spine-and-injury-clinic',
    archetype: 'kinetic-blueprint',
    name: 'Bridesburg Spine and Injury Clinic',
    short: 'Bridesburg Spine',
    schema: 'MedicalBusiness',
    url: 'https://www.bridesburgchiro.com/',
    tel: '(215) 743-5330',
    address: '2644 Lefevre St, Philadelphia, PA 19137',
    city: 'Philadelphia',
    eyebrow: 'Dr. Calantoni, Bridesburg',
    headline: 'Your chiropractor in Philadelphia, PA',
    sub: 'Looking for a chiropractor in Philadelphia? Bridesburg Spine and Injury Clinic is your best choice. Call us today at (215) 743-5330 to see how we can help.',
    ctaPrimary: 'Call (215) 743-5330',
    ctaSecondary: 'What we treat',
    proof: [['Lefevre St', 'In Bridesburg'], ['Auto injuries', 'Early intervention'], ['Dr. Calantoni', 'Treating in-house'], ['Same week', 'Appointments available']],
    services: [
      ['Back pain treatment', 'The complaint most people walk in with, worked down to what is actually causing it.'],
      ['Neck pain treatment', 'Range of motion restored without a permanent appointment schedule.'],
      ['Headache treatment', 'Headaches and whiplash traced back to the neck they usually come from.'],
      ['Auto injury care', 'Early intervention after a collision, documented properly from day one.'],
      ['Shoulder and jaw (TMJ) pain', 'The joints people ignore until they cannot chew or reach.'],
      ['Radicular pain and vertigo', 'Nerve pain, dizziness, and thoracic outlet syndrome.'],
    ],
    story: {
      title: 'Early intervention changes the outcome',
      body: 'Auto injuries, whiplash, headaches, neck pain, back pain, shoulder pain, jaw pain, radicular pain, dizziness and vertigo. The list is long because the delay between the injury and the first visit is what turns a short problem into a long one.',
    },
    feature: { title: 'Meet Dr. Calantoni', body: 'One doctor, one clinic, one set of hands. Curricula vitae and patient testimonials are on the record for anyone who wants to read them first.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 1:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', 'Closed']],
    links: [['About us', '#story'], ['Meet Dr. Calantoni', '#feature'], ['Testimonials', '#visit'], ['Office photos', '#gallery']],
    closing: 'Call (215) 743-5330 and get it looked at this week.',
    tokens: { paper: '#F2F4F5', ink: '#12136B', accent: '#1238BD', accent2: '#6313BC', panel: '#D3D7E4', deep: '#0C0D4A' },
    alts: ['Chiropractic treatment in progress', 'Adjustment table at Bridesburg Spine and Injury Clinic', 'Spine model used for patient education', 'Treatment room on Lefevre Street', 'Rehab equipment at the clinic', 'Bridesburg Spine and Injury Clinic'],
  },
  {
    slug: 'bustleton-services',
    archetype: 'field-grid',
    name: 'Bustleton Services, Inc',
    short: 'Bustleton Services',
    schema: 'GeneralContractor',
    url: 'https://www.bustletonservices.com/',
    tel: '(215) 447-3140',
    address: '735 Birch Avenue, Bensalem, PA 19020',
    city: 'Greater Philadelphia and the Delaware Valley',
    eyebrow: 'Commercial contracting since 1988',
    headline: 'Your trusted tree, fence and landscaping contractor',
    sub: 'Bustleton Services has been shaping commercial job sites since 1988. Over three decades of quality craftsmanship, safety, and professional service on every project.',
    ctaPrimary: 'Call (215) 447-3140',
    ctaSecondary: 'About the company',
    proof: [['1988', 'Founded'], ['30+ yrs', 'On commercial sites'], ['Delaware Valley', 'Service area'], ['3 pillars', 'On every project']],
    services: [
      ['Tree service', 'Removal, trimming, and clearing on active commercial sites.'],
      ['Fence installation', 'Perimeter and security fencing scoped to the site, not the catalog.'],
      ['Landscaping', 'Commercial grounds built to survive the traffic they actually get.'],
      ['Site clearing', 'Getting the lot ready before anyone else can start working.'],
      ['Grounds maintenance', 'Ongoing contracts for properties that cannot look neglected.'],
      ['Storm response', 'Calls that come in after the weather, not during business hours.'],
    ],
    story: {
      title: 'Serving Greater Philadelphia and the Delaware Valley since 1988',
      body: 'Since 1988, Bustleton Services has been a leading provider of commercial contracting services in the Philadelphia area. With over 30 years of experience, our team is dedicated to quality craftsmanship, safety, and professional service on every project.',
    },
    feature: { title: 'Exceptional communication', body: 'Our three pillars guide every project. The one clients bring up first is communication, because on a commercial site the surprise costs more than the work.' },
    quote: null,
    hours: [['Mon', '7:00am - 4:00pm'], ['Tue', '7:00am - 4:00pm'], ['Wed', '7:00am - 4:00pm'], ['Thu', '7:00am - 4:00pm'], ['Fri', '7:00am - 4:00pm'], ['Sat', 'By appointment']],
    links: [['About us', '#story'], ['Contact us', '#visit'], ['Service area', '#proof'], ['Home', '#top']],
    closing: 'Three decades of commercial sites. Call (215) 447-3140.',
    tokens: { paper: '#F4F4F2', ink: '#12488B', accent: '#B39F26', accent2: '#13498B', panel: '#E4DDB6', deep: '#0D3466' },
    alts: ['Bustleton Services crew on a commercial site', 'Fence line installed on a commercial property', 'Tree work in progress', 'Landscaping on a Delaware Valley job site', 'Equipment staged at the Bensalem yard', 'Bustleton Services, Inc'],
  },
  {
    slug: 'dependable-concrete',
    archetype: 'poured-slab',
    name: 'Dependable Concrete Contractor LLC',
    short: 'Dependable Concrete',
    schema: 'HomeAndConstructionBusiness',
    url: 'https://dependableconcrete.com/',
    tel: '215-821-9779',
    address: '7715 Crittenden St, Philadelphia, PA 19118',
    city: 'Philadelphia',
    eyebrow: '35 years of service',
    headline: 'Concrete built for strong, long lasting structures',
    sub: 'Trust our reliable concrete contractors in Philadelphia for strong, long lasting structures. Book your appointment now for dependable concrete services.',
    ctaPrimary: 'Call 215-821-9779',
    ctaSecondary: 'See the gallery',
    proof: [['35 years', 'Of service'], ['Crittenden St', 'Philadelphia 19118'], ['Waterproofing', 'And surrounding areas'], ['Free', 'Estimates']],
    services: [
      ['Concrete steps', 'Front steps poured and finished to hold up to a Philly winter.'],
      ['Concrete driveways', 'Driveways, walkways, and curb work that does not crack in year two.'],
      ['Concrete patios', 'Backyard patios and slabs, formed and poured in one pass.'],
      ['Basement floors and walls', 'Below grade work done by people who do it every week.'],
      ['Basement waterproofing', 'Waterproofing in Philadelphia and surrounding areas.'],
      ['Concrete resurfacing', 'Bringing back what is there instead of tearing it all out.'],
    ],
    story: {
      title: 'About us',
      body: 'Thank you for visiting Dependable Concrete Contractor LLC. We are experienced concrete contractors with 35 years of service in Philadelphia. Steps, walkways, driveways, patios, backyards, resurfacing, curbs, basement floors, basement walls, and waterproofing.',
    },
    feature: { title: 'Need concrete contractors near Philadelphia?', body: 'Reliable work, quoted before it starts. Recommendations, testimonials and a project gallery are all on the record.' },
    quote: null,
    hours: [['Mon', '7:00am - 5:00pm'], ['Tue', '7:00am - 5:00pm'], ['Wed', '7:00am - 5:00pm'], ['Thu', '7:00am - 5:00pm'], ['Fri', '7:00am - 5:00pm'], ['Sat', '8:00am - 12:00pm']],
    links: [['Recommendations', '#feature'], ['Gallery', '#gallery'], ['Testimonials', '#feature'], ['Blog', '#visit']],
    closing: 'Book your appointment. Call 215-821-9779.',
    tokens: { paper: '#F3F3EF', ink: '#2B2B2B', accent: '#1E7BC4', accent2: '#F8BD45', panel: '#D8D6CE', deep: '#1F1F1F' },
    alts: ['Freshly poured concrete driveway', 'Concrete steps finished by Dependable Concrete', 'Concrete patio slab', 'Basement floor pour in progress', 'Waterproofing work on a Philadelphia basement', 'Dependable Concrete Contractor LLC'],
  },
  {
    slug: 'e-and-e-cleaning',
    archetype: 'fresh-bloom',
    name: 'E & E Cleaning Services',
    short: 'E & E Cleaning',
    schema: 'HomeAndConstructionBusiness',
    url: 'https://www.eandecleaning.com/',
    tel: '(267) 593-0603',
    address: '2025 South Norwood Street, Philadelphia, PA 19145',
    city: 'Philadelphia and surrounding areas',
    eyebrow: 'Family owned and operated',
    headline: 'A local cleaning company that actually shows up',
    sub: 'Residential and commercial cleaning across Philadelphia and the surrounding areas. House cleaning, apartment cleaning, and everything in between.',
    ctaPrimary: 'Call or text (267) 593-0603',
    ctaSecondary: 'Get an instant quote',
    proof: [['Family', 'Owned and operated'], ['Residential', 'And commercial'], ['Instant', 'Quote by phone or text'], ['19145', 'South Philadelphia']],
    services: [
      ['House cleaning', 'Regular cleans for homes that need one less thing to think about.'],
      ['Apartment cleaning', 'Apartments and condos, priced by the place and not by guesswork.'],
      ['Move in and move out', 'The deep clean that decides whether you get the deposit back.'],
      ['Commercial cleaning', 'Offices and small commercial spaces on a schedule that fits yours.'],
      ['Deep cleaning', 'The one that gets behind the appliances and inside the cabinets.'],
      ['Recurring service', 'Weekly, biweekly or monthly with the same team each time.'],
    ],
    story: {
      title: 'About us',
      body: 'We are a local cleaning company, family owned and operated. We provide residential and commercial cleaning to all of Philadelphia and the surrounding areas. Thank you so much for your patience while we build a better and easier way to book with us.',
    },
    feature: { title: 'Booking is by phone, text or email', body: 'Online booking through the site is currently unavailable. Email eandecleaning@mail.com or call and text (267) 593-0603 for an instant quote.' },
    quote: null,
    hours: [['Mon', '8:00am - 6:00pm'], ['Tue', '8:00am - 6:00pm'], ['Wed', '8:00am - 6:00pm'], ['Thu', '8:00am - 6:00pm'], ['Fri', '8:00am - 6:00pm'], ['Sat', '9:00am - 3:00pm']],
    links: [['Services', '#services'], ['Contact', '#visit'], ['Book online', '#visit'], ['Home', '#top']],
    closing: 'Call or text (267) 593-0603 for an instant quote.',
    tokens: { paper: '#EFF1EA', ink: '#1B1310', accent: '#4F6A00', accent2: '#7FA900', panel: '#DCE0D0', deep: '#28261F' },
    alts: ['E & E Cleaning team at work', 'Clean kitchen after a service visit', 'Cleaning supplies ready for a job', 'Freshly cleaned living space', 'Apartment cleaning in South Philadelphia', 'E & E Cleaning Services'],
  },
  {
    slug: 'farrells-roofing',
    archetype: 'pitch-shift',
    name: "Farrell's Roofing",
    short: "Farrell's Roofing",
    schema: 'RoofingContractor',
    url: 'https://www.farrellsroofingphiladelphia.com/',
    tel: '(215) 501-0276',
    address: '12801 Medford Rd, Philadelphia, PA',
    city: 'Philadelphia, Bucks County, Montgomery County and New Jersey',
    eyebrow: 'Family owned since 1997',
    headline: 'Trusted in Philadelphia for over 25 years',
    sub: "Farrell's Roofing is a licensed and insured roofing company serving Philadelphia, Bucks County, Montgomery County and New Jersey.",
    ctaPrimary: 'Call (215) 501-0276',
    ctaSecondary: 'See recent work',
    proof: [['1997', 'Family owned'], ['25+ yrs', 'In Philadelphia'], ['Licensed', 'And insured'], ['4 areas', 'PA and NJ']],
    services: [
      ['Roofing', 'Full replacements and repairs on flat and pitched roofs.'],
      ['Siding', 'Siding replaced by the same crew that handles the roof line.'],
      ['Gutters', 'Gutters and downspouts sized for the roof they are draining.'],
      ['Shingles', 'Shingle work matched to what is already on the block.'],
      ['Capping', 'Capping on trim and windows so the wood stops rotting.'],
      ['Silver coat', 'Silver coating that buys a flat roof more years.'],
    ],
    story: {
      title: 'Roofing experts you can trust',
      body: "Farrell's Roofing is a family owned and operated roofing company serving Philadelphia and the surrounding areas since 1997. Our services include roofing, siding, gutters, shingles, capping and silver coat.",
    },
    feature: { title: "Why Farrell's Roofing?", body: 'Licensed and insured, family run, and 25 years in the same market. The crew that quotes the job is the crew that does it.' },
    quote: null,
    hours: [['Mon', '7:00am - 5:00pm'], ['Tue', '7:00am - 5:00pm'], ['Wed', '7:00am - 5:00pm'], ['Thu', '7:00am - 5:00pm'], ['Fri', '7:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['About', '#story'], ['Recent work', '#gallery'], ['Contact', '#visit'], ['(215) 501-0276', '#visit']],
    closing: 'Quality roofing services. Call (215) 501-0276.',
    tokens: { paper: '#F1F7F1', ink: '#232122', accent: '#12B81C', accent2: '#2A2829', panel: '#CBE3CA', deep: '#1E1C1D' },
    alts: ['Roof replacement in progress', 'New shingle roof by Farrell\'s Roofing', 'Gutter and capping work', 'Crew working on a Philadelphia row home roof', 'Completed roofing job', "Farrell's Roofing"],
  },
  {
    slug: 'greater-philadelphia-chiropractic-center',
    archetype: 'clinic-orbit',
    name: 'Greater Philadelphia Chiropractic Center',
    short: 'Greater Philadelphia Chiropractic',
    schema: 'MedicalBusiness',
    url: 'https://www.philadelphiachiropractic.net/',
    tel: '(215) 338-8555',
    address: '2612 Rhawn St, Philadelphia, PA 19152',
    city: 'Northeast Philadelphia',
    eyebrow: 'John Maher, DC',
    headline: 'Chiropractic care and patient education on Rhawn Street',
    sub: 'Philadelphia chiropractor John Maher, DC provides chiropractic care for patients across the Philadelphia area, with an education library to match.',
    ctaPrimary: 'Call (215) 338-8555',
    ctaSecondary: 'Patient education',
    proof: [['John Maher, DC', 'Treating doctor'], ['Rhawn St', 'Northeast Philadelphia'], ['Education', 'Full patient library'], ['New patients', 'Welcome']],
    services: [
      ['Chiropractic techniques', 'Adjustment methods and the tools that go with them, explained before use.'],
      ['Sports injuries', 'Injuries from the field and the gym, treated for return to play.'],
      ['Coping with pain', 'Self care you can do between appointments so progress holds.'],
      ['Types of therapies', 'A range of therapies matched to the condition, not to the schedule.'],
      ['Exercise and prevention', 'General prevention tips and exercise programming.'],
      ['Anatomy education', 'Key body structures and terms so you understand your own case.'],
    ],
    story: {
      title: 'Patient education is part of the treatment',
      body: 'Anatomy, exercise, health tips, general prevention, key body structures and terms, treatments, chiropractic techniques and tools, coping with pain, and types of therapies. Patients who understand what is happening get better outcomes.',
    },
    feature: { title: 'To Your Health newsletter', body: 'An ongoing newsletter for patients who want to keep learning between visits. New patients, office information and services are all documented on the site.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 1:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', '9:00am - 12:00pm']],
    links: [['Office', '#story'], ['Services', '#services'], ['New patients', '#visit'], ['Contact us', '#visit']],
    closing: 'Call (215) 338-8555. Fax (215) 338-8031.',
    tokens: { paper: '#F0F0F0', ink: '#37483A', accent: '#0048FF', accent2: '#0384D7', panel: '#C9D2C7', deep: '#2C3A2F' },
    alts: ['Adjustment room at Greater Philadelphia Chiropractic Center', 'Chiropractic table on Rhawn Street', 'Patient education materials', 'Therapy equipment in the office', 'Waiting area at the practice', 'Greater Philadelphia Chiropractic Center'],
  },
  {
    slug: 'hal-rosenthaler-dmd',
    archetype: 'porcelain',
    name: 'Hal Rosenthaler DMD',
    short: 'Rosenthaler DMD',
    schema: 'Dentist',
    url: 'https://halrosenthalerdmd.com/',
    tel: '215-673-7400',
    address: '1718 Welsh Road, Philadelphia, PA',
    city: 'Philadelphia',
    eyebrow: 'Hal Rosenthaler, D.M.D., F.A.G.D.',
    headline: 'Dentistry that looks good, feels good and lasts a long time',
    sub: "Specializing in prosthetic, restorative, cosmetic and implant dentistry. Dr. Rosenthaler's gentle techniques combine with the caring nature of our team.",
    ctaPrimary: 'Call 215-673-7400',
    ctaSecondary: 'Our services',
    proof: [['F.A.G.D.', 'Fellow, Academy of General Dentistry'], ['Welsh Road', '1718'], ['Gentle', 'Technique first'], ['Implants', 'Placed and restored']],
    services: [
      ['Dental implants', 'Placed and restored in one practice so nobody hands you off.'],
      ['Porcelain veneers', 'Cosmetic work shaped to your face, not to a shade guide.'],
      ['Crowns and bridges', 'Restorations built to last rather than to get through the year.'],
      ['Periodontal care', 'Gum health handled before it becomes the expensive problem.'],
      ['Root canal', 'Endodontic treatment done gently and in-house.'],
      ['Teeth whitening and bonding', 'Whitening, bonding, dentures and fillings.'],
    ],
    story: {
      title: 'Our commitment to you',
      body: 'Dr. Rosenthaler provides dentistry that looks good, feels good, lasts a long time, and fits within your means. Specializing in prosthetic, restorative, cosmetic and implant dentistry, his gentle techniques combine with the caring nature of our team.',
    },
    feature: { title: 'Dr. Rosenthaler is an avid travel photographer', body: 'Follow along on Instagram with Dr. Rosenthaler on his travels with his family and learn about the many beautiful places he photographs between appointments.' },
    quote: null,
    hours: [['Mon', '9:00am - 5:00pm'], ['Tue', '9:00am - 7:00pm'], ['Wed', '9:00am - 5:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 2:00pm'], ['Sat', 'Closed']],
    links: [['Our services', '#services'], ['Meet Dr. Rosenthaler', '#story'], ['Office hours', '#visit'], ['Contact', '#visit']],
    closing: 'Call 215-673-7400 to schedule.',
    tokens: { paper: '#EFEFEF', ink: '#2E2E2E', accent: '#0C71C3', accent2: '#165BA0', panel: '#CFE0BC', deep: '#22384F' },
    alts: ['Treatment room at Hal Rosenthaler DMD', 'Dental chair and equipment', 'Reception area on Welsh Road', 'Cosmetic dentistry work', 'Travel photograph by Dr. Rosenthaler', 'Hal Rosenthaler DMD'],
  },
  {
    slug: 'lawrence-kassan-podiatry',
    archetype: 'step-trace',
    name: 'Lawrence Kassan Podiatry',
    short: 'Dr. Kassan, DPM',
    schema: 'MedicalBusiness',
    url: 'https://www.philadelphiafeet.com/',
    tel: '(215) 336-4151',
    address: '2101 Snyder Avenue, Philadelphia, PA 19145',
    city: 'Philadelphia',
    eyebrow: 'Board certified foot and ankle specialist',
    headline: 'Got foot pain? We can help. Call today.',
    sub: 'Dr. Lawrence Kassan, DPM is a board certified foot and ankle specialist with two office locations and convenient hours across Philadelphia.',
    ctaPrimary: 'Call (215) 336-4151',
    ctaSecondary: 'Conditions we treat',
    proof: [['Board certified', 'Foot and ankle'], ['2 locations', 'Philadelphia'], ['Accepting', 'New patients'], ['Snyder Ave', '2101']],
    services: [
      ['Bunions', 'Conservative care first, surgery only when it earns its place.'],
      ['Heel pain', 'The complaint that gets people out of bed badly, treated properly.'],
      ['Sports injuries', 'Foot and ankle injuries with a return to activity plan.'],
      ['Ingrown toenails and fungus', 'Toenail fungus and ingrown nails handled in office.'],
      ['Diabetic foot care', 'Diabetic foot conditions monitored before they escalate.'],
      ['Stress fractures and hallux rigidus', 'Corns, calluses, stress fractures and hallux rigidus.'],
    ],
    story: {
      title: 'Medical and surgical care of the foot and ankle',
      body: 'As a Philadelphia podiatrist, Dr. Kassan specializes in medical and surgical care of the foot and ankle. With two office locations and convenient hours, we are able to see patients quickly and give them a means to understand their own condition.',
    },
    feature: { title: 'Accepting new patients', body: 'The practice built this site to give patients a means of understanding what is happening to their feet before they ever sit in the chair.' },
    quote: null,
    hours: [['Mon', '9:00am - 5:00pm'], ['Tue', '9:00am - 5:00pm'], ['Wed', '9:00am - 5:00pm'], ['Thu', '9:00am - 5:00pm'], ['Fri', '9:00am - 3:00pm'], ['Sat', 'By appointment']],
    links: [['About', '#story'], ['Meet Dr. Kassan, DPM', '#feature'], ['Conditions we treat', '#services'], ['Patient resources', '#visit']],
    closing: 'We can help. Call today at (215) 336-4151.',
    tokens: { paper: '#F5F4F1', ink: '#131412', accent: '#0F86B8', accent2: '#A00A0A', panel: '#D9CCB0', deep: '#111211' },
    alts: ['Podiatry exam room', 'Foot and ankle assessment', 'Treatment equipment at the Snyder Avenue office', 'Orthotics and footwear fitting', 'Waiting room at Lawrence Kassan Podiatry', 'Lawrence Kassan Podiatry'],
  },
  {
    slug: 'marthas-sophisticated-shine',
    archetype: 'gilded-sheen',
    name: "Martha's Sophisticated Shine",
    short: "Sophisticated Shine",
    schema: 'HomeAndConstructionBusiness',
    url: 'https://sophisticatedshine.com/',
    tel: '(267) 694-9410',
    address: 'Philadelphia, PA',
    city: 'Philadelphia and the surrounding area',
    eyebrow: 'Family owned residential cleaning',
    headline: 'Cleaning the way you like it, with a touch of sophistication',
    sub: 'Exceptional residential cleaning for homes, Airbnb units, condos and apartments across Philadelphia and the surrounding area.',
    ctaPrimary: 'Call (267) 694-9410',
    ctaSecondary: 'See specials',
    proof: [['Family owned', 'Philadelphia'], ['Airbnb', 'Turnovers welcome'], ['Personalized', 'Every home'], ['Residential', 'Homes and condos']],
    services: [
      ['Home cleaning', 'Recurring residential cleaning for houses across the city.'],
      ['Airbnb turnovers', 'Fast turnarounds between guests, done to the standard reviews reward.'],
      ['Condo and apartment cleaning', 'Buildings, units and everything the lease calls your responsibility.'],
      ['Deep cleaning', 'The reset clean before a season, a move, or a visit.'],
      ['Personalized cleaning', 'Cleaning the way you like it, written down and followed.'],
      ['Move in and move out', 'The clean that settles the deposit conversation.'],
    ],
    story: {
      title: 'Because our clients know how well we care for their home',
      body: 'We provide exceptional home cleaning services for residential homes, Airbnb, condos and apartment units. Because our clients know how well we care for and maintain their home, they keep us on the calendar year after year.',
    },
    feature: { title: 'Personalized cleaning', body: 'Martha L., founder: "Cleaning the way you like it, with a touch of sophistication." The preferences you give us on day one are the ones we work from on visit fifty.' },
    quote: { text: 'Cleaning the way you like it, with a touch of sophistication.', who: 'Martha L., Founder' },
    hours: [['Mon', '8:00am - 6:00pm'], ['Tue', '8:00am - 6:00pm'], ['Wed', '8:00am - 6:00pm'], ['Thu', '8:00am - 6:00pm'], ['Fri', '8:00am - 6:00pm'], ['Sat', 'By appointment']],
    links: [['Specials', '#feature'], ['Services', '#services'], ['News', '#visit'], ['Contact', '#visit']],
    closing: 'Book Martha and her team. Call (267) 694-9410.',
    tokens: { paper: '#FBF3E5', ink: '#170A0B', accent: '#C79A2E', accent2: '#876E2E', panel: '#F0E1C6', deep: '#1F0707' },
    alts: ["Martha's Sophisticated Shine team at work", 'Cleaned and staged living room', 'Kitchen after a Sophisticated Shine visit', 'Airbnb unit turned over and ready', 'Detail work on a residential clean', "Martha's Sophisticated Shine LLC"],
  },
  {
    slug: 'mayfair-family-chiropractic',
    archetype: 'spinal-column',
    name: 'Mayfair Family Chiropractic Center',
    short: 'Mayfair Family Chiropractic',
    schema: 'MedicalBusiness',
    url: 'https://www.mayfairchiro.com/',
    tel: '(215) 332-8686',
    address: '3301 Ryan Ave, Philadelphia, PA',
    city: 'Northeast Philadelphia',
    eyebrow: 'Managing patient health since 1995',
    headline: "Northeast Philadelphia's chiropractic clinic",
    sub: 'The leading chiropractic clinic in Philadelphia and now in Wilmington, DE. We have been managing our patients health since 1995 with proactive, whole body care.',
    ctaPrimary: 'Call (215) 332-8686',
    ctaSecondary: 'Meet the team',
    proof: [['1995', 'Managing patient health'], ['2 cities', 'Philadelphia and Wilmington'], ['Whole body', 'Not just the spine'], ['Ryan Ave', '3301']],
    services: [
      ['Acute and chronic injuries', 'The new injury and the one you have had for years.'],
      ['Back and neck pain', 'Back, neck, head and joint pain worked as one system.'],
      ['Total whole body health', 'Care that does not stop at the vertebra it started on.'],
      ['Nutritional counseling', 'What you eat, addressed alongside what you feel.'],
      ['Lifestyle management', 'The habits that keep undoing the adjustment.'],
      ['Family care', 'Patients and their families guided at every step.'],
    ],
    story: {
      title: 'Complete care without the premium price',
      body: 'Mayfair Family Chiropractic Center is the leading chiropractic clinic in Philadelphia, and now in Wilmington, DE. We have been managing our patients health since 1995. We offer proactive, whole body care from back, neck, head and joint pain to nutritional counseling and lifestyle management.',
    },
    feature: { title: 'Every step of the way', body: 'Our professional team guides patients and their families throughout their health journeys. Schedule an appointment today to make sure you are on the right track.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 1:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', '9:00am - 12:00pm']],
    links: [['Meet the team', '#feature'], ['Our services', '#services'], ['Blog', '#visit'], ['Contact us', '#visit']],
    closing: 'Complete care without the premium price. Call (215) 332-8686.',
    tokens: { paper: '#EAF5F7', ink: '#101312', accent: '#003862', accent2: '#6FB6C4', panel: '#B9DDE4', deep: '#0C1417' },
    alts: ['Adjustment in progress at Mayfair Family Chiropractic', 'Physiotherapy equipment', 'Senior physiotherapy session', 'Muscle stimulation therapy', 'Treatment room on Ryan Avenue', 'Mayfair Family Chiropractic Center'],
  },
  {
    slug: 'mayfair-fence',
    archetype: 'picket-run',
    name: 'Mayfair Fence',
    short: 'Mayfair Fence',
    schema: 'HomeAndConstructionBusiness',
    url: 'https://www.mayfairfence.com/',
    tel: '215-676-1120',
    address: '13420 Damar Drive, Philadelphia, PA',
    city: 'Philadelphia',
    eyebrow: 'Warranty and free estimates',
    headline: 'We build and install fences',
    sub: 'Chain link, wood and iron fencing. Installation, privacy and picket. Warranty, free estimates, increased security. Call 215-676-1120.',
    ctaPrimary: 'Call 215-676-1120',
    ctaSecondary: 'Fence gallery',
    proof: [['Warranty', 'On installation'], ['Free', 'Estimates'], ['Chain link', 'Wood and iron'], ['Damar Drive', 'Philadelphia']],
    services: [
      ['Chain link fence', 'The workhorse fence, installed straight and tensioned right.'],
      ['Wood fence', 'Privacy and picket in wood, set to survive the freeze cycle.'],
      ['Iron fence', 'Ornamental iron for properties where the fence is part of the look.'],
      ['Custom iron works', 'Custom welding and iron work built in house.'],
      ['Commercial fencing', 'Building your commercial fencing solution to spec.'],
      ['Privacy and picket', 'The two everybody asks for, done without shortcuts.'],
    ],
    story: {
      title: 'Building your commercial fencing solution',
      body: 'Warranty, free estimates, increased security. Chain link, wood, iron fencing, installation, privacy and picket. Take a look at our recent projects and our full gallery of fences and gates.',
    },
    feature: { title: 'Custom iron works', body: 'Custom welding and iron work, done by the same shop that installs the fence. Gates, railings and the pieces nobody stocks.' },
    quote: { text: 'I was so happy I went with Mayfair Fence.', who: 'Mayfair Fence customer' },
    hours: [['Mon', '8:00am - 4:30pm'], ['Tue', '8:00am - 4:30pm'], ['Wed', '8:00am - 4:30pm'], ['Thu', '8:00am - 4:30pm'], ['Fri', '8:00am - 4:30pm'], ['Sat', 'By appointment']],
    links: [['Fence gallery', '#gallery'], ['Recent projects', '#gallery'], ['Contact Mayfair Fence Inc.', '#visit'], ['Home', '#top']],
    closing: 'Free estimates. Call 215-676-1120.',
    tokens: { paper: '#F2F2F2', ink: '#1E2225', accent: '#E06A04', accent2: '#204F00', panel: '#D5C6B3', deep: '#1B1E21' },
    alts: ['Wood privacy fence installed by Mayfair Fence', 'Chain link fence line', 'Custom iron gate', 'Picket fence on a Philadelphia property', 'Commercial fencing installation', 'Mayfair Fence'],
  },
  {
    slug: 'metro-physical-medicine',
    archetype: 'vitals-monitor',
    name: 'Metro Physical Medicine',
    short: 'Metro Physical Medicine',
    schema: 'MedicalBusiness',
    url: 'https://metrophysicalmedicine.com/',
    tel: '215-422-3140',
    address: '15 N. 22nd Street, Philadelphia, PA',
    city: 'Philadelphia',
    eyebrow: 'Medical doctor plus chiropractic care',
    headline: 'Medical doctor and chiropractic care under one roof',
    sub: 'Our goal at Metro Physical Medicine Group is to provide the best care, helping those who need us most. Brand new, state of the art facility.',
    ctaPrimary: 'Call 215-422-3140',
    ctaSecondary: 'Our services',
    proof: [['MD on site', 'Plus chiropractic'], ['New facility', 'State of the art'], ['Transportation', 'Provided if needed'], ['22nd St', '15 North']],
    services: [
      ['Medical doctor', 'Our on-site medical doctor builds an individualized plan for your injury.'],
      ['Chiropractic care', 'Adjustment and manual care coordinated with the medical side.'],
      ['Workers compensation', 'Work injury cases handled with the documentation they require.'],
      ['Sports injuries', 'Injuries treated for return to activity, not just pain relief.'],
      ['Physical therapy', 'Rehab in a brand new, state of the art facility.'],
      ['Transportation', 'No ride to your appointment? No problem, we can help.'],
    ],
    story: {
      title: 'Unique treatment plans for each patient',
      body: 'We develop unique treatment plans for each patient. We offer chiropractic care, workers comp and sports injury treatment. Our on-site medical doctor helps create an individualized plan to help you recover from an injury.',
    },
    feature: { title: 'Are you without a ride?', body: 'No problem. We can arrange transportation to your appointment at Metro Physical Medicine, because missing care over a ride is the wrong reason to stay hurt.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 7:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['Locations', '#visit'], ['Insurance', '#visit'], ['Transportation', '#feature'], ['Services', '#services']],
    closing: 'Call 215-422-3140 and we will build the plan around you.',
    tokens: { paper: '#ECECEC', ink: '#141617', accent: '#198FD9', accent2: '#E85C41', panel: '#C4DDD0', deep: '#181A1B' },
    alts: ['Treatment floor at Metro Physical Medicine', 'Treadmills in the rehab facility', 'Exam room with the on-site medical doctor', 'Rehab equipment at the 22nd Street facility', 'Chiropractic table at Metro Physical Medicine', 'Metro Physical Medicine'],
  },
  {
    slug: 'moss-contracting',
    archetype: 'circuit-live',
    name: 'Moss Contracting',
    short: 'Moss Contracting',
    schema: 'GeneralContractor',
    url: 'https://mosscontractingllc.com/',
    tel: '(267) 303-3614',
    address: '2924 Ridge Ave, Philadelphia, PA',
    city: 'Philadelphia',
    eyebrow: 'Lighting up Pennsylvania since 2012',
    headline: 'Electrical work, lighting up Pennsylvania since 2012',
    sub: 'Moss Contracting is an electrician in Philadelphia specializing in new construction and residential wiring. Family owned and operated.',
    ctaPrimary: 'Call (267) 303-3614',
    ctaSecondary: 'See the gallery',
    proof: [['2012', 'Established'], ['20+ yrs', 'In the field'], ['Family owned', 'And operated'], ['Ridge Ave', '2924']],
    services: [
      ['Residential wiring', 'Whole home wiring and rewiring done to code the first time.'],
      ['New construction', 'Electrical for new builds, scheduled around the rest of the trades.'],
      ['Commercial electrical', 'Wiring installation for commercial clients on real deadlines.'],
      ['Panel and service work', 'Service upgrades for houses asking more than the panel can give.'],
      ['Lighting installation', 'Interior and exterior lighting, planned and installed.'],
      ['Investor friendly work', 'Real estate investor friendly scheduling and pricing.'],
    ],
    story: {
      title: 'Our purpose',
      body: 'With over 20 years of experience working in the electrical and construction field, we established Moss Contracting to help homeowners and companies get work done right. We are a family owned and operated company specializing in new construction and residential wiring.',
    },
    feature: { title: 'Real estate investor friendly', body: 'Investors get the thing they actually need: a crew that shows up on schedule, prices the job honestly, and gets the unit ready to turn.' },
    quote: null,
    hours: [['Mon', '7:00am - 5:00pm'], ['Tue', '7:00am - 5:00pm'], ['Wed', '7:00am - 5:00pm'], ['Thu', '7:00am - 5:00pm'], ['Fri', '7:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['Gallery', '#gallery'], ['Residential wiring', '#services'], ['Contact us', '#visit'], ['Home', '#top']],
    closing: 'We get the job done. Call (267) 303-3614.',
    tokens: { paper: '#F2F3F0', ink: '#252A20', accent: '#0075C1', accent2: '#F2A007', panel: '#D5D8CC', deep: '#1A1E16' },
    alts: ['Electrical utility meter on house exterior siding', 'Close up of a worker drilling holes in a wall at a construction site', 'New construction wiring by Moss Contracting', 'Golden sunset over large buildings', 'Interior of a finished hotel bathroom', 'Moss Contracting'],
  },
  {
    slug: 'northeast-family-foot-care',
    archetype: 'soft-arch',
    name: 'Northeast Family Foot Care',
    short: 'Northeast Family Foot Care',
    schema: 'MedicalBusiness',
    url: 'https://www.northeastfamilyfootcare.com/',
    tel: '(215) 464-4444',
    address: '9892 Bustleton Ave., First Floor, Philadelphia, PA 19115',
    city: 'Northeast Philadelphia',
    eyebrow: 'Foot and ankle care for all ages',
    headline: 'Foot doctors in Northeast Philadelphia',
    sub: 'Northeast Family Foot Care Podiatry provides quality family foot and ankle care for all ages. A visit to the doctor does not have to be a chore.',
    ctaPrimary: 'Make an appointment',
    ctaSecondary: 'Our services',
    proof: [['All ages', 'Family podiatry'], ['First floor', '9892 Bustleton Ave'], ['15 min early', 'For new patients'], ['The team', 'Full staff on site']],
    services: [
      ['Family foot care', 'Quality foot and ankle care for every age in the house.'],
      ['Heel and arch pain', 'The pain that shows up on the first step of the morning.'],
      ['Diabetic foot care', 'Regular monitoring for feet that cannot afford a missed problem.'],
      ['Nail and skin conditions', 'Ingrown nails, fungus, corns and calluses.'],
      ['Sports and activity injuries', 'Injuries treated so you get back on the field.'],
      ['Pediatric podiatry', "Children's feet checked by people who see them all day."],
    ],
    story: {
      title: 'You are not just a chart number',
      body: 'At Northeast Family Foot Care we believe that a visit to the doctor does not have to be a chore. We want you to feel relaxed and at home. In fact, in our office, you are not just a patient, you are part of the practice.',
    },
    feature: { title: 'Your first visit', body: 'New patients should arrive 15 minutes prior to the scheduled time to allow for collection of information. Please bring your insurance card and a list of medications.' },
    quote: null,
    hours: [['Mon', '9:00am - 5:00pm'], ['Tue', '9:00am - 6:00pm'], ['Wed', '9:00am - 5:00pm'], ['Thu', '9:00am - 6:00pm'], ['Fri', '9:00am - 3:00pm'], ['Sat', 'By appointment']],
    links: [['Our services', '#services'], ['The team', '#feature'], ['Contact and directions', '#visit'], ['Staff', '#visit']],
    closing: 'Make an appointment with Northeast Family Foot Care.',
    tokens: { paper: '#F4F0EA', ink: '#173040', accent: '#C79A67', accent2: '#116DFF', panel: '#E6D8C6', deep: '#173040' },
    alts: ['Dancer toes', 'Tying a sneaker', "Child's foot in an adult hand", 'Exam room at Northeast Family Foot Care', 'Podiatry office on Bustleton Avenue', 'Northeast Family Foot Care'],
  },
  {
    slug: 'oxford-rehabilitation-center',
    archetype: 'aqua-lane',
    name: 'Oxford Rehabilitation Center',
    short: 'Oxford Rehab',
    schema: 'MedicalBusiness',
    url: 'https://www.oxfordrehab.com/',
    tel: '(215) 725-2000',
    address: '6735 Harbison Ave, Philadelphia, PA',
    city: 'Philadelphia',
    eyebrow: 'Serving the community for 30+ years',
    headline: 'Top rated chiropractic rehab center in Philadelphia',
    sub: 'Serving the community for over 30 years. Chiropractic therapy, physical therapy, hands-on techniques and aquatic therapy under one roof.',
    ctaPrimary: 'Call (215) 725-2000',
    ctaSecondary: 'Explore services',
    proof: [['30+ years', 'Serving the community'], ['Aquatic', 'Therapy on site'], ['Harbison Ave', '6735'], ['Mon 9-7', 'Extended hours']],
    services: [
      ['Chiropractic therapy', 'The core of the practice, with chiropractic FAQs answered up front.'],
      ['Physical therapy', 'Rehab programming that progresses instead of repeating.'],
      ['Aquatic therapy', 'Water based rehab for bodies that cannot load yet.'],
      ['Hands-on techniques', 'Manual therapy from clinicians who use their hands first.'],
      ['Motor vehicle accidents', 'Accident cases documented and treated properly.'],
      ['Work related injuries', 'Work injuries and the professional services that go with them.'],
    ],
    story: {
      title: 'Putting our patients first',
      body: 'Top rated chiropractic rehab center in Philadelphia, serving the community for 30+ years. Rehab services include chiropractic therapy, physical therapy, hands-on techniques and aquatic therapy. Motor vehicle accidents and work related injuries are a large part of what we handle.',
    },
    feature: { title: 'Benefits of aquatic therapy', body: 'Water carries the load your joints cannot. For patients early in recovery it is often the only way to start moving without setting progress back.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 7:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['About us', '#story'], ['Virtual office', '#gallery'], ['Testimonials', '#feature'], ['Our services', '#services']],
    closing: 'Call (215) 725-2000. Monday 9:00am to 7:00pm.',
    tokens: { paper: '#EFF3F6', ink: '#0F3366', accent: '#2E547E', accent2: '#FF7927', panel: '#C7D6E2', deep: '#12283F' },
    alts: ['Aquatic therapy pool at Oxford Rehabilitation Center', 'Physical therapy floor', 'Chiropractic treatment room', 'Rehab equipment on Harbison Avenue', 'Hands-on manual therapy session', 'Oxford Rehabilitation Center'],
  },
  {
    slug: 'patriot-fence-and-ironworks',
    archetype: 'forge-iron',
    name: 'Patriot Fence & Ironworks, LLC',
    short: 'Patriot Fence',
    schema: 'HomeAndConstructionBusiness',
    url: 'https://www.patriotfenceandironworks.com/',
    tel: '215-943-3631',
    address: '77 Canyon Road, Levittown, PA 19057',
    city: 'Levittown and Greater Philadelphia',
    eyebrow: 'Vinyl, chain link, wood, aluminum, iron',
    headline: 'Vinyl fence, railings and ironwork',
    sub: 'Vinyl fence, chain link fence, wood fence, aluminum fence, iron work and financing. Installed by a crew customers call perfectionists.',
    ctaPrimary: 'Call 215-943-3631',
    ctaSecondary: 'Contact Patriot',
    proof: [['Financing', 'Available'], ['Canyon Road', 'Levittown, PA'], ['One day', 'Typical install'], ['Grade: A+', 'Customer review']],
    services: [
      ['Vinyl fence and railings', 'Vinyl fence and railing systems that stay looking new.'],
      ['Chain link fence', 'Installed in one day as promised, slats included.'],
      ['Wood fence', 'Wood fencing built by a crew that measures twice.'],
      ['Aluminum fence', 'Aluminum for properties that want the look without the upkeep.'],
      ['Iron work', 'Custom iron work from the ironworks side of the business.'],
      ['Financing', 'Financing available so the fence does not wait on the budget.'],
    ],
    story: {
      title: 'About Patriot',
      body: 'Vinyl fence, chain link fence, wood fence, aluminum fence, iron work and financing. Customers describe prompt initial meetings, on time estimates, and a true perfectionist leading the install.',
    },
    feature: { title: 'Installed in one day as promised', body: 'Great communication and excellent workmanship. That is the review this business gets most, and it is the one worth putting on the front page.' },
    quote: { text: 'In a word, superb. Prompt, courteous, thorough. I cannot say enough in praise of their work. I am having them come back for another project. Grade: A+', who: 'Patriot Fence customer' },
    hours: [['Mon', '8:00am - 5:00pm'], ['Tue', '8:00am - 5:00pm'], ['Wed', '8:00am - 5:00pm'], ['Thu', '8:00am - 5:00pm'], ['Fri', '8:00am - 5:00pm'], ['Sat', '9:00am - 1:00pm']],
    links: [['Vinyl fence', '#services'], ['Chain link fence', '#services'], ['Wood fence', '#services'], ['Contact', '#visit']],
    closing: 'Call now. 215-943-3631.',
    tokens: { paper: '#F3F1F1', ink: '#8F1A2B', accent: '#2E86D6', accent2: '#9D1C30', panel: '#DCC3C8', deep: '#1A1416' },
    alts: ['Vinyl fence and railing installation', 'Chain link fence with slats', 'Custom iron work by Patriot Ironworks', 'Wood fence on a Levittown property', 'Aluminum fence line', 'Patriot Fence & Ironworks, LLC'],
  },
  {
    slug: 'philly-medical-and-rehab-associates',
    archetype: 'case-file',
    name: 'Philly Medical and Rehab Associates',
    short: 'Philly Medical and Rehab',
    schema: 'MedicalBusiness',
    url: 'https://www.mypmra.com/',
    tel: '(215) 535-5616',
    address: '6401 Rising Sun Ave, Philadelphia, PA 19111',
    city: 'Philadelphia',
    eyebrow: 'Accident, injury and workers comp',
    headline: 'Philly Medical and Rehab Associates welcomes you',
    sub: 'Automotive accident, workers compensation and personal injury care. To schedule your appointment, fill out the form or give us a call at (215) 535-5616.',
    ctaPrimary: 'Call (215) 535-5616',
    ctaSecondary: 'Schedule appointment',
    proof: [['7 days', 'Open all week'], ['Rising Sun Ave', '6401'], ['Auto and work', 'Injury cases'], ['Same week', 'Scheduling']],
    services: [
      ['Automotive accident', 'Collision injuries assessed and documented from the first visit.'],
      ['Workers compensation', 'Work injuries handled with the paperwork the claim requires.'],
      ['Personal injury', 'Slip and fall trauma to bones, joints, muscles and ligaments.'],
      ['Chronic pain management', 'Severe injuries that became a chronic source of pain.'],
      ['Rehabilitation', 'Getting daily life back after the limitations set in.'],
      ['Diagnostic assessment', 'Finding what is actually injured before treating around it.'],
    ],
    story: {
      title: 'When the injury becomes the limitation',
      body: 'People who suffer slip and fall injuries can experience trauma to bones, joints, muscles and ligaments on nearly any place of the body. When these injuries are severe and a chronic source of pain you may encounter limitations in your daily life.',
    },
    feature: { title: 'Open seven days', body: 'Monday 9am to 2pm. Tuesday through Thursday 10am to 7pm. Friday through Sunday 9am to 2pm. Injuries do not respect business hours and neither does the schedule.' },
    quote: null,
    hours: [['Mon', '9:00am - 2:00pm'], ['Tue', '10:00am - 7:00pm'], ['Wed', '10:00am - 7:00pm'], ['Thu', '10:00am - 7:00pm'], ['Fri', '9:00am - 2:00pm'], ['Sat / Sun', '9:00am - 2:00pm']],
    links: [['Services', '#services'], ['Schedule appointment', '#visit'], ['Team', '#feature'], ['Contact', '#visit']],
    closing: 'Fill out the form or call (215) 535-5616. We look forward to seeing you.',
    tokens: { paper: '#F4F4F4', ink: '#121212', accent: '#E24E4E', accent2: '#116DFF', panel: '#E6CFCF', deep: '#1C1C1C' },
    alts: ['Doctor reviewing patient files', 'Exam room at Philly Medical and Rehab Associates', 'Rehab equipment on Rising Sun Avenue', 'Treatment session in progress', 'Reception at the practice', 'Philly Medical and Rehab Associates'],
  },
  {
    slug: 'pt-in-philly',
    archetype: 'one-on-one',
    name: 'PT in Philly',
    short: 'PT in Philly',
    schema: 'MedicalBusiness',
    url: 'https://www.ptinphilly.com/',
    tel: '(267) 201-0986',
    address: '241 South 2nd Street, Philadelphia, PA 19106',
    city: 'Philadelphia',
    eyebrow: 'Cash based physical therapy',
    headline: 'One hour. One patient. One Doctor of Physical Therapy.',
    sub: 'A cash based physical therapy and personal training practice. We never book multiple patients in one hour, which means you get the full attention of a licensed Doctor of Physical Therapy.',
    ctaPrimary: 'Call (267) 201-0986',
    ctaSecondary: 'Book a session',
    proof: [['1-on-1', 'Never double booked'], ['DPT', 'Doctor of Physical Therapy'], ['Cash based', 'No insurance games'], ['2nd Street', '241 South']],
    services: [
      ['1-on-1 physical therapy', 'A premium experience with an experienced Doctor of Physical Therapy.'],
      ['Personal training', 'Certified professionals delivering structured exercise programs.'],
      ['Injury rehabilitation', 'Rehab that gets the full hour it needs to actually work.'],
      ['Movement assessment', 'Finding the cause instead of chasing the symptom.'],
      ['Return to sport', 'Programming built to get you back to what you were doing.'],
      ['Strength programming', 'Proven programs that get results, no equipment excuses.'],
    ],
    story: {
      title: 'Our philosophy',
      body: 'PTinPhilly is a cash based physical therapy and personal training practice founded by professionals with knowledge and experience in the fitness and wellness industry. We never book multiple patients in one hour, which allows you to have the full attention of a licensed Doctor of Physical Therapy.',
    },
    feature: { title: 'Why the industry is going cash based', body: 'Private pay lets the clinician spend the hour on you instead of on a billing code. Every one of our trainers is an experienced certified professional delivering programs proven to get results.' },
    quote: null,
    hours: [['Mon', '7:00am - 7:00pm'], ['Tue', '7:00am - 7:00pm'], ['Wed', '7:00am - 7:00pm'], ['Thu', '7:00am - 7:00pm'], ['Fri', '7:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['Book', '#visit'], ['Team', '#feature'], ['FAQ', '#story'], ['Cash based vs insurance', '#feature']],
    closing: 'See you soon. Call (267) 201-0986.',
    tokens: { paper: '#FAF7E8', ink: '#40292A', accent: '#E63535', accent2: '#116DFF', panel: '#F0E8CD', deep: '#3A2626' },
    alts: ['One on one physical therapy session', 'Training floor at PT in Philly', 'Doctor of Physical Therapy working with a patient', 'Strength programming in progress', 'Studio on South 2nd Street', 'PT in Philly'],
  },
  {
    slug: 'rhi-construction',
    archetype: 'ridge-line',
    name: 'RHI Construction Inc.',
    short: 'RHI Construction',
    schema: 'RoofingContractor',
    url: 'https://www.rhihomes.com/',
    tel: '267-872-3318',
    address: '21 Wolf Street, Philadelphia, PA 19148',
    city: 'Philadelphia and South Jersey',
    eyebrow: 'Family owned and operated',
    headline: 'Residential and commercial roofing experts',
    sub: 'Focused on quality, safety and dependability. Fully licensed, insured and certified, with a 10 to 50 year roof warranty.',
    ctaPrimary: 'Call 267-872-3318',
    ctaSecondary: 'Why choose RHI',
    proof: [['10-50 yr', 'Roof warranty'], ['Licensed', 'Insured and certified'], ['Family', 'Owned and operated'], ['PA and NJ', 'Philadelphia and South Jersey']],
    services: [
      ['Residential roofing', 'Roof replacement and repair for homeowners across Philadelphia.'],
      ['Commercial roofing', 'Flat roof systems for business owners who cannot close for a week.'],
      ['Roof leak repair', 'Finding the leak instead of coating over the guess.'],
      ['Roof replacement', 'Full tear off and replacement backed by the warranty.'],
      ['Certified installation', 'Certified crews so the manufacturer warranty actually holds.'],
      ['Free consultation', 'Down to earth, meet, review requirements, 100% up front on terms.'],
    ],
    story: {
      title: 'Why choose RHI',
      body: 'Communication, honesty and integrity are the core values we achieve with each and every job. Confidently choose RHI Construction for your residential and commercial roofing needs in Philadelphia and South Jersey. We deliver reliable service and professional craftsmanship.',
    },
    feature: { title: 'Down to earth and 100% up front', body: 'We meet, review your requirements, and are completely up front with terms and how we can help you with your roofing needs. Certified, licensed and insured before the first shingle moves.' },
    quote: null,
    hours: [['Mon', '7:00am - 5:00pm'], ['Tue', '7:00am - 5:00pm'], ['Wed', '7:00am - 5:00pm'], ['Thu', '7:00am - 5:00pm'], ['Fri', '7:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['Home owners', '#services'], ['Business owners', '#services'], ['Contact us', '#visit'], ['Home', '#top']],
    closing: 'Trust us with your roof replacement and repairs. Call 267-872-3318.',
    tokens: { paper: '#F3F4F0', ink: '#12482A', accent: '#1D6634', accent2: '#88BC4A', panel: '#CFDCC4', deep: '#0F2E1C' },
    alts: ['RHI Construction repairing a roof leak on a flat roof in Philadelphia', 'Commercial roofing job in progress', 'Residential roof replacement', 'Crew working on a certified roof install', 'Completed roof by RHI Construction', 'RHI Construction Inc.'],
  },
  {
    slug: 'rittenhouse-square-chiropractic',
    archetype: 'liquid-suite',
    name: 'Rittenhouse Square Chiropractic',
    short: 'Rittenhouse Chiro',
    schema: 'MedicalBusiness',
    url: 'https://rittenhousechiro.com/',
    tel: '(215) 546-1010',
    address: '1608 Walnut Street, 6th Floor, Philadelphia, PA',
    city: 'Rittenhouse Square, Philadelphia',
    eyebrow: 'Three doctors on Walnut Street',
    headline: 'Chiropractic care, functional rehabilitation, functional nutrition',
    sub: 'For the best chiropractor in Philadelphia and wellness care, call the experienced chiropractors at Rittenhouse Square Chiropractic.',
    ctaPrimary: 'Call (215) 546-1010',
    ctaSecondary: 'Meet the doctors',
    proof: [['3 doctors', 'On staff'], ['6th floor', '1608 Walnut Street'], ['Rittenhouse', 'Square'], ['Auto injury', 'Personal injury doctors']],
    services: [
      ['Chiropractic care', 'Corrective chiropractic care for neck, mid back and low back.'],
      ['Functional rehabilitation', 'Rehab that rebuilds the movement, not just the joint.'],
      ['Functional nutrition', 'Nutrition addressed as part of the treatment plan.'],
      ['TMJD treatment', 'Jaw pain treated by doctors who see it regularly.'],
      ['Auto accidents and whiplash', 'Personal injury doctors handling collision cases.'],
      ['Headaches and migraines', 'Chiropractic care aimed at the headache pattern itself.'],
    ],
    story: {
      title: 'Three doctors, one practice',
      body: 'Dr. Jason Nutche, DC. Dr. Steven Realdine, DC. Dr. Michael Narvid, DC. Chiropractic care, TMJD, auto accidents, whiplash, corrective chiropractic care, personal injury, headaches and migraines, and care for neck, mid back and low back.',
    },
    feature: { title: 'On the sixth floor at 1608 Walnut', body: 'Center City location, three licensed chiropractors, and a practice built around functional rehabilitation rather than a permanent adjustment schedule.' },
    quote: null,
    hours: [['Mon', '8:00am - 7:00pm'], ['Tue', '8:00am - 7:00pm'], ['Wed', '8:00am - 7:00pm'], ['Thu', '8:00am - 7:00pm'], ['Fri', '8:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['About us', '#story'], ['Dr. Jason Nutche, DC', '#story'], ['Dr. Steven Realdine, DC', '#story'], ['Dr. Michael Narvid, DC', '#story']],
    closing: 'Call (215) 546-1010 for the best chiropractor in Philadelphia.',
    tokens: { paper: '#F2F2F2', ink: '#2C2C2C', accent: '#1F7E89', accent2: '#99D7DB', panel: '#D2E4E6', deep: '#1D3336' },
    alts: ['Treatment room at Rittenhouse Square Chiropractic', 'Adjustment in progress', 'Functional rehabilitation space', 'View from the sixth floor office on Walnut Street', 'Rehab equipment at the practice', 'Rittenhouse Square Chiropractic'],
  },
  {
    slug: 'rufus-chiropractic-and-wellness',
    archetype: 'stone-garden',
    name: 'Rufus Chiropractic and Wellness',
    short: 'Rufus Chiropractic',
    schema: 'MedicalBusiness',
    url: 'https://www.rufuschiropractic.com/',
    tel: '(215) 673-1113',
    address: '2875 Holme Ave, Philadelphia, PA 19152',
    city: 'Northeast Philadelphia',
    eyebrow: 'Accepting new appointments',
    headline: 'We assess the patient as a whole',
    sub: 'Rufus Chiropractic and Wellness is a skilled chiropractor in Philadelphia, PA. Accepting new appointments. Call today or request an appointment on our website.',
    ctaPrimary: 'Call (215) 673-1113',
    ctaSecondary: 'New patients',
    proof: [['New patients', 'Welcome'], ['Holme Ave', '2875'], ['Whole patient', 'Assessment'], ['Red light', 'Therapy available']],
    services: [
      ['Chiropractic care', 'Adjustment and ongoing care built around your health goals.'],
      ['Neck pain and sciatica', 'The two complaints that bring most people through the door.'],
      ['Corrective exercises', 'Exercises that hold the correction between appointments.'],
      ['Massage therapy', 'Soft tissue work alongside the adjustment.'],
      ['Cupping and physiotherapy', 'Cupping, physiotherapy and ultrasound where they help.'],
      ['Red light therapy', 'Red light therapy as part of the treatment plan.'],
    ],
    story: {
      title: 'About our office',
      body: 'We provide excellent chiropractic care to help our patients reach and exceed their health goals. We assess the patient as a whole. We want to know what is happening in the rest of your life, because it is usually connected to what brought you in.',
    },
    feature: { title: 'Your first visit', body: 'New patients, your first visit, what to expect, online forms, payment options and appointments are all documented before you arrive so nothing is a surprise.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 1:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', '9:00am - 12:00pm']],
    links: [['Meet the doctor', '#story'], ['Meet the staff', '#feature'], ['New patients', '#visit'], ['Your first visit', '#feature']],
    closing: 'Accepting new appointments. Call (215) 673-1113.',
    tokens: { paper: '#F3F4F1', ink: '#343938', accent: '#41675F', accent2: '#A8B6C2', panel: '#D8DFD9', deep: '#2C302E' },
    alts: ['Chiropractor in Philadelphia, PA', 'Treatment room at Rufus Chiropractic and Wellness', 'Payment options desk', 'Your first visit at the Holme Avenue office', 'Therapy equipment at the practice', 'Rufus Chiropractic and Wellness'],
  },
  {
    slug: 'scrc-accident-and-injury-center',
    archetype: 'impact-dossier',
    name: 'SCRC Accident & Injury Center',
    short: 'SCRC',
    schema: 'MedicalBusiness',
    url: 'https://springcrc.com/',
    tel: '(267) 286-0934',
    address: '7707 Ogontz Ave, Philadelphia, PA 19150',
    city: 'Philadelphia',
    eyebrow: 'Accident and injury physicians',
    headline: "Philadelphia's most trusted accident and injury center",
    sub: 'Experienced physicians who diagnose and treat conditions related to motor vehicle collisions, work related injuries, and slip and falls.',
    ctaPrimary: 'Call (267) 286-0934',
    ctaSecondary: 'Our services',
    proof: [['Physicians', 'Experienced team'], ['Ogontz Ave', '7707'], ['Auto, work, falls', 'Three case types'], ['Personal', 'Care plans']],
    services: [
      ['Motor vehicle accidents', 'Advanced and personal care for collision injuries.'],
      ['Work related injuries', 'Work injuries diagnosed and documented for the claim.'],
      ['Slip and fall', 'Fall injuries assessed across bones, joints and soft tissue.'],
      ['Chiropractic care', 'Chiropractic care and physical therapy in one plan.'],
      ['Physical therapy', 'Therapy built from an analysis of how your body actually moves.'],
      ['Diagnostic evaluation', 'Physicians who diagnose before they treat.'],
    ],
    story: {
      title: 'About us',
      body: 'Our team of experienced physicians and support staff put your specific needs first. With years of experience, our team of physicians is capable of analyzing your body and creating a plan built for the injury you actually have.',
    },
    feature: { title: 'Chiropractic care and physical therapy', body: 'Advanced and personal care for treatment of motor vehicle accidents, work related injuries, and slip and falls, coordinated across both disciplines.' },
    quote: null,
    hours: [['Mon', '9:00am - 7:00pm'], ['Tue', '9:00am - 7:00pm'], ['Wed', '9:00am - 7:00pm'], ['Thu', '9:00am - 7:00pm'], ['Fri', '9:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['About us', '#story'], ['Our services', '#services'], ['Contact', '#visit'], ['Home', '#top']],
    closing: 'Call (267) 286-0934 and start the plan today.',
    tokens: { paper: '#E4E4E4', ink: '#3F3F3F', accent: '#2A71DE', accent2: '#0544A4', panel: '#B6B6B6', deep: '#141414' },
    alts: ['Exam room at SCRC Accident & Injury Center', 'Physical therapy floor', 'Physician reviewing an injury case', 'Treatment equipment on Ogontz Avenue', 'Rehab session in progress', 'SCRC Accident & Injury Center'],
  },
  {
    slug: 'zbc-general-contracting',
    archetype: 'build-blocks',
    name: 'ZBC General Contracting',
    short: 'ZBC Contracting',
    schema: 'GeneralContractor',
    url: 'https://www.zbccontracting.com/',
    tel: '267-688-9024',
    address: '447 Roxborough Avenue, Philadelphia, PA 19128',
    city: 'Greater Philadelphia Area',
    eyebrow: 'Interior and exterior remodeling',
    headline: 'Your trusted Philadelphia area general contractor',
    sub: 'ZBC specializes in top quality interior and exterior remodeling and renovations throughout the Greater Philadelphia Area. Small repair or full renovation.',
    ctaPrimary: 'Call 267-688-9024',
    ctaSecondary: 'About us',
    proof: [['Interior', 'And exterior'], ['Roxborough Ave', '447'], ['Greater Philly', 'Service area'], ['Any size', 'Repair to renovation']],
    services: [
      ['Kitchens', 'Full kitchen remodels from demo through final trim.'],
      ['Bathrooms', 'Bathroom renovations done by one crew start to finish.'],
      ['Flooring and basements', 'Flooring, basements, and the spaces people forget to finish.'],
      ['Decks, porches and sunrooms', 'Decks, porches, sunrooms, pools and ponds.'],
      ['Masonry and hardscaping', 'Masonry, hardscaping, fences, sheds and garages.'],
      ['Repairs and prep for sale', 'Repairs, preventive maintenance and prep for sale.'],
    ],
    story: {
      title: 'Our mission',
      body: 'To provide our customers with the highest quality work at a fair price. ZBC General Contracting specializes in top quality interior and exterior remodeling and renovations throughout the Greater Philadelphia Area. Whether you have a small repair or a full renovation, we handle it the same way.',
    },
    feature: { title: "I treat every job as if I'm doing it for my parents", body: 'That is the standard the owner holds the crew to, and it is the reason the referral list is what it is. For all your home repair, remodeling and renovation needs.' },
    quote: { text: "I treat every job as if I'm doing it for my parents.", who: 'ZBC General Contracting' },
    hours: [['Mon', '7:00am - 5:00pm'], ['Tue', '7:00am - 5:00pm'], ['Wed', '7:00am - 5:00pm'], ['Thu', '7:00am - 5:00pm'], ['Fri', '7:00am - 5:00pm'], ['Sat', 'By appointment']],
    links: [['About us', '#story'], ['Kitchens', '#services'], ['Bathrooms', '#services'], ['Repairs and maintenance', '#services']],
    closing: 'For all your home repair, remodeling and renovation needs. Call 267-688-9024.',
    tokens: { paper: '#F5E9A5', ink: '#022E59', accent: '#022E59', accent2: '#C8892A', panel: '#DAD5D9', deep: '#04223F' },
    alts: ['Kitchen remodel by ZBC General Contracting', 'Bathroom renovation in progress', 'Exterior remodeling work', 'Finished interior renovation', 'Deck and porch construction', 'ZBC General Contracting'],
  },
];

for (const s of sites) {
  s.images = IMAGES.slice();
  s.logo = 'assets/logo.png';
  s.logoTone = (TONE[s.slug] && TONE[s.slug].tone) || 'dark';
  const x = EXPANDED[s.slug];
  if (x) {
    if (x.services) s.services = x.services;
    if (x.story) s.story.body = x.story;
    if (x.feature) s.feature.body = x.feature;
  }
  if (!s.alts) s.alts = IMAGES.map((_, i) => `${s.name} in ${s.city}`);
}

module.exports = { sites, IMAGES };
