'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { spawnSync } = require('child_process');

const HERE = path.resolve(__dirname, '..');
const TREAT = path.join(HERE, 'treat.py');

function writePng(dest, r, g, b) {
  // Tiny valid 64x80 PNG generated by Python so we do not add a PNG encoder here.
  const py = `
from PIL import Image
im = Image.new("RGB", (64, 80), (${r}, ${g}, ${b}))
im.save(${JSON.stringify(dest)})
`;
  const res = spawnSync('python3', ['-c', py], { encoding: 'utf8' });
  if (res.status !== 0) throw new Error(res.stderr || 'png write failed');
}

test('treat.py maps two seeds to two hashes and raises local variance', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'unslop-treat-'));
  const src = path.join(dir, 'src.png');
  const a = path.join(dir, 'a.webp');
  const b = path.join(dir, 'b.webp');
  writePng(src, 118, 92, 74);
  const tokens = '#C2410C,#1A1410,#2A1810,#F4EFE7,#E7A843';
  const run = (out, seed) => {
    const res = spawnSync(
      'python3',
      [TREAT, '--in', src, '--out', out, '--tokens', tokens, '--seed', seed],
      { encoding: 'utf8' }
    );
    assert.equal(res.status, 0, res.stderr || res.stdout);
  };
  run(a, 'narberth-pizza-1');
  run(b, 'kehans-auto-service-1');
  const ha = crypto.createHash('sha256').update(fs.readFileSync(a)).digest('hex');
  const hb = crypto.createHash('sha256').update(fs.readFileSync(b)).digest('hex');
  assert.notEqual(ha, hb);
  const py = `
import numpy as np
from PIL import Image
src = np.array(Image.open(${JSON.stringify(src)}).convert("RGB"))
out = np.array(Image.open(${JSON.stringify(a)}).convert("RGB"))
s = (0.2126*src[...,0]+0.7152*src[...,1]+0.0722*src[...,2]).std()
o = (0.2126*out[...,0]+0.7152*out[...,1]+0.0722*out[...,2]).std()
print(s, o)
`;
  const stats = spawnSync('python3', ['-c', py], { encoding: 'utf8' });
  assert.equal(stats.status, 0, stats.stderr);
  const [srcStd, outStd] = stats.stdout.trim().split(/\s+/).map(Number);
  assert.ok(outStd > srcStd, `expected treated std ${outStd} > flat src ${srcStd}`);
  fs.rmSync(dir, { recursive: true, force: true });
});
