#!/usr/bin/env node
/**
 * Rewrite all 25 briefs as forward-facing local sites:
 * real logos when present, imagined-but-plausible homepage copy,
 * mapped to the 15 shown wow shots plus 10 more. No em dashes.
 */
const fs = require('fs');
const path = require('path');
const { buildSite } = require('/workspace/_templates/site-factory/build-site.js');
const { fitBriefToMeasuredSpec } = require('/workspace/_templates/site-factory/brief-from-harvest.js');

const BATCH = path.join(__dirname, '..');
const SITES = path.join(BATCH, 'sites');

const MAP = {
  'andorra-family-dentistry': 'https://stripe.com',
  'eisenberg-rothweiler-winkler-eisenberg-and-jeck-p-c': 'https://www.apple.com',
  'mt-airy-pediatrics-p-c': 'https://www.airbnb.com',
  'be-balanced-hormone-weight-loss-centers': 'https://arc.net',
  'go2tech': 'https://webflow.com',
  'maclaren-kitchen-and-bath': 'https://cursor.com',
  'dream-team': 'https://www.figma.com',
  'pennsylvania-dental-group': 'https://linear.app',
  'glen-eagle-pediatric-dentistry': 'https://www.notion.so',
  'colmar-dentistry-for-kids': 'https://godly.website',
  'benjamin-lovell-shoes': 'https://land-book.com',
  'frederick-w-oster-fine-violins': 'https://www.pentagram.com/work',
  'metalmorphose-iron-studio': 'https://studiofreight.com',
  'davidson-fabricating-inc': 'https://www.awwwards.com/websites/architecture',
  'plastic-surgery-solutions': 'https://www.midjourney.com',
  'always-dental-care': 'https://www.spotify.com',
  'smile-culture-dental': 'https://www.raycast.com',
  'live-urgent-care': 'https://www.cosmos.so',
  'dutton-road-veterinary-clinic': 'https://www.shopify.com',
  'floral-and-hardy': 'https://clerk.com',
  'salter-s-fireplace-and-outdoor-living': 'https://www.framer.com',
  'philadelphia-garage': 'https://github.com',
  'southampton-hot-tub': 'https://www.anthropic.com',
  'elverson-supply': 'https://cal.com',
  'dreammaker-bath-and-kitchen': 'https://resend.com',
};

const COPY = {
  'andorra-family-dentistry': {
    eyebrow: 'Andorra, Philadelphia',
    headline: 'Family dentistry on Ridge Avenue',
    sub: 'Dr. Shah, Dr. Emani, and Dr. Bansal take care of kids, parents, and grandparents in one office. Call when you want a cleaning, a repair, or a calmer first visit.',
    cta: 'Call the office',
    offerings: ['Cleanings and exams', 'Veneers and whitening', 'Implants and restorations'],
    proof: ['Dentists you can name', 'Ridge Avenue, Suite 9', 'Andorra and Roxborough', 'Same-day emergency care'],
    storyH: 'A practice that knows your name',
    story: [
      'Our team focuses on comfortable visits and a full range of care, from a first cleaning to implants and Invisalign. People come from Andorra, Conshohocken, Lafayette Hill, and Roxborough.',
      'You will see digital scans, clear explanations, and a plan you can follow. Bring the whole family. We will make room.',
    ],
    experience: ['Book from your phone', 'See the room before you sit', 'Talk to a person, not a form'],
    featureH: 'A smile you will actually show',
    feature: 'Cosmetic work here is practical: bonding, veneers, whitening, and clear aligners when they fit. We start with what you want to change, then pick the smallest step that gets you there.',
    spotH: 'Close to home in Andorra',
    spot: 'The office sits at 8919 Ridge Avenue. Park, walk in, and tell us what is bothering you. We will tell you what we can do today.',
    contactH: 'Come see us on Ridge Avenue',
    contact: 'Phone and address are on this page so you can act without hunting. Confirm hours on the official site before you drive.',
    close: 'Ready when you are',
  },
  'pennsylvania-dental-group': {
    eyebrow: 'University City',
    headline: 'Dental care that keeps up with your week',
    sub: 'Pennsylvania Dental Group sees students, faculty, and neighbors around Market Street. Come in for a cleaning, a crown, or a problem that will not wait.',
    cta: 'Call Market Street',
    offerings: ['Preventive cleanings', 'Crowns and bridges', 'Emergency visits'],
    proof: ['Market Street office', 'Phone on the homepage', 'Built for a busy calendar', 'One clear next step'],
    storyH: 'A city practice with a steady hand',
    story: [
      'You should not need a map to find the dentist. We keep the phone, the address, and the reason to visit in one place.',
      'Tell us what hurts, what you want to protect, and how soon you can come in. We will meet you there.',
    ],
    experience: ['Call before you commute', 'See the office on your phone', 'Leave with a plan'],
    featureH: 'Care that fits a campus day',
    feature: 'University City moves fast. We keep visits focused so you can get back to class, work, or the train.',
    spotH: '3700 Market Street',
    spot: 'Suite 101 is easy to reach. Bring your questions. We will keep the visit straightforward.',
    contactH: 'Book the next visit',
    contact: 'Use the number on this page or confirm details on the official site.',
    close: 'See you on Market Street',
  },
  'glen-eagle-pediatric-dentistry': {
    eyebrow: 'Glen Mills',
    headline: 'Dentistry built for kids, not for waiting rooms',
    sub: 'Glen Eagle Pediatric Dentistry helps children through first visits, cleanings, and the days that feel scary. Parents stay in the loop the whole time.',
    cta: 'Call for kids',
    offerings: ['First visits', 'Cleanings and sealants', 'Gentle repairs'],
    proof: ['Pediatric focus', 'Glen Mills office', 'Parents stay involved', 'Calm, clear visits'],
    storyH: 'A first dentist they will come back to',
    story: [
      'Kids remember how a visit felt. We keep the room calm, the words simple, and the work careful.',
      'Parents get a plain explanation before anything starts. No surprises, no rush.',
    ],
    experience: ['Prep your child at home', 'Stay in the room', 'Leave with home care that makes sense'],
    featureH: 'Small mouths, careful work',
    feature: 'Sealants, cleanings, and repairs are paced for children. We would rather go slow than scare someone out of coming back.',
    spotH: 'Wilmington West Chester Pike',
    spot: 'The Glen Mills office is set up for families. Call ahead if your child is nervous. We will make time.',
    contactH: 'Schedule a kid visit',
    contact: 'Phone and address are listed so you can book without a scavenger hunt.',
    close: 'Bring them in',
  },
  'davidson-fabricating-inc': {
    eyebrow: 'West Chester',
    headline: 'Steel that holds the building up',
    sub: 'Davidson Fabricating cuts, welds, and delivers structural work for jobs that cannot guess. Call when the drawings are ready.',
    cta: 'Call the shop',
    offerings: ['Structural steel', 'Custom fabrication', 'Job-site delivery'],
    proof: ['Hagerty Boulevard shop', 'West Chester, PA', 'Built for contractors', 'Drawings in, steel out'],
    storyH: 'A shop that reads the print',
    story: [
      'We fabricate what the job needs, not a catalog page. Send the drawings. We will tell you what we can run and when.',
      'Contractors come back because the pieces fit and the phone gets answered.',
    ],
    experience: ['Send the drawings', 'Walk the shop if you need to', 'Get a date you can plan around'],
    featureH: 'Fabrication you can schedule',
    feature: 'Lead times stay honest. If a piece will slip, you hear it from us before the job feels it.',
    spotH: '11 Hagerty Boulevard',
    spot: 'The West Chester shop is where the work happens. Come by when you want to see the floor, not a brochure.',
    contactH: 'Talk to the shop',
    contact: 'Call with the job name and what you need fabricated. We will take it from there.',
    close: 'Send the drawings',
  },
  'dream-team': {
    eyebrow: 'Lansdowne',
    headline: 'Heat, air, and a crew that shows up',
    sub: 'Dream Team keeps houses in Lansdowne comfortable when the weather will not cooperate. Call for a repair, a tune-up, or a system that has had enough.',
    cta: 'Call Dream Team',
    offerings: ['Heating repair', 'Air conditioning', 'System replacements'],
    proof: ['Lansdowne crew', 'S. Lansdowne Avenue', 'Houses, not showrooms', 'Phone first'],
    storyH: 'The truck you wanted yesterday',
    story: [
      'When the house is too hot or too cold, you want a person who will come over and fix it. That is the job.',
      'We keep the conversation plain: what failed, what it costs, and when we can be there.',
    ],
    experience: ['Call with the symptom', 'Get a window, not a maybe', 'See the work before you pay'],
    featureH: 'Repair first, replace when you must',
    feature: 'We would rather fix a system that still has life than sell you a new one. If replacement is the honest answer, you will hear why.',
    spotH: '436 S. Lansdowne Avenue',
    spot: 'Local houses, local trucks. If you can describe the noise, we can usually guess the part.',
    contactH: 'Get a tech on the way',
    contact: 'Call the number on this page. Tell us the town and what the system is doing.',
    close: 'We will come to the house',
  },
  'eisenberg-rothweiler-winkler-eisenberg-and-jeck-p-c': {
    eyebrow: 'Spruce Street, Philadelphia',
    headline: 'Trial lawyers who take the case personally',
    sub: 'Eisenberg, Rothweiler, Winkler, Eisenberg & Jeck represent people who got hurt and need a firm that will stand in court, not just send a letter.',
    cta: 'Call the firm',
    offerings: ['Personal injury', 'Trial work', 'Client-first counsel'],
    proof: ['1634 Spruce Street', 'Philadelphia trial firm', 'Named partners', 'One conversation to start'],
    storyH: 'A firm built for the courtroom',
    story: [
      'You should know who is handling your case. Our name is on the door because the work is ours.',
      'Bring the facts. We will tell you if we can help, and we will not waste your time if we cannot.',
    ],
    experience: ['Tell us what happened', 'Meet the lawyer, not a script', 'Get a clear yes or no'],
    featureH: 'Counsel you can reach',
    feature: 'Injury work is personal. We keep the file close and the updates human so you are never guessing what happens next.',
    spotH: 'Center City office',
    spot: 'The Spruce Street office is where we meet clients. Call first so we can make time.',
    contactH: 'Start with a call',
    contact: 'Use the phone on this page. Have the date, the place, and what you have already been told.',
    close: 'Tell us what happened',
  },
  'frederick-w-oster-fine-violins': {
    eyebrow: 'South Broad Street',
    headline: 'Violins chosen with a player in mind',
    sub: 'Frederick W. Oster Fine Violins has served Philadelphia musicians who need an instrument that sounds like them. Come play before you decide.',
    cta: 'Visit the shop',
    offerings: ['Fine violins', 'Bows and fittings', 'Sales and service'],
    proof: ['507 South Broad Street', 'Philadelphia shop', 'Play before you buy', 'Instruments, not posters'],
    storyH: 'A shop for people who listen',
    story: [
      'You cannot judge a violin from a photo. Come in, play, and listen in the room.',
      'We help students, professionals, and families who want the next instrument to last.',
    ],
    experience: ['Book a play-in', 'Compare two instruments', 'Leave with a sound you chose'],
    featureH: 'The room does the selling',
    feature: 'We keep the talk short so you can hear the instrument. If it is not right, we will say so.',
    spotH: 'Broad Street, Philadelphia',
    spot: 'The shop is on South Broad. Call ahead if you want a quiet hour with a few instruments out.',
    contactH: 'Come play something',
    contact: 'Address and phone are here. Confirm hours on the official site before you travel.',
    close: 'Bring your bow',
  },
  'smile-culture-dental': {
    eyebrow: 'Huntingdon Valley',
    headline: 'A dental visit that feels current',
    sub: 'Smile Culture Dental on County Line Road keeps cleanings, cosmetics, and everyday repairs in one modern office. Book when the calendar opens.',
    cta: 'Call Smile Culture',
    offerings: ['Family dentistry', 'Cosmetic care', 'Same-week visits'],
    proof: ['Huntingdon Valley', 'County Line Road', 'Modern chairs', 'Phone on the page'],
    storyH: 'Culture is how the visit feels',
    story: [
      'People stay with a dentist who explains the work and respects the clock. That is the bar.',
      'Come in for a cleaning or a change you have been putting off. We will show you the options in plain language.',
    ],
    experience: ['Text or call to book', 'See the plan on a screen', 'Leave knowing the next date'],
    featureH: 'Cosmetic work without the sales pitch',
    feature: 'Whitening, aligners, and repairs are on the menu. We will tell you what is worth it for your mouth, not for a monthly special.',
    spotH: '2150 E County Line Road',
    spot: 'Huntingdon Valley is easy to reach. Park, check in, and we will take it from there.',
    contactH: 'Reserve a chair',
    contact: 'Call the office or confirm on the official site if you already have a portal login.',
    close: 'Your next cleaning is waiting',
  },
  'be-balanced-hormone-weight-loss-centers': {
    eyebrow: 'Collegeville',
    headline: 'Hormone care with a plan you can keep',
    sub: 'Be Balanced in Collegeville helps people who are tired of guessing. Come in, get a read on what is going on, and leave with a program that fits your week.',
    cta: 'Call Collegeville',
    offerings: ['Hormone programs', 'Weight-loss support', 'Follow-up visits'],
    proof: ['519 Main Street', 'Collegeville, PA', 'Local center', 'A program, not a pitch'],
    storyH: 'Balance you can measure',
    story: [
      'Energy, sleep, and weight are connected. We start with your story and the labs, then build a plan you can actually follow.',
      'You will know what we are changing and why. No mystery packets.',
    ],
    experience: ['Tell us the symptoms', 'Review the plan together', 'Check in as you go'],
    featureH: 'A center on Main Street',
    feature: 'Collegeville should not need a drive to the city for this kind of care. We keep the visits local and the instructions written down.',
    spotH: '519 Main Street',
    spot: 'Walk in when you have an appointment. Bring a list of what you have already tried.',
    contactH: 'Start the conversation',
    contact: 'Call the Collegeville center. We will tell you what the first visit includes.',
    close: 'Come in as you are',
  },
  'plastic-surgery-solutions': {
    eyebrow: 'Sanatoga',
    headline: 'Surgery decisions made in good light',
    sub: 'Plastic Surgery Solutions in Sanatoga is for people who want a careful consult, honest limits, and a result that still looks like them.',
    cta: 'Request a consult',
    offerings: ['Consultations', 'Surgical care', 'Follow-through visits'],
    proof: ['Heritage Drive, Sanatoga', 'Named practice', 'Consult first', 'Photos of real work'],
    storyH: 'A consult before a commitment',
    story: [
      'You should hear what is possible and what is not before anyone books a date. We keep that conversation unhurried.',
      'Bring photos of what you like. We will talk about anatomy, recovery, and whether surgery is the right tool.',
    ],
    experience: ['Book the consult', 'See comparable work', 'Decide with the lights on'],
    featureH: 'Results that still look like you',
    feature: 'The goal is a change you can live with in daylight, not a trend. We will decline work that will not age well.',
    spotH: '900 Heritage Drive',
    spot: 'Suite 920 in Sanatoga. Call ahead so we can set aside time for a real consult.',
    contactH: 'Talk before you book',
    contact: 'Use the phone on this page. Have your questions written down.',
    close: 'Start with a consult',
  },
  'live-urgent-care': {
    eyebrow: 'King of Prussia',
    headline: 'Urgent care when the day goes sideways',
    sub: 'Live Urgent Care on Town Center Road is for the sprain, the fever, the cut, and the thing that cannot wait for a Tuesday physical.',
    cta: 'Get directions',
    offerings: ['Walk-in visits', 'Illness and injury', 'On-site testing'],
    proof: ['King of Prussia', 'Town Center Road', 'Open for the unexpected', 'Phone listed'],
    storyH: 'A clinic for the unplanned',
    story: [
      'You do not plan an urgent care visit. You just need the door to be open and the staff to move.',
      'Tell us what started, when it started, and what you have already taken. We will take it from there.',
    ],
    experience: ['Check the hours', 'Walk in or call first', 'Leave with next steps'],
    featureH: 'King of Prussia, same day',
    feature: 'We handle the problems that show up after work and on weekends. If you need the ER instead, we will say so.',
    spotH: '107 Town Center Road',
    spot: 'Easy to find in King of Prussia. Bring an ID and a short list of medications.',
    contactH: 'Come in today',
    contact: 'Confirm hours on the official site, then head over. The address is on this page.',
    close: 'We will see you shortly',
  },
  'floral-and-hardy': {
    eyebrow: 'Skippack',
    headline: 'Plants, pots, and a yard that looks loved',
    sub: 'Floral and Hardy on Skippack Pike is the garden center you drive to when you want something alive, not a plastic bouquet.',
    cta: 'Visit Skippack',
    offerings: ['Seasonal plants', 'Garden supplies', 'Local advice'],
    proof: ['4007 Skippack Pike', 'Skippack, PA', 'A real greenhouse', 'Ask before you buy'],
    storyH: 'A garden center with dirt under the nails',
    story: [
      'We grow and stock what does well here, then tell you how to keep it alive. That is the whole offer.',
      'Come walk the benches. If you are unsure, ask. We would rather send you home with the right plant.',
    ],
    experience: ['Walk the benches', 'Ask what survives here', 'Load the car once'],
    featureH: 'Skippack Pike, in season',
    feature: 'The mix changes with the weather. Spring is busy. Fall is for the people who plan. Winter still has something green if you ask.',
    spotH: '4007 Skippack Pike',
    spot: 'Park, wander, and leave with more than you meant to. That is a good day here.',
    contactH: 'Come walk the benches',
    contact: 'Confirm hours before you drive. The address is on this page.',
    close: 'Bring the wagon',
  },
  'salter-s-fireplace-and-outdoor-living': {
    eyebrow: 'Eagleville',
    headline: 'Fireplaces and the rooms they warm',
    sub: 'Salter\'s Fireplace & Outdoor Living on Ridge Pike helps you pick a hearth you will actually use, then installs it so the house stays safe.',
    cta: 'Call Salter\'s',
    offerings: ['Fireplaces', 'Outdoor living', 'Service and install'],
    proof: ['3076 Ridge Pike', 'Eagleville, PA', 'Showroom you can walk', 'Installers on staff'],
    storyH: 'A showroom, then a clean install',
    story: [
      'You should see the unit in person before anyone cuts a hole in your wall. Come to Ridge Pike and stand in front of a few.',
      'We handle the install and the service after. One shop, one phone number.',
    ],
    experience: ['Walk the showroom', 'Pick fuel and style', 'Schedule the install'],
    featureH: 'Outdoor rooms that get used',
    feature: 'Patios fail when the fire is an afterthought. We plan the hearth with the seating so you stay outside longer.',
    spotH: 'Ridge Pike, Eagleville',
    spot: 'The showroom is easy to find. Call if you want a quieter hour to look.',
    contactH: 'See it before you buy',
    contact: 'Phone and address are listed. Confirm hours on the official site.',
    close: 'Come stand in front of one',
  },
  'go2tech': {
    eyebrow: 'Springfield',
    headline: 'IT help that answers the phone',
    sub: 'GO2Tech keeps Springfield offices running: the network, the backups, the machine that froze before a meeting. Call when it cannot wait.',
    cta: 'Call GO2Tech',
    offerings: ['Managed IT', 'Repairs', 'Network and backup'],
    proof: ['Baltimore Pike', 'Springfield, PA', 'Local techs', 'A human on the line'],
    storyH: 'Support you can reach',
    story: [
      'Technology should not be a mystery invoice. We tell you what broke, what we did, and how to keep it from happening again.',
      'Offices in Delaware County call us because we show up and we explain the work.',
    ],
    experience: ['Describe the outage', 'Get a tech assigned', 'See the fix in writing'],
    featureH: 'Prevent the next outage',
    feature: 'Backup and monitoring are boring until the day they save the week. We will tell you what you are missing.',
    spotH: '606 Baltimore Pike',
    spot: 'Springfield is home base. We come to you when the office cannot come to us.',
    contactH: 'Get a tech on it',
    contact: 'Call with the business name and what stopped working. We will take the ticket.',
    close: 'We will get you back online',
  },
  'metalmorphose-iron-studio': {
    eyebrow: 'Kennett Square',
    headline: 'Ironwork with a maker\'s fingerprint',
    sub: 'Metalmorphose Iron Studio builds rails, gates, and custom pieces you can see from the street. Call when you want metal that looks considered.',
    cta: 'Call the studio',
    offerings: ['Custom ironwork', 'Rails and gates', 'Studio pieces'],
    proof: ['Cannery Road studio', 'Kennett Square', 'Handmade, not catalog', 'See the shop'],
    storyH: 'A studio, not a warehouse',
    story: [
      'We draw, forge, and finish in one place. You can watch the work if you want to understand the timeline.',
      'Bring a photo, a measurement, and the feeling you want at the front door. We will answer with a sketch.',
    ],
    experience: ['Share the opening size', 'Review a sketch', 'See it in steel'],
    featureH: 'Iron that belongs on the house',
    feature: 'The best rail looks like it grew there. We match the line of the stairs and the color of the brick, then we get out of the way.',
    spotH: '1296 Cannery Road',
    spot: 'The Kennett Square studio is where the heat is. Call before you visit so someone is at the door.',
    contactH: 'Start with a sketch',
    contact: 'Call with the project and a few photos. We will tell you if it is a fit.',
    close: 'Let\'s make the gate',
  },
  'benjamin-lovell-shoes': {
    eyebrow: 'Chestnut Street',
    headline: 'Shoes you can walk Philadelphia in',
    sub: 'Benjamin Lovell Shoes on Chestnut Street is for people who want comfort that still looks like a choice. Come try the pair on.',
    cta: 'Visit Chestnut Street',
    offerings: ['Everyday shoes', 'Fit help', 'Brands you can feel'],
    proof: ['1728 Chestnut Street', 'Philadelphia', 'Fit before you buy', 'A store, not a warehouse'],
    storyH: 'A shoe store that still fits you',
    story: [
      'Size is a starting point. We watch you walk and tell you when a pair is lying to you.',
      'Come in with the shoes that already hurt. We will use that information.',
    ],
    experience: ['Tell us where it hurts', 'Try two lasts', 'Walk the aisle before you pay'],
    featureH: 'Chestnut Street, in person',
    feature: 'Photos flatten a shoe. The last, the leather, and the way it flexes only show up when you stand in it.',
    spotH: '1728 Chestnut Street',
    spot: 'Center City is easy to reach. Bring the socks you actually wear.',
    contactH: 'Come try a pair',
    contact: 'Confirm hours on the official site. The address is on this page.',
    close: 'Walk in, walk out better',
  },
  'southampton-hot-tub': {
    eyebrow: 'Hot tubs, local',
    headline: 'A spa you will use in January',
    sub: 'Southampton Hot Tub helps you pick a tub that fits the deck, the power, and the way you actually relax. Come see them in person.',
    cta: 'See the tubs',
    offerings: ['Hot tubs', 'Delivery and setup', 'Service after'],
    proof: ['Local showroom', 'See it running', 'Service after the sale', 'Ask about power'],
    storyH: 'Buy the tub you will sit in',
    story: [
      'A hot tub is a weekend habit or it is an expensive lid. We help you pick one you will keep uncovered.',
      'We talk about pads, breakers, and winter covers before anyone quotes a pretty picture.',
    ],
    experience: ['Sit in a display', 'Check the electrical', 'Plan the crane or the path'],
    featureH: 'Setup is the real product',
    feature: 'Delivery day is when most regrets start. We plan the path, the pad, and the first fill so you are soaking that night.',
    spotH: 'Come see them running',
    spot: 'Call before you drive so we can confirm the showroom hours. Street address is confirmed on the official site when it is posted.',
    contactH: 'Talk through the deck',
    contact: 'Call with photos of the yard and the breaker panel. We will tell you what will fit.',
    close: 'Leave the lid off',
  },
  'maclaren-kitchen-and-bath': {
    eyebrow: 'West Chester',
    headline: 'Kitchens and baths built in the shop',
    sub: 'MacLaren Kitchen and Bath on Phoenixville Pike fabricates the cabinets and surfaces you live with every morning. Come see the work before you pick a finish.',
    cta: 'Call MacLaren',
    offerings: ['Kitchen cabinetry', 'Bath vanities', 'Shop fabrication'],
    proof: ['West Chester shop', 'Phoenixville Pike', 'Built here', 'See a finished job'],
    storyH: 'A fabricator, not a showroom chain',
    story: [
      'We build in West Chester. You can see how a door is made and how a finish is applied before you sign.',
      'Bring the drawings or the messy kitchen photos. We will tell you what is worth changing.',
    ],
    experience: ['Walk a finished kitchen', 'Pick the door style', 'Get a shop date'],
    featureH: 'The shop is the proof',
    feature: 'Catalog photos hide the joints. Come look at a real box, a real drawer, and a finish under shop lights.',
    spotH: '1135 Phoenixville Pike',
    spot: 'West Chester is home. Call so someone can pull samples for the visit.',
    contactH: 'Start in the shop',
    contact: 'Phone and address are on this page. Bring measurements if you have them.',
    close: 'Let\'s open a door',
  },
  'philadelphia-garage': {
    eyebrow: 'Garage floors, done once',
    headline: 'A garage you can park on and live with',
    sub: 'Philadelphia Garage coats and finishes floors so the space works for cars, tools, and the overflow from the house. Call for a look at your slab.',
    cta: 'Request a look',
    offerings: ['Floor coatings', 'Prep and repair', 'Clean handoff'],
    proof: ['Local crew', 'Prep is the job', 'Photos of real slabs', 'One project at a time'],
    storyH: 'The floor is the room',
    story: [
      'A pretty coat on a dirty slab fails. We talk about prep, moisture, and what you park on it before we talk color.',
      'You will know how long the car lives in the driveway. We keep that timeline honest.',
    ],
    experience: ['Send slab photos', 'Hear the prep plan', 'Park when we say you can'],
    featureH: 'Prep you can trust',
    feature: 'Most failures start with skipped grind work. We will not skip it to win a cheaper bid.',
    spotH: 'We come to the garage',
    spot: 'Street address is confirmed on the official site when the listing is complete. Call and we will meet you at the house.',
    contactH: 'Show us the slab',
    contact: 'Call with photos and the town. We will tell you if the floor is ready.',
    close: 'Let\'s see the concrete',
  },
  'elverson-supply': {
    eyebrow: 'Elverson',
    headline: 'The hardware run that still works',
    sub: 'Elverson Supply on East Main Street is the counter you walk up to when you need the part today, not a tracking number.',
    cta: 'Call the counter',
    offerings: ['Hardware', 'Job supplies', 'Local counter help'],
    proof: ['101 East Main Street', 'Elverson, PA', 'A real counter', 'Ask for the part'],
    storyH: 'A supply house with a memory',
    story: [
      'We know the jobs around here. Tell us the brand on the box and we will find the piece that matches.',
      'Contractors and homeowners use the same counter. Everyone gets the same honest answer about what is in stock.',
    ],
    experience: ['Call ahead for the part', 'Pick up on Main Street', 'Get the matching piece'],
    featureH: 'In stock beats overnight',
    feature: 'If we have it, you can have it this afternoon. If we do not, we will say so and tell you the next move.',
    spotH: '101 East Main Street',
    spot: 'Elverson is small enough that you will not miss the door. Come in with the old part in your hand.',
    contactH: 'Ask the counter',
    contact: 'Call with the part number or a photo. We will check the shelf.',
    close: 'Bring the old part',
  },
  'dreammaker-bath-and-kitchen': {
    eyebrow: 'Chester Springs',
    headline: 'Remodels you can cook and bathe in',
    sub: 'DreamMaker Bath & Kitchen in Chester Springs plans the rooms you use every day, then builds them so the next decade feels easy.',
    cta: 'Start a remodel',
    offerings: ['Kitchen remodels', 'Bath remodels', 'Design and build'],
    proof: ['Pottstown Pike', 'Chester Springs', 'Design, then build', 'A project manager'],
    storyH: 'A remodel with a sequence',
    story: [
      'Kitchens fail when the plan skips how you cook. Baths fail when the tile wins and the storage loses. We start with how you live.',
      'You will know the order of work and who to call when a question shows up at 7 a.m.',
    ],
    experience: ['Walk the current rooms', 'Lock the plan', 'Live through the build with a point person'],
    featureH: 'Chester County, start to finish',
    feature: 'We stay on the job after the pretty photos. Punch lists get closed. You should not hunt a sub for a missing stop.',
    spotH: '12 Pottstown Pike',
    spot: 'Chester Springs is the office. Come in with the rooms you cannot stand anymore.',
    contactH: 'Talk through the rooms',
    contact: 'Call to set a design visit. Bring photos and a sense of what you will not compromise on.',
    close: 'Let\'s open the walls on purpose',
  },
  'dutton-road-veterinary-clinic': {
    eyebrow: 'Northeast Philadelphia',
    headline: 'Vet care on Dutton Road',
    sub: 'Dutton Road Veterinary Clinic looks after the dogs and cats who live in the Northeast. Call when something feels off, or when it is time for the yearly visit.',
    cta: 'Call the clinic',
    offerings: ['Wellness visits', 'Sick pets', 'Local clinic care'],
    proof: ['10901 Dutton Road', 'Philadelphia, PA 19154', 'Neighborhood clinic', 'Call first'],
    storyH: 'A clinic the neighborhood already knows',
    story: [
      'You want a vet who has seen your pet before the emergency. We keep the visits steady so the scary days are easier.',
      'Bring the questions you typed into a search bar. We will answer them in the room.',
    ],
    experience: ['Call with the symptom', 'Come in for the exam', 'Leave with home care you understand'],
    featureH: 'Northeast, close to home',
    feature: 'Dutton Road is easy to reach when a pet will not wait. We will tell you if you need an emergency hospital instead.',
    spotH: '10901 Dutton Road',
    spot: 'Park, come in, and tell us what changed. We will take it from there.',
    contactH: 'Call before you load the carrier',
    contact: 'The phone is on this page. Confirm hours on the official site if you are coming after work.',
    close: 'Bring them in',
  },
  'colmar-dentistry-for-kids': {
    eyebrow: 'Montgomeryville',
    headline: 'Dentistry that kids do not dread',
    sub: 'Colmar Dentistry For Kids on Bethlehem Pike is built for first visits, wiggly patients, and parents who want a straight answer.',
    cta: 'Call for kids',
    offerings: ['First visits', 'Cleanings', 'Kid-focused care'],
    proof: ['671 Bethlehem Pike', 'Montgomeryville', 'Kids first', 'Parents stay informed'],
    storyH: 'A kids\' office on purpose',
    story: [
      'The room, the words, and the pace are for children. Parents get the plan in language they can repeat at dinner.',
      'Come early if your child needs time to look around. We would rather start slow.',
    ],
    experience: ['Preview the visit', 'Stay close', 'Leave with a sticker and a plan'],
    featureH: 'Bethlehem Pike, family parking',
    feature: 'The office is set up for car seats and nervous first-timers. Call if you want the quietest slot of the day.',
    spotH: '671 Bethlehem Pike',
    spot: 'Montgomeryville is easy to reach. Bring the favorite stuffed animal. We have seen it all.',
    contactH: 'Book the first visit',
    contact: 'Call the office. Tell us the age and whether this is a first dentist.',
    close: 'They can do this',
  },
  'mt-airy-pediatrics-p-c': {
    eyebrow: 'Mt. Airy',
    headline: 'Pediatrics on Germantown Avenue',
    sub: 'Mt. Airy Pediatrics, P.C. is the neighborhood practice for checkups, sick days, and the questions that show up at 9 p.m. Call the office when you need us.',
    cta: 'Call pediatrics',
    offerings: ['Well visits', 'Sick visits', 'Growing-up care'],
    proof: ['6673 Germantown Avenue', 'Philadelphia 19119', 'Neighborhood pediatrics', 'Call the desk'],
    storyH: 'A practice that grows with them',
    story: [
      'We see children through the ordinary years and the scary ones. You should feel known when you walk in.',
      'Bring the list. We will go through it without making you feel like you overreacted.',
    ],
    experience: ['Call the desk', 'Come in for the visit', 'Leave knowing the after-hours plan'],
    featureH: 'Mt. Airy, close by',
    feature: 'Germantown Avenue is home base. We keep the instructions written so the other parent can follow them too.',
    spotH: '6673 Germantown Avenue',
    spot: 'Park, come upstairs, and tell us what changed since last time.',
    contactH: 'Reach the desk',
    contact: 'Call the office number on this page. Confirm hours if you are coming before school.',
    close: 'We are here for the ordinary days too',
  },
  'always-dental-care': {
    eyebrow: 'Phoenixville',
    headline: 'Dental care you can keep on the calendar',
    sub: 'Always Dental Care on Egypt Road is for cleanings, repairs, and the visit you have been moving to next month. Book it while you are thinking about it.',
    cta: 'Call Always Dental',
    offerings: ['Cleanings', 'Repairs', 'Family visits'],
    proof: ['1570 Egypt Road', 'Phoenixville', 'Suite 210', 'A number you can tap'],
    storyH: 'Always means we will get you in',
    story: [
      'People skip the dentist when booking feels like a project. We keep the phone on the page and the next step obvious.',
      'Come in for the cleaning. Stay for the work you have been postponing. We will sequence it so it fits your month.',
    ],
    experience: ['Tap to call', 'Pick a morning or after work', 'Leave with the next date set'],
    featureH: 'Egypt Road, Suite 210',
    feature: 'Phoenixville patients should not need a downtown trip for everyday dentistry. We keep the visits local and the explanations short.',
    spotH: '1570 Egypt Road',
    spot: 'Suite 210 is easy to find. Call if you want the first or last slot of the day.',
    contactH: 'Put it on the calendar',
    contact: 'Call the office. Tell us if you are new or if you are coming back after a while. Either is fine.',
    close: 'See you on Egypt Road',
  },
};

function hasLogo(slug) {
  const dir = path.join(SITES, slug, 'assets');
  return ['logo.png', 'logo.svg', 'logo.webp', 'logo.jpg'].some((f) => fs.existsSync(path.join(dir, f)));
}

function applyCopy(brief, c) {
  const tel = (brief.phone || '').replace(/\D/g, '');
  const href = tel ? `tel:${tel}` : brief.url || '#visit';
  brief.composition_ref = MAP[brief.slug] || brief.composition_ref;
  brief.layout = brief.composition_ref;
  brief.logo = hasLogo(brief.slug);
  brief.description = c.sub;
  brief.nav = [
    { label: 'Care', href: '#offerings' },
    { label: 'Work', href: '#gallery' },
    { label: 'Visit', href: '#visit' },
  ];
  brief.hero = {
    ...brief.hero,
    eyebrow: c.eyebrow,
    headline: c.headline,
    sub: c.sub,
    ctaPrimary: { label: c.cta, href },
    ctaSecondary: { label: 'See the work', href: '#gallery' },
    glassFloat: { title: brief.city, sub: brief.category },
  };
  brief.offerings = { items: c.offerings, heading: 'What we do <mark>well.</mark>' };
  brief.proof = { items: c.proof };
  brief.story = { heading: c.storyH, paragraphs: c.story, imageIndex: 2 };
  brief.experience = { items: c.experience, heading: 'How a visit goes' };
  brief.feature = {
    heading: c.featureH,
    text: c.feature,
    cta: { label: 'Official site', href: brief.url || href },
    imageIndex: 8,
  };
  brief.spotlight = {
    heading: c.spotH,
    text: c.spot,
    imageIndex: 12,
    cta: { label: 'Plan a visit', href: '#visit' },
  };
  brief.catalog = {
    heading: 'More ways in',
    items: [
      { title: 'Official site', href: brief.url || href, imageIndex: 9 },
      { title: 'What we do', href: '#offerings', imageIndex: 10 },
      { title: 'Visit', href: '#visit', imageIndex: 11 },
    ],
  };
  brief.contact = { heading: c.contactH, sub: c.contact };
  brief.closing = { heading: c.close, cta: { label: c.cta, href } };
  brief.headerCta = { label: c.cta, href };
  return brief;
}

const report = [];
for (const file of fs.readdirSync(path.join(BATCH, 'briefs')).filter((f) => f.endsWith('.json')).sort()) {
  const p = path.join(BATCH, 'briefs', file);
  const brief = JSON.parse(fs.readFileSync(p, 'utf8'));
  const c = COPY[brief.slug];
  if (!c) {
    report.push({ slug: brief.slug, status: 'no-copy' });
    continue;
  }
  applyCopy(brief, c);
  const measured = fitBriefToMeasuredSpec(brief, () => buildSite(brief, SITES));
  fs.writeFileSync(p, JSON.stringify(brief, null, 2) + '\n');
  report.push({
    slug: brief.slug,
    layout: brief.layout,
    logo: brief.logo,
    words: measured.words,
    images: measured.images,
    sections: measured.sections.length,
  });
  console.log(brief.slug, measured.words, 'words', brief.logo ? 'logo' : 'wordmark', brief.composition_ref);
}
fs.writeFileSync(path.join(BATCH, 'forward-copy-report.json'), JSON.stringify(report, null, 2));
