#!/usr/bin/env python3
"""
Slack posting routine for Dillon OS.

Reads pulse-today.md and urgent-replies.md, formats as Slack messages,
and posts to the configured webhooks.

Usage:
  python3 slack-routine.py pulse            # Post daily pulse to Obsidian Vault
  python3 slack-routine.py urgent           # Post urgent replies to Obsidian Vault
  python3 slack-routine.py m360-roundup     # Post weekly roundup to Momentum 360
  python3 slack-routine.py all              # Post pulse + urgent to Obsidian Vault
"""

import json
import sys
import urllib.request
from pathlib import Path
from datetime import datetime

VAULT_ROOT = Path(__file__).resolve().parent.parent
SECRETS_PATH = VAULT_ROOT / ".claude" / "secrets.json"
PULSE_PATH = VAULT_ROOT / "Daily-Briefs" / "pulse-today.md"
URGENT_PATH = VAULT_ROOT / "System" / "urgent-replies.md"
MEMORY_SYNC_PATH = VAULT_ROOT / "System" / "claude-memory-sync.md"


def load_webhooks():
    with open(SECRETS_PATH) as f:
        return json.load(f)["slack_webhooks"]


def post_to_slack(webhook_url, blocks, text_fallback):
    payload = {"text": text_fallback, "blocks": blocks}
    req = urllib.request.Request(
        webhook_url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as resp:
        return resp.status


def chunk_text(text, limit=2900):
    """Slack section blocks cap at 3000 chars. Split on paragraph boundaries."""
    if len(text) <= limit:
        return [text]
    chunks = []
    current = ""
    for paragraph in text.split("\n\n"):
        if len(current) + len(paragraph) + 2 > limit:
            if current:
                chunks.append(current)
            current = paragraph
        else:
            current = f"{current}\n\n{paragraph}" if current else paragraph
    if current:
        chunks.append(current)
    return chunks


def build_pulse_blocks():
    text = PULSE_PATH.read_text()
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"Daily Pulse — {datetime.now().strftime('%A, %B %d')}"},
        },
        {"type": "divider"},
    ]
    for chunk in chunk_text(text):
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": chunk}})
    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f":file_folder: Generated by nightly-client-pulse | {datetime.now().strftime('%Y-%m-%d %H:%M %Z').strip()}"}
            ],
        }
    )
    return blocks, f"Daily Pulse {datetime.now().strftime('%Y-%m-%d')}"


def build_urgent_blocks():
    text = URGENT_PATH.read_text()
    body = text.split("---", 2)[-1] if text.startswith("---") else text
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": ":rotating_light: Urgent Replies Needed"},
        },
        {"type": "divider"},
    ]
    for chunk in chunk_text(body):
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": chunk}})
    return blocks, "Urgent replies queue"


def build_m360_roundup_blocks():
    """Leadership-friendly weekly roundup. Pulls from memory sync."""
    text = MEMORY_SYNC_PATH.read_text()
    body = text.split("---", 2)[-1] if text.startswith("---") else text
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"M360 Weekly Roundup — Week of {datetime.now().strftime('%B %d')}"},
        },
        {"type": "divider"},
    ]
    for chunk in chunk_text(body):
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": chunk}})
    return blocks, f"M360 Roundup {datetime.now().strftime('%Y-%m-%d')}"


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    mode = sys.argv[1]
    webhooks = load_webhooks()

    if mode == "pulse":
        blocks, fallback = build_pulse_blocks()
        post_to_slack(webhooks["obsidian_vault"], blocks, fallback)
        print("Posted pulse to Obsidian Vault.")

    elif mode == "urgent":
        blocks, fallback = build_urgent_blocks()
        post_to_slack(webhooks["obsidian_vault"], blocks, fallback)
        print("Posted urgent replies to Obsidian Vault.")

    elif mode == "m360-roundup":
        blocks, fallback = build_m360_roundup_blocks()
        post_to_slack(webhooks["momentum_360"], blocks, fallback)
        print("Posted M360 roundup to Momentum 360.")

    elif mode == "all":
        blocks, fallback = build_pulse_blocks()
        post_to_slack(webhooks["obsidian_vault"], blocks, fallback)
        blocks, fallback = build_urgent_blocks()
        post_to_slack(webhooks["obsidian_vault"], blocks, fallback)
        print("Posted pulse + urgent to Obsidian Vault.")

    else:
        print(f"Unknown mode: {mode}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
