#!/usr/bin/env python3
"""Draw the dimensional icon tiles for the light theme.

Each icon is a rounded squircle carrying an orange gradient, a soft cast
shadow, a specular highlight across the top, and a white monoline glyph. The
dimension comes from three cheap tricks stacked rather than a fake perspective:
a two stop gradient on the tile, a light band clipped to the top half, and a
1px inner stroke that catches the top edge and fades by the bottom.

Everything is one self contained SVG per icon so a tile drops into a page, a
deck, or a video frame with no filter support required beyond feGaussianBlur.

    python3 icons3d.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE / 'assets' / 'icons3d'
JS = HERE / 'build' / 'icons3d.js'

SIZE = 96          # tile viewBox
R = 28             # corner radius
GLYPH = 'translate(24,24) scale(2)'   # place a 24 unit glyph on the 96 tile

# Monoline glyphs on a 24 unit grid, stroked white over the tile.
GLYPHS = {
    'coverage': """
      <path d="M12 3.2 20.4 6v6.1c0 4.6-3.4 7.6-8.4 8.7-5-1.1-8.4-4.1-8.4-8.7V6z"/>
      <path d="m8.6 11.9 2.4 2.4 4.4-4.6"/>""",
    'rules': """
      <path d="M5.2 3.4h9.1l4.5 4.5v12.7H5.2z"/>
      <path d="M14 3.4v4.7h4.6"/>
      <path d="M8.4 12.4h7M8.4 16.2h4.6"/>""",
    'handoff': """
      <path d="M4.2 9.6A8.2 8.2 0 0 1 19 7.6"/>
      <path d="M19.8 4v3.9h-3.9"/>
      <path d="M19.8 14.4A8.2 8.2 0 0 1 5 16.4"/>
      <path d="M4.2 20v-3.9h3.9"/>""",
    'design': """
      <rect x="3.2" y="4" width="17.6" height="16" rx="2.4"/>
      <path d="M3.2 9h17.6M9.2 9v11"/>
      <path d="m14 16.9 3.4-3.4 1.7 1.7-3.4 3.4-2.2.5z"/>""",
    'connect': """
      <circle cx="6" cy="6" r="2.8"/>
      <circle cx="18" cy="6" r="2.8"/>
      <circle cx="12" cy="18.4" r="2.8"/>
      <path d="M7.9 8.1 10.4 16M16.1 8.1 13.6 16M8.8 6h6.4"/>""",
    'visible': """
      <path d="M2.6 12S6 5.6 12 5.6 21.4 12 21.4 12 18 18.4 12 18.4 2.6 12 2.6 12z"/>
      <circle cx="12" cy="12" r="3.2"/>""",
    'relevant': """
      <path d="M20.2 12a8.2 8.2 0 1 1-2.6-6"/>
      <path d="M20.6 3.6v5.2h-5.2"/>
      <path d="M12 7.8V12l3 1.8"/>""",
    'trust': """
      <path d="M12 3.2 20.4 6v6.1c0 4.6-3.4 7.6-8.4 8.7-5-1.1-8.4-4.1-8.4-8.7V6z"/>
      <circle cx="12" cy="10.8" r="2.1"/>
      <path d="M8.4 16.6a3.9 3.9 0 0 1 7.2 0"/>""",
    'brain': """
      <path d="M12 4.4v15.2"/>
      <path d="M12 6.6a3 3 0 0 0-5.6-1.2 2.9 2.9 0 0 0-2.1 4.6 3 3 0 0 0 .5 4.5 3 3 0 0 0 4.3 3 3 3 0 0 0 2.9 2"/>
      <path d="M12 6.6a3 3 0 0 1 5.6-1.2 2.9 2.9 0 0 1 2.1 4.6 3 3 0 0 1-.5 4.5 3 3 0 0 1-4.3 3 3 3 0 0 1-2.9 2"/>""",
}


def tile(name, glyph):
    g = ' '.join(glyph.split())
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}">
<defs>
<linearGradient id="{name}-f" x1="0" y1="0" x2="0.35" y2="1">
<stop offset="0" stop-color="#F9A45C"/><stop offset="0.52" stop-color="#F0803A"/><stop offset="1" stop-color="#DE5B22"/>
</linearGradient>
<linearGradient id="{name}-s" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="#fff" stop-opacity="0.55"/><stop offset="1" stop-color="#fff" stop-opacity="0"/>
</linearGradient>
<linearGradient id="{name}-e" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="#fff" stop-opacity="0.85"/><stop offset="0.55" stop-color="#fff" stop-opacity="0.08"/><stop offset="1" stop-color="#8A3410" stop-opacity="0.35"/>
</linearGradient>
<filter id="{name}-d" x="-40%" y="-25%" width="180%" height="180%">
<feDropShadow dx="0" dy="7" stdDeviation="7" flood-color="#C2521C" flood-opacity="0.34"/>
</filter>
</defs>
<g filter="url(#{name}-d)">
<rect x="6" y="4" width="84" height="84" rx="{R}" fill="url(#{name}-f)"/>
<path d="M6 32C6 15 20 4 34 4h28c14 0 28 11 28 28 0 6-12 12-42 12S6 38 6 32z" fill="url(#{name}-s)"/>
<rect x="6.75" y="4.75" width="82.5" height="82.5" rx="{R - 0.75}" fill="none" stroke="url(#{name}-e)" stroke-width="1.5"/>
</g>
<g transform="{GLYPH}" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{g}</g>
</svg>'''


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    table = {}
    for name, glyph in GLYPHS.items():
        svg = tile(name, glyph)
        (OUT / f'{name}.svg').write_text(svg + '\n')
        # inner markup only, so a page can inline it without nesting svg roots
        table[name] = svg.split('>', 1)[1].rsplit('</svg>', 1)[0]
    JS.parent.mkdir(parents=True, exist_ok=True)
    JS.write_text('/* generated by icons3d.py, do not edit */\n'
                  'const ICONS3D = ' + json.dumps(table, indent=0) + ';\n')
    print(f'{len(table)} tiles -> {OUT.relative_to(HERE)}/ and {JS.relative_to(HERE)}')


if __name__ == '__main__':
    main()
