/**
 * Contracts for the web ladder, camofox clone helper, owned-history ingest,
 * and the Claude-agent generator. Run: node --test _os/test/web-stack.test.js
 */
const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const crypto = require('node:crypto');

const VAULT = path.resolve(__dirname, '..', '..');
const AGENTS_DIR = path.join(VAULT, '.claude', 'agents');
const AGENT_NAMES = [
  'marketing-chief',
  'web-product-builder',
  'qa-critic',
  'paid-media-analyst',
  'growth-content',
  'brain-curator',
  'reliability-scout',
];
const GENERATOR = path.join(VAULT, 'System', 'scripts', 'Build-ClaudeAgents.py');
const CLONE = path.join(VAULT, 'System', 'scripts', 'Clone-CamofoxBrowser.py');
const HISTORY = path.join(VAULT, 'System', 'scripts', 'Export-BrowserHistory.py');

function read(rel) {
  return fs.readFileSync(path.join(VAULT, rel), 'utf8');
}

function hashDir(dir) {
  const h = crypto.createHash('sha256');
  for (const name of fs.readdirSync(dir).sort()) {
    if (!name.endsWith('.md')) continue;
    h.update(name);
    h.update(fs.readFileSync(path.join(dir, name)));
  }
  return h.digest('hex');
}

describe('web stack architecture', () => {
  it('documents the generator rule and honest stealth rung in AGENTS.md', () => {
    const agents = read('AGENTS.md');
    assert.match(agents, /Build-ClaudeAgents\.py/);
    assert.match(agents, /FIRECRAWL_BATCH_SCRAPE/);
    assert.match(agents, /earned-lessons\.md/);
    assert.match(agents, /Clone-CamofoxBrowser\.py/);
    assert.match(agents, /Export-BrowserHistory\.py/);
    assert.match(agents, /BRIGHTDATA_API_KEY/);
    assert.match(agents, /playwright-isolated|start-playwright/);
    assert.match(agents, /\.claude\.json/);
    assert.match(agents, /attach_live/);
  });

  it('keeps architecture, decision, and receipt notes', () => {
    for (const rel of [
      '12_Brain/09_Ops/Web Escalation Architecture.md',
      '12_Brain/04_Decisions/2026-08-18 - Local web stack and browser history grant.md',
      '12_Brain/01_Captures/research/2026-08-18 - Firecrawl web capability receipt.md',
      '12_Brain/11_Craft/earned-lessons.md',
      '12_Brain/02_Entities/Firecrawl.md',
      '12_Brain/02_Entities/Camofox Browser.md',
      '12_Brain/02_Entities/Playwright MCP.md',
      '12_Brain/03_Concepts/Web Escalation Ladder.md',
      '12_Brain/03_Concepts/Generated File Drift.md',
      '12_Brain/03_Concepts/Live Process Ownership.md',
      '12_Brain/03_Concepts/MCP Catalog Direction.md',
      '12_Brain/04_Decisions/2026-08-18 - MCP catalogs stay directional.md',
      '12_Brain/01_Captures/research/2026-08-18 - Claude Code MCP catalog verification.md',
    ]) {
      assert.equal(fs.existsSync(path.join(VAULT, rel)), true, rel);
      const text = read(rel);
      assert.match(text, /^---\n/, `${rel} missing frontmatter`);
      assert.match(text, /note_type:/);
      assert.match(text, /source_refs:/);
    }
  });

  it('gitignores vendor clones and private history', () => {
    const gi = read('.gitignore');
    assert.match(gi, /^\.vendor\//m);
    assert.match(gi, /12_Brain\/private\/\*\*/);
  });
});

describe('Claude agent generator', () => {
  it('emits seven agents with ladder, recursion, and local-stack grant', () => {
    for (const name of AGENT_NAMES) {
      const text = fs.readFileSync(path.join(AGENTS_DIR, `${name}.md`), 'utf8');
      assert.match(text, /GENERATED by System\/scripts\/Build-ClaudeAgents\.py/);
      assert.match(text, /FIRECRAWL_BATCH_SCRAPE/);
      assert.match(text, /earned-lessons\.md/);
      assert.match(text, /Clone-CamofoxBrowser\.py/);
      assert.match(text, /Export-BrowserHistory\.py/);
      assert.match(text, /does \*\*not\*\* unlock outbound verbs/);
      assert.match(text, /start-playwright/);
      assert.doesNotMatch(text, /Not cloned locally yet/);
      assert.doesNotMatch(text, /installed, \*\*not live\*\*/);
      assert.doesNotMatch(text, /\| 4 \| Firecrawl with `proxy: "stealth"` \|/);
    }
  });

  it('is idempotent', () => {
    const before = hashDir(AGENTS_DIR);
    execFileSync('python3', [GENERATOR], { cwd: VAULT, encoding: 'utf8' });
    const after = hashDir(AGENTS_DIR);
    assert.equal(after, before);
  });
});

describe('camofox clone helper', () => {
  it('prints a gitignored destination and does not clone into tracked paths', () => {
    const dest = execFileSync('python3', [CLONE, '--print-path'], {
      cwd: VAULT,
      encoding: 'utf8',
    }).trim();
    assert.ok(dest.endsWith('camofox-browser'), dest);
    assert.equal(dest.includes(`${path.sep}11_Agents${path.sep}`), false);
    assert.equal(dest.includes(`${path.sep}12_Brain${path.sep}`), false);
  });
});

describe('browser-access router', () => {
  const CLI = path.join(VAULT, '_os', 'automation', 'bin', 'browser-access.js');

  it('probe records never-9222 and writes regenerable state', () => {
    const raw = execFileSync(process.execPath, [CLI, 'probe'], {
      cwd: VAULT,
      encoding: 'utf8',
    });
    const out = JSON.parse(raw);
    assert.deepEqual(out.never_ports, [9222]);
    assert.equal(out.evidence_port, 9223);
    const ids = out.engines.map((e) => e.id);
    assert.ok(ids.includes('chrome_isolated'));
    assert.ok(ids.includes('camofox'));
    assert.ok(ids.includes('firecrawl'));
    assert.ok(ids.includes('playwright_mcp'));
    assert.equal(out.engines.find((e) => e.id === 'bright_data').live, false);
    const pw = out.engines.find((e) => e.id === 'playwright_mcp');
    if (pw.live) {
      assert.match(pw.detail, /8931/);
      assert.match(pw.detail, /no --extension/);
    }
    const src = read('_os/automation/bin/browser-access.js');
    assert.match(src, /never.*9222/i);
    assert.doesNotMatch(src, /remote-debugging-port=9222/);
    assert.match(src, /EVIDENCE_PORT/);
    assert.match(src, /start-playwright/);
    assert.doesNotMatch(src, /args\.push\('--extension'\)/);
  });

  it('recommend returns job-specific engine order', () => {
    const cloudflare = JSON.parse(execFileSync(process.execPath, [CLI, 'recommend', 'cloudflare'], {
      cwd: VAULT,
      encoding: 'utf8',
    }));
    assert.deepEqual(cloudflare.order, ['firecrawl_stealth', 'camofox', 'playwright_mcp']);
    const logged = JSON.parse(execFileSync(process.execPath, [CLI, 'recommend', 'logged_in'], {
      cwd: VAULT,
      encoding: 'utf8',
    }));
    assert.deepEqual(logged.order, ['claude_in_chrome']);
    const js = JSON.parse(execFileSync(process.execPath, [CLI, 'recommend', 'js_interact'], {
      cwd: VAULT,
      encoding: 'utf8',
    }));
    assert.equal(js.order[0], 'playwright_mcp');
    const policy = JSON.parse(read('System/browser-access.policy.json'));
    assert.deepEqual(policy.never.ports, [9222]);
    assert.equal(policy.chrome.evidence_port, 9223);
    assert.deepEqual(policy.playwright_mcp.never_flags, ['--extension']);
    assert.equal(policy.playwright_mcp.args.includes('--extension'), false);
    assert.equal(policy.jobs.js_interact[0], 'playwright_mcp');
    assert.equal(policy.jobs.screenshot[0], 'playwright_mcp');
  });

  it('fetch of a local file uses isolated Chrome, not 9222', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ba-'));
    const htmlPath = path.join(tmp, 'page.html');
    fs.writeFileSync(htmlPath, '<!doctype html><title>Router Fixture</title><p>ok</p>');
    const profile = path.join(tmp, 'profile');
    const raw = execFileSync(process.execPath, [CLI, 'fetch', `file://${htmlPath}`], {
      cwd: VAULT,
      encoding: 'utf8',
      timeout: 25000,
      env: { ...process.env, BROWSER_EVIDENCE_PROFILE: profile },
    });
    const out = JSON.parse(raw);
    assert.equal(out.engine, 'chrome_isolated');
    assert.equal(out.title, 'Router Fixture');
    assert.equal(String(out.binary).includes('google-chrome') && !String(out.binary).includes('/opt/google/chrome/chrome'), false);
  });

  it('fetch of https uses isolated Playwright MCP, not --extension', () => {
    const raw = execFileSync(process.execPath, [CLI, 'fetch', 'https://example.com'], {
      cwd: VAULT,
      encoding: 'utf8',
      timeout: 25000,
    });
    const out = JSON.parse(raw);
    assert.equal(out.engine, 'playwright_mcp');
    assert.equal(out.title, 'Example Domain');
    assert.match(out.endpoint, /localhost:8931/);
  });
});

describe('owned browser history ingest', () => {
  it('sanitizes titles/domains, drops login paths, and refuses non-private output', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'hist-'));
    const db = path.join(tmp, 'History');
    const out = path.join(tmp, 'out');
    const py = `
import datetime, sqlite3, os
db = os.environ['HIST_DB']
conn = sqlite3.connect(db)
conn.execute('CREATE TABLE urls (id INTEGER PRIMARY KEY, url LONGVARCHAR, title LONGVARCHAR, visit_count INTEGER, typed_count INTEGER, last_visit_time INTEGER, hidden INTEGER DEFAULT 0)')
epoch = datetime.datetime(1601,1,1)
now = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
micro = int((now - epoch).total_seconds() * 1e6)
rows = [
  ('https://example.com/pricing?token=secret', 'Example pricing', 3, micro),
  ('https://accounts.google.com/signin', 'Sign in', 9, micro),
  ('https://bankofamerica.com/login', 'Bank', 2, micro),
  ('https://shadowhvac.example/ac-repair', 'AC repair', 1, micro),
]
conn.executemany('INSERT INTO urls (url,title,visit_count,typed_count,last_visit_time,hidden) VALUES (?,?,?,0,?,0)', rows)
conn.commit()
`;
    execFileSync('python3', ['-c', py], {
      cwd: VAULT,
      env: { ...process.env, HIST_DB: db },
    });

    const exported = execFileSync('python3', [HISTORY, '--db', db, '--out', out, '--days', '14'], {
      cwd: VAULT,
      encoding: 'utf8',
      env: { ...process.env, BROWSER_HISTORY_TEST: '1' },
    });
    assert.match(exported, /rows=/);
    const files = fs.readdirSync(out).filter((f) => f.endsWith('.md'));
    assert.equal(files.length, 1);
    const body = fs.readFileSync(path.join(out, files[0]), 'utf8');
    assert.match(body, /example\.com/);
    assert.match(body, /shadowhvac\.example/);
    assert.doesNotMatch(body, /token=secret/);
    assert.doesNotMatch(body, /accounts\.google\.com/);
    assert.doesNotMatch(body, /bankofamerica/);

    let refused = false;
    try {
      execFileSync('python3', [HISTORY, '--db', db, '--out', path.join(tmp, 'leaked'), '--days', '1'], {
        cwd: VAULT,
        encoding: 'utf8',
        env: { ...process.env, BROWSER_HISTORY_TEST: '' },
      });
    } catch (err) {
      refused = true;
      assert.match(String(err.stderr || err.stdout || err), /refusing to write/);
    }
    assert.equal(refused, true);
  });
});
