#!/usr/bin/env python3
"""Draw the Align HCM service icon set.

One monoline family on a 24 unit grid, 1.7 stroke, round caps and joins, no
fills. Everything is stroked in currentColor so a single file works orange on
navy, white on navy, or ink on cream without a second export.

Writes assets/icons/<name>.svg plus build/icons.js, a plain object of raw path
markup that build.py inlines into index.html.

    python3 icons.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE / 'assets' / 'icons'
JS = HERE / 'build' / 'icons.js'

# Each entry is the inner markup of a 24x24 icon. Keep to the grid: 3 unit
# margin, 18 unit live area, and let shapes breathe rather than filling it.
ICONS = {
    # a document under a loupe: sizing up the estate before anyone touches it
    'assessments': """
      <path d="M5 3.6h8.2L18 8.2v5.1"/>
      <path d="M13 3.6v4.8h4.8"/>
      <path d="M5 3.6v16.8h6"/>
      <path d="M8 9.4h3.2M8 12.6h2.4"/>
      <circle cx="16.1" cy="16.1" r="3.6"/>
      <path d="M18.7 18.7 21 21"/>""",

    # stacked platform layers with the top one landing
    'implementation': """
      <path d="M12 2.9 20.6 7 12 11.1 3.4 7z"/>
      <path d="m3.4 12 8.6 4.1 8.6-4.1"/>
      <path d="m3.4 17 8.6 4.1 8.6-4.1"/>""",

    # mortarboard: Align Academy
    'training': """
      <path d="M12 4 22 8.4 12 12.8 2 8.4z"/>
      <path d="M6.4 10.6v4.8c0 1.6 2.5 3 5.6 3s5.6-1.4 5.6-3v-4.8"/>
      <path d="M21 9.3v5.2"/>""",

    # two systems joined by a link
    'integration': """
      <rect x="2.6" y="3.2" width="7.6" height="7.6" rx="2.2"/>
      <rect x="13.8" y="13.2" width="7.6" height="7.6" rx="2.2"/>
      <path d="M13.6 6.4h3.4a3.4 3.4 0 0 1 3.4 3.4v.8"/>
      <path d="M10.4 17.6H7a3.4 3.4 0 0 1-3.4-3.4v-.8"/>
      <path d="m11.2 4.4 2.4 2-2.4 2M12.8 15.6l-2.4 2 2.4 2"/>""",

    # legacy store piping into the new one
    'data-conversion': """
      <ellipse cx="6.2" cy="5.6" rx="3.3" ry="1.9"/>
      <path d="M2.9 5.6v5.2c0 1 1.5 1.9 3.3 1.9s3.3-.9 3.3-1.9V5.6"/>
      <ellipse cx="17.8" cy="13.2" rx="3.3" ry="1.9"/>
      <path d="M14.5 13.2v5.2c0 1 1.5 1.9 3.3 1.9s3.3-.9 3.3-1.9v-5.2"/>
      <path d="M10.4 9.1h4.2a3 3 0 0 1 3 3v.4"/>
      <path d="m15.9 7.2 2.1 1.9-2.1 1.9"/>""",

    # headset: the desk that picks up
    'support': """
      <path d="M4.2 14.4v-2.6a7.8 7.8 0 0 1 15.6 0v2.6"/>
      <rect x="2.6" y="13.1" width="4" height="5.6" rx="1.8"/>
      <rect x="17.4" y="13.1" width="4" height="5.6" rx="1.8"/>
      <path d="M19.8 18.7v.6a2.4 2.4 0 0 1-2.4 2.4H13"/>""",

    # the line goes up and to the right, with a spark on the peak
    'optimization': """
      <path d="M3.2 20.8h17.6"/>
      <path d="m4.6 16.6 4.5-4.7 3.4 3 5.3-6"/>
      <path d="M14.6 8.9h3.2v3.2"/>
      <path d="M6.6 6.1 7.3 4l.7 2.1 2.1.7-2.1.7L7.3 9.6l-.7-2.1L4.5 6.8z"/>""",

    # a partial ring: part time capacity plugged into a whole team
    'fractional': """
      <circle cx="12" cy="12" r="8.6"/>
      <path d="M12 3.4A8.6 8.6 0 0 1 20.6 12H12z"/>""",

    # a lead standing in front of the team
    'client-side': """
      <circle cx="9.4" cy="7.6" r="3.4"/>
      <path d="M3.2 20.4a6.2 6.2 0 0 1 12.4 0"/>
      <path d="M16.4 5.2a3.4 3.4 0 0 1 0 6.6"/>
      <path d="M18 14.6a6.2 6.2 0 0 1 2.8 5.2"/>""",

    # two entities merging into one
    'ma': """
      <path d="M2.8 4.8h2.6a5 5 0 0 1 5 5v4.4a5 5 0 0 0 5 5h5"/>
      <path d="M2.8 19.2h2.6a5 5 0 0 0 5-5"/>
      <path d="m17.2 15.6 3.6 3.6-3.6 3.6"/>""",
}

HEAD = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
        'fill="none" stroke="currentColor" stroke-width="1.7" '
        'stroke-linecap="round" stroke-linejoin="round">')


def normalise(body):
    return ' '.join(body.split())


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    table = {}
    for name, body in ICONS.items():
        body = normalise(body)
        table[name] = body
        (OUT / f'{name}.svg').write_text(f'{HEAD}{body}</svg>\n')
    JS.parent.mkdir(parents=True, exist_ok=True)
    JS.write_text('/* generated by icons.py, do not edit */\n'
                  'const ICONS = ' + json.dumps(table, indent=0) + ';\n')
    print(f'{len(table)} icons -> {OUT.relative_to(HERE)}/ and {JS.relative_to(HERE)}')


if __name__ == '__main__':
    main()
